%------------------------------------------------------------------------------
% File     : COM012+3 : TPTP v6.1.0. Released v4.0.0.
% Domain   : Computing Theory
% Problem  : Newman's lemma on rewriting systems 01, 02 expansion
% Version  : Especial.
% English  :

% Refs     : [VLP07] Verchinine et al. (2007), System for Automated Deduction
%          : [PV+07] Paskevich et al. (2007), Reasoning Inside a Formula an
%          : [Pas08] Paskevich (2008), Email to G. Sutcliffe
% Source   : [Pas08]
% Names    : newman_01.02 [Pas08]

% Status   : Theorem
% Rating   : 0.04 v6.1.0, 0.07 v6.0.0, 0.04 v5.4.0, 0.07 v5.3.0, 0.11 v5.2.0, 0.00 v5.1.0, 0.10 v5.0.0, 0.17 v4.1.0, 0.22 v4.0.1, 0.48 v4.0.0
% Syntax   : Number of formulae    :   10 (   0 unit)
%            Number of atoms       :   63 (   4 equality)
%            Maximal formula depth :   11 (   6 average)
%            Number of connectives :   53 (   0 ~  ;  10  |;  28  &)
%                                         (   2 <=>;  13 =>;   0 <=)
%                                         (   0 <~>;   0 ~|;   0 ~&)
%            Number of predicates  :    7 (   0 propositional; 1-3 arity)
%            Number of functors    :    4 (   4 constant; 0-0 arity)
%            Number of variables   :   24 (   0 singleton;  20 !;   4 ?)
%            Maximal term depth    :    1 (   1 average)
% SPC      : FOF_THM_RFO_SEQ

% Comments : Problem generated by the SAD system [VLP07]
%------------------------------------------------------------------------------
fof(mElmSort,axiom,(
    ! [W0] :
      ( aElement0(W0)
     => $true ) )).

fof(mRelSort,axiom,(
    ! [W0] :
      ( aRewritingSystem0(W0)
     => $true ) )).

fof(mReduct,axiom,(
    ! [W0,W1] :
      ( ( aElement0(W0)
        & aRewritingSystem0(W1) )
     => ! [W2] :
          ( aReductOfIn0(W2,W0,W1)
         => aElement0(W2) ) ) )).

fof(mWFOrd,axiom,(
    ! [W0,W1] :
      ( ( aElement0(W0)
        & aElement0(W1) )
     => ( iLess0(W0,W1)
       => $true ) ) )).

fof(mTCbr,axiom,(
    ! [W0,W1,W2] :
      ( ( aElement0(W0)
        & aRewritingSystem0(W1)
        & aElement0(W2) )
     => ( sdtmndtplgtdt0(W0,W1,W2)
       => $true ) ) )).

fof(mTCDef,definition,(
    ! [W0,W1,W2] :
      ( ( aElement0(W0)
        & aRewritingSystem0(W1)
        & aElement0(W2) )
     => ( sdtmndtplgtdt0(W0,W1,W2)
      <=> ( aReductOfIn0(W2,W0,W1)
          | ? [W3] :
              ( aElement0(W3)
              & aReductOfIn0(W3,W0,W1)
              & sdtmndtplgtdt0(W3,W1,W2) ) ) ) ) )).

fof(mTCTrans,axiom,(
    ! [W0,W1,W2,W3] :
      ( ( aElement0(W0)
        & aRewritingSystem0(W1)
        & aElement0(W2)
        & aElement0(W3) )
     => ( ( sdtmndtplgtdt0(W0,W1,W2)
          & sdtmndtplgtdt0(W2,W1,W3) )
       => sdtmndtplgtdt0(W0,W1,W3) ) ) )).

fof(mTCRDef,definition,(
    ! [W0,W1,W2] :
      ( ( aElement0(W0)
        & aRewritingSystem0(W1)
        & aElement0(W2) )
     => ( sdtmndtasgtdt0(W0,W1,W2)
      <=> ( W0 = W2
          | sdtmndtplgtdt0(W0,W1,W2) ) ) ) )).

fof(m__349,hypothesis,
    ( aElement0(xx)
    & aRewritingSystem0(xR)
    & aElement0(xy)
    & aElement0(xz) )).

fof(m__,conjecture,
    ( ( ( xx = xy
        | ( ( aReductOfIn0(xy,xx,xR)
            | ? [W0] :
                ( aElement0(W0)
                & aReductOfIn0(W0,xx,xR)
                & sdtmndtplgtdt0(W0,xR,xy) ) )
          & sdtmndtplgtdt0(xx,xR,xy) ) )
      & sdtmndtasgtdt0(xx,xR,xy)
      & ( xy = xz
        | ( ( aReductOfIn0(xz,xy,xR)
            | ? [W0] :
                ( aElement0(W0)
                & aReductOfIn0(W0,xy,xR)
                & sdtmndtplgtdt0(W0,xR,xz) ) )
          & sdtmndtplgtdt0(xy,xR,xz) ) )
      & sdtmndtasgtdt0(xy,xR,xz) )
   => ( xx = xz
      | aReductOfIn0(xz,xx,xR)
      | ? [W0] :
          ( aElement0(W0)
          & aReductOfIn0(W0,xx,xR)
          & sdtmndtplgtdt0(W0,xR,xz) )
      | sdtmndtplgtdt0(xx,xR,xz)
      | sdtmndtasgtdt0(xx,xR,xz) ) )).

%------------------------------------------------------------------------------
