%------------------------------------------------------------------------------
% File     : CSR052+1 : TPTP v6.1.0. Released v3.4.0.
% Domain   : Common Sense Reasoning
% Problem  : Autogenerated Cyc Problem CSR052+1
% Version  : Especial.
% English  :

% Refs     : [RS+]   Reagan Smith et al., The Cyc TPTP Challenge Problem
% Source   : [RS+]
% Names    :

% Status   : Theorem
% Rating   : 0.00 v6.1.0, 0.04 v6.0.0, 0.25 v5.5.0, 0.08 v5.4.0, 0.13 v5.3.0, 0.22 v5.2.0, 0.07 v5.0.0, 0.10 v4.1.0, 0.06 v4.0.1, 0.00 v3.4.0
% Syntax   : Number of formulae    :   96 (  27 unit)
%            Number of atoms       :  178 (   0 equality)
%            Maximal formula depth :    7 (   3 average)
%            Number of connectives :   83 (   1 ~  ;   0  |;  14  &)
%                                         (   0 <=>;  68 =>;   0 <=)
%                                         (   0 <~>;   0 ~|;   0 ~&)
%            Number of predicates  :   26 (   0 propositional; 1-3 arity)
%            Number of functors    :   27 (  24 constant; 0-2 arity)
%            Number of variables   :  128 (   0 singleton; 128 !;   0 ?)
%            Maximal term depth    :    4 (   1 average)
% SPC      : FOF_THM_RFO_NEQ

% Comments : Autogenerated from the OpenCyc KB. Documentation can be found at
%            http://opencyc.org/doc/#TPTP_Challenge_Problem_Set
%          : Cyc(R) Knowledge Base Copyright(C) 1995-2007 Cycorp, Inc., Austin,
%            TX, USA. All rights reserved.
%          : OpenCyc Knowledge Base Copyright(C) 2001-2007 Cycorp, Inc.,
%            Austin, TX, USA. All rights reserved.
%------------------------------------------------------------------------------
%$problem_series(cyc_scaling_1,[CSR025+1,CSR026+1,CSR027+1,CSR028+1,CSR029+1,CSR030+1,CSR031+1,CSR032+1,CSR033+1,CSR034+1,CSR035+1,CSR036+1,CSR037+1,CSR038+1,CSR039+1,CSR040+1,CSR041+1,CSR042+1,CSR043+1,CSR044+1,CSR045+1,CSR046+1,CSR047+1,CSR048+1,CSR049+1,CSR050+1,CSR051+1,CSR052+1,CSR053+1,CSR054+1,CSR055+1,CSR056+1,CSR057+1,CSR058+1,CSR059+1,CSR060+1,CSR061+1,CSR062+1,CSR063+1,CSR064+1,CSR065+1,CSR066+1,CSR067+1,CSR068+1,CSR069+1,CSR070+1,CSR071+1,CSR072+1,CSR073+1,CSR074+1])
%$static(cyc_scaling_1,include('Axioms/CSR002+0.ax'))
%----Empty file include('Axioms/CSR002+0.ax').
%------------------------------------------------------------------------------
% Cyc Assertion #455528:
fof(just1,axiom,(
    transitivebinarypredicate(c_genls) )).

% Cyc Assertion #592971:
fof(just2,axiom,(
    genlmt(c_cycorpproductsmt,c_basekb) )).

% Cyc Assertion #600900:
fof(just3,axiom,(
    genlmt(c_cycnounlearnermt,c_cycorpproductsmt) )).

% Cyc Assertion #829544:
fof(just4,axiom,(
    genlmt(f_contentmtofcdafromeventfn(f_urlreferentfn(f_urlfn(s_http_ukencartamsncomencyclopedia_761573010_4united_states_of_americahtml)),c_translation_33),c_machinelearningspindleheadmt) )).

% Cyc Assertion #1322220:
fof(just5,axiom,(
    transitivebinarypredicate(c_genlmt) )).

% Cyc Assertion #1614635:
fof(just6,axiom,(
    genlmt(c_machinelearningspindleheadmt,c_cycnounlearnermt) )).

% Cyc Assertion #1650755:
fof(just7,axiom,(
    genlmt(c_basekb,c_universalvocabularymt) )).

% Cyc Assertion #1922596:
fof(just8,axiom,(
    genls(c_tptpcol_8_39940,c_tptpcol_7_39939) )).

fof(just9,axiom,(
    ! [OBJ] :
      ( tptpcol_8_39940(OBJ)
     => tptpcol_7_39939(OBJ) ) )).

% Cyc Assertion #1923235:
fof(just10,axiom,(
    genls(c_tptpcol_9_40196,c_tptpcol_8_39940) )).

fof(just11,axiom,(
    ! [OBJ] :
      ( tptpcol_9_40196(OBJ)
     => tptpcol_8_39940(OBJ) ) )).

% Cyc Assertion #1923554:
fof(just12,axiom,(
    genls(c_tptpcol_10_40324,c_tptpcol_9_40196) )).

fof(just13,axiom,(
    ! [OBJ] :
      ( tptpcol_10_40324(OBJ)
     => tptpcol_9_40196(OBJ) ) )).

% Cyc Assertion #1923713:
fof(just14,axiom,(
    genls(c_tptpcol_11_40388,c_tptpcol_10_40324) )).

fof(just15,axiom,(
    ! [OBJ] :
      ( tptpcol_11_40388(OBJ)
     => tptpcol_10_40324(OBJ) ) )).

% Cyc Assertion #1923792:
fof(just16,axiom,(
    genls(c_tptpcol_12_40420,c_tptpcol_11_40388) )).

fof(just17,axiom,(
    ! [OBJ] :
      ( tptpcol_12_40420(OBJ)
     => tptpcol_11_40388(OBJ) ) )).

% Cyc Assertion #1923794:
fof(just18,axiom,(
    genls(c_tptpcol_13_40421,c_tptpcol_12_40420) )).

fof(just19,axiom,(
    ! [OBJ] :
      ( tptpcol_13_40421(OBJ)
     => tptpcol_12_40420(OBJ) ) )).

% Cyc Assertion #1923813:
fof(just20,axiom,(
    genls(c_tptpcol_14_40429,c_tptpcol_13_40421) )).

fof(just21,axiom,(
    ! [OBJ] :
      ( tptpcol_14_40429(OBJ)
     => tptpcol_13_40421(OBJ) ) )).

% Cyc Assertion #1923815:
fof(just22,axiom,(
    genls(c_tptpcol_15_40430,c_tptpcol_14_40429) )).

fof(just23,axiom,(
    ! [OBJ] :
      ( tptpcol_15_40430(OBJ)
     => tptpcol_14_40429(OBJ) ) )).

% Cyc Assertion #398814:
fof(just24,axiom,(
    ! [OBJ,COL1,COL2] :
      ~ ( isa(OBJ,COL1)
        & isa(OBJ,COL2)
        & disjointwith(COL1,COL2) ) )).

% Cyc Assertion #831913:
fof(just25,axiom,(
    ! [SPECPRED,PRED,GENLPRED] :
      ( ( genlinverse(SPECPRED,PRED)
        & genlinverse(PRED,GENLPRED) )
     => genlpreds(SPECPRED,GENLPRED) ) )).

% Cyc Constant #40273:
fof(just26,axiom,(
    ! [ARG1,INS] :
      ( genlpreds(ARG1,INS)
     => predicate(INS) ) )).

fof(just27,axiom,(
    ! [ARG1,INS] :
      ( genlpreds(ARG1,INS)
     => predicate(INS) ) )).

fof(just28,axiom,(
    ! [INS,ARG2] :
      ( genlpreds(INS,ARG2)
     => predicate(INS) ) )).

fof(just29,axiom,(
    ! [INS,ARG2] :
      ( genlpreds(INS,ARG2)
     => predicate(INS) ) )).

fof(just30,axiom,(
    ! [X,Y,Z] :
      ( ( genlpreds(X,Y)
        & genlpreds(Y,Z) )
     => genlpreds(X,Z) ) )).

fof(just31,axiom,(
    ! [X] :
      ( predicate(X)
     => genlpreds(X,X) ) )).

fof(just32,axiom,(
    ! [X] :
      ( predicate(X)
     => genlpreds(X,X) ) )).

% Cyc Constant #45259:
fof(just33,axiom,(
    ! [ARG1,INS] :
      ( genlinverse(ARG1,INS)
     => binarypredicate(INS) ) )).

fof(just34,axiom,(
    ! [INS,ARG2] :
      ( genlinverse(INS,ARG2)
     => binarypredicate(INS) ) )).

fof(just35,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( genlinverse(OLD,ARG2)
        & genlpreds(NEW,OLD) )
     => genlinverse(NEW,ARG2) ) )).

fof(just36,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( genlinverse(ARG1,OLD)
        & genlpreds(OLD,NEW) )
     => genlinverse(ARG1,NEW) ) )).

% Cyc Constant #78648:
fof(just37,axiom,(
    ! [ARG1,INS] :
      ( disjointwith(ARG1,INS)
     => collection(INS) ) )).

fof(just38,axiom,(
    ! [INS,ARG2] :
      ( disjointwith(INS,ARG2)
     => collection(INS) ) )).

fof(just39,axiom,(
    ! [X,Y] :
      ( disjointwith(X,Y)
     => disjointwith(Y,X) ) )).

fof(just40,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( disjointwith(ARG1,OLD)
        & genls(NEW,OLD) )
     => disjointwith(ARG1,NEW) ) )).

fof(just41,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( disjointwith(OLD,ARG2)
        & genls(NEW,OLD) )
     => disjointwith(NEW,ARG2) ) )).

% Cyc Constant #170027:
fof(just42,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_15_40430)
     => tptpcol_15_40430(X) ) )).

fof(just43,axiom,(
    ! [X] :
      ( tptpcol_15_40430(X)
     => isa(X,c_tptpcol_15_40430) ) )).

% Cyc Constant #170026:
fof(just44,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_14_40429)
     => tptpcol_14_40429(X) ) )).

fof(just45,axiom,(
    ! [X] :
      ( tptpcol_14_40429(X)
     => isa(X,c_tptpcol_14_40429) ) )).

% Cyc Constant #170018:
fof(just46,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_13_40421)
     => tptpcol_13_40421(X) ) )).

fof(just47,axiom,(
    ! [X] :
      ( tptpcol_13_40421(X)
     => isa(X,c_tptpcol_13_40421) ) )).

% Cyc Constant #170017:
fof(just48,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_12_40420)
     => tptpcol_12_40420(X) ) )).

fof(just49,axiom,(
    ! [X] :
      ( tptpcol_12_40420(X)
     => isa(X,c_tptpcol_12_40420) ) )).

% Cyc Constant #169985:
fof(just50,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_11_40388)
     => tptpcol_11_40388(X) ) )).

fof(just51,axiom,(
    ! [X] :
      ( tptpcol_11_40388(X)
     => isa(X,c_tptpcol_11_40388) ) )).

% Cyc Constant #169921:
fof(just52,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_10_40324)
     => tptpcol_10_40324(X) ) )).

fof(just53,axiom,(
    ! [X] :
      ( tptpcol_10_40324(X)
     => isa(X,c_tptpcol_10_40324) ) )).

% Cyc Constant #169793:
fof(just54,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_9_40196)
     => tptpcol_9_40196(X) ) )).

fof(just55,axiom,(
    ! [X] :
      ( tptpcol_9_40196(X)
     => isa(X,c_tptpcol_9_40196) ) )).

% Cyc Constant #169536:
fof(just56,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_7_39939)
     => tptpcol_7_39939(X) ) )).

fof(just57,axiom,(
    ! [X] :
      ( tptpcol_7_39939(X)
     => isa(X,c_tptpcol_7_39939) ) )).

% Cyc Constant #169537:
fof(just58,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_8_39940)
     => tptpcol_8_39940(X) ) )).

fof(just59,axiom,(
    ! [X] :
      ( tptpcol_8_39940(X)
     => isa(X,c_tptpcol_8_39940) ) )).

% Cyc Constant #129091:
fof(just60,axiom,(
    ! [ARG1] : natfunction(f_urlfn(ARG1),c_urlfn) )).

fof(just61,axiom,(
    ! [ARG1] : natargument(f_urlfn(ARG1),n_1,ARG1) )).

fof(just62,axiom,(
    ! [ARG1] : uniformresourcelocator(f_urlfn(ARG1)) )).

% Cyc Constant #78971:
fof(just63,axiom,(
    ! [ARG1] : natfunction(f_urlreferentfn(ARG1),c_urlreferentfn) )).

fof(just64,axiom,(
    ! [ARG1] : natargument(f_urlreferentfn(ARG1),n_1,ARG1) )).

fof(just65,axiom,(
    ! [ARG1] : computerdataartifact(f_urlreferentfn(ARG1)) )).

% Cyc Constant #71728:
fof(just66,axiom,(
    ! [ARG1,ARG2] : natfunction(f_contentmtofcdafromeventfn(ARG1,ARG2),c_contentmtofcdafromeventfn) )).

fof(just67,axiom,(
    ! [ARG1,ARG2] : natargument(f_contentmtofcdafromeventfn(ARG1,ARG2),n_1,ARG1) )).

fof(just68,axiom,(
    ! [ARG1,ARG2] : natargument(f_contentmtofcdafromeventfn(ARG1,ARG2),n_2,ARG2) )).

fof(just69,axiom,(
    ! [ARG1,ARG2] : microtheory(f_contentmtofcdafromeventfn(ARG1,ARG2)) )).

% Cyc Constant #19550:
fof(just70,axiom,(
    ! [SPECMT,GENLMT] :
      ( ( mtvisible(SPECMT)
        & genlmt(SPECMT,GENLMT) )
     => mtvisible(GENLMT) ) )).

fof(just71,axiom,(
    ! [ARG1,INS] :
      ( genlmt(ARG1,INS)
     => microtheory(INS) ) )).

fof(just72,axiom,(
    ! [ARG1,INS] :
      ( genlmt(ARG1,INS)
     => microtheory(INS) ) )).

fof(just73,axiom,(
    ! [INS,ARG2] :
      ( genlmt(INS,ARG2)
     => microtheory(INS) ) )).

fof(just74,axiom,(
    ! [INS,ARG2] :
      ( genlmt(INS,ARG2)
     => microtheory(INS) ) )).

fof(just75,axiom,(
    ! [X,Y,Z] :
      ( ( genlmt(X,Y)
        & genlmt(Y,Z) )
     => genlmt(X,Z) ) )).

fof(just76,axiom,(
    ! [X] :
      ( microtheory(X)
     => genlmt(X,X) ) )).

fof(just77,axiom,(
    ! [X] :
      ( microtheory(X)
     => genlmt(X,X) ) )).

% Cyc Constant #27757:
fof(just78,axiom,(
    mtvisible(c_basekb) )).

% Cyc Constant #127156:
fof(just79,axiom,(
    ! [X] :
      ( isa(X,c_transitivebinarypredicate)
     => transitivebinarypredicate(X) ) )).

fof(just80,axiom,(
    ! [X] :
      ( transitivebinarypredicate(X)
     => isa(X,c_transitivebinarypredicate) ) )).

% Cyc Constant #0:
fof(just81,axiom,(
    ! [ARG1,INS] :
      ( genls(ARG1,INS)
     => collection(INS) ) )).

fof(just82,axiom,(
    ! [ARG1,INS] :
      ( genls(ARG1,INS)
     => collection(INS) ) )).

fof(just83,axiom,(
    ! [INS,ARG2] :
      ( genls(INS,ARG2)
     => collection(INS) ) )).

fof(just84,axiom,(
    ! [INS,ARG2] :
      ( genls(INS,ARG2)
     => collection(INS) ) )).

fof(just85,axiom,(
    ! [X,Y,Z] :
      ( ( genls(X,Y)
        & genls(Y,Z) )
     => genls(X,Z) ) )).

fof(just86,axiom,(
    ! [X] :
      ( collection(X)
     => genls(X,X) ) )).

fof(just87,axiom,(
    ! [X] :
      ( collection(X)
     => genls(X,X) ) )).

fof(just88,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( genls(OLD,ARG2)
        & genls(NEW,OLD) )
     => genls(NEW,ARG2) ) )).

fof(just89,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( genls(ARG1,OLD)
        & genls(OLD,NEW) )
     => genls(ARG1,NEW) ) )).

% Cyc Constant #72115:
fof(just90,axiom,(
    ! [ARG1,INS] :
      ( isa(ARG1,INS)
     => collection(INS) ) )).

fof(just91,axiom,(
    ! [ARG1,INS] :
      ( isa(ARG1,INS)
     => collection(INS) ) )).

fof(just92,axiom,(
    ! [INS,ARG2] :
      ( isa(INS,ARG2)
     => thing(INS) ) )).

fof(just93,axiom,(
    ! [INS,ARG2] :
      ( isa(INS,ARG2)
     => thing(INS) ) )).

fof(just94,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( isa(ARG1,OLD)
        & genls(OLD,NEW) )
     => isa(ARG1,NEW) ) )).

% Cyc Constant #95028:
fof(just95,axiom,(
    mtvisible(c_universalvocabularymt) )).

fof(query52,conjecture,
    ( mtvisible(f_contentmtofcdafromeventfn(f_urlreferentfn(f_urlfn(s_http_ukencartamsncomencyclopedia_761573010_4united_states_of_americahtml)),c_translation_33))
   => genls(c_tptpcol_15_40430,c_tptpcol_7_39939) )).

%------------------------------------------------------------------------------
