%------------------------------------------------------------------------------
% File     : CSR029+1 : TPTP v6.1.0. Released v3.4.0.
% Domain   : Common Sense Reasoning
% Problem  : Autogenerated Cyc Problem CSR029+1
% Version  : Especial.
% English  :

% Refs     : [RS+]   Reagan Smith et al., The Cyc TPTP Challenge Problem
% Source   : [RS+]
% Names    :

% Status   : Theorem
% Rating   : 0.00 v6.0.0, 0.33 v5.5.0, 0.22 v5.4.0, 0.11 v5.3.0, 0.09 v5.2.0, 0.00 v4.1.0, 0.06 v4.0.1, 0.00 v3.4.0
% Syntax   : Number of formulae    :   58 (  10 unit)
%            Number of atoms       :  119 (   0 equality)
%            Maximal formula depth :    7 (   4 average)
%            Number of connectives :   62 (   1 ~  ;   0  |;  14  &)
%                                         (   0 <=>;  47 =>;   0 <=)
%                                         (   0 <~>;   0 ~|;   0 ~&)
%            Number of predicates  :   18 (   0 propositional; 1-2 arity)
%            Number of functors    :   14 (  14 constant; 0-0 arity)
%            Number of variables   :   89 (   0 singleton;  89 !;   0 ?)
%            Maximal term depth    :    1 (   1 average)
% SPC      : FOF_THM_EPR

% Comments : Autogenerated from the OpenCyc KB. Documentation can be found at
%            http://opencyc.org/doc/#TPTP_Challenge_Problem_Set
%          : Cyc(R) Knowledge Base Copyright(C) 1995-2007 Cycorp, Inc., Austin,
%            TX, USA. All rights reserved.
%          : OpenCyc Knowledge Base Copyright(C) 2001-2007 Cycorp, Inc.,
%            Austin, TX, USA. All rights reserved.
%------------------------------------------------------------------------------
%$problem_series(cyc_scaling_1,[CSR025+1,CSR026+1,CSR027+1,CSR028+1,CSR029+1,CSR030+1,CSR031+1,CSR032+1,CSR033+1,CSR034+1,CSR035+1,CSR036+1,CSR037+1,CSR038+1,CSR039+1,CSR040+1,CSR041+1,CSR042+1,CSR043+1,CSR044+1,CSR045+1,CSR046+1,CSR047+1,CSR048+1,CSR049+1,CSR050+1,CSR051+1,CSR052+1,CSR053+1,CSR054+1,CSR055+1,CSR056+1,CSR057+1,CSR058+1,CSR059+1,CSR060+1,CSR061+1,CSR062+1,CSR063+1,CSR064+1,CSR065+1,CSR066+1,CSR067+1,CSR068+1,CSR069+1,CSR070+1,CSR071+1,CSR072+1,CSR073+1,CSR074+1])
%$static(cyc_scaling_1,include('Axioms/CSR002+0.ax'))
%----Empty file include('Axioms/CSR002+0.ax').
%------------------------------------------------------------------------------
% Cyc Assertion #253062:
fof(just1,axiom,(
    genlmt(c_geographymt,c_basekb) )).

% Cyc Assertion #536720:
fof(just2,axiom,(
    transitivebinarypredicate(c_inregion) )).

% Cyc Assertion #631445:
fof(just3,axiom,(
    genlmt(c_worldgeographymt,c_geographymt) )).

% Cyc Assertion #1144679:
fof(just4,axiom,(
    genlinverse(c_geographicalsubregions,c_inregion) )).

fof(just5,axiom,(
    ! [ARG1,ARG2] :
      ( geographicalsubregions(ARG1,ARG2)
     => inregion(ARG2,ARG1) ) )).

% Cyc Assertion #1322220:
fof(just6,axiom,(
    transitivebinarypredicate(c_genlmt) )).

% Cyc Assertion #1650755:
fof(just7,axiom,(
    genlmt(c_basekb,c_universalvocabularymt) )).

% Cyc Assertion #2463131:
fof(just8,axiom,(
    genlmt(c_tptpgeo_spindleheadmt,c_worldgeographymt) )).

% Cyc Assertion #2463146:
fof(just9,axiom,(
    genlmt(c_tptpgeo_member3_mt,c_tptpgeo_spindleheadmt) )).

% Cyc Assertion #2477332:
fof(just10,axiom,
    ( mtvisible(c_worldgeographymt)
   => geolevel_3(c_georegion_l3_x4_y13) )).

% Cyc Assertion #2493055:
fof(just11,axiom,
    ( mtvisible(c_tptpgeo_member3_mt)
   => geographicalsubregions(c_georegion_l3_x4_y13,c_georegion_l4_x14_y39) )).

% Cyc Assertion #2499616:
fof(just12,axiom,
    ( mtvisible(c_tptpgeo_member3_mt)
   => inregion(c_geolocation_x14_y39,c_georegion_l4_x14_y39) )).

% Cyc Assertion #398814:
fof(just13,axiom,(
    ! [OBJ,COL1,COL2] :
      ~ ( isa(OBJ,COL1)
        & isa(OBJ,COL2)
        & disjointwith(COL1,COL2) ) )).

% Cyc Assertion #831913:
fof(just14,axiom,(
    ! [SPECPRED,PRED,GENLPRED] :
      ( ( genlinverse(SPECPRED,PRED)
        & genlinverse(PRED,GENLPRED) )
     => genlpreds(SPECPRED,GENLPRED) ) )).

% Cyc Constant #40273:
fof(just15,axiom,(
    ! [ARG1,INS] :
      ( genlpreds(ARG1,INS)
     => predicate(INS) ) )).

fof(just16,axiom,(
    ! [ARG1,INS] :
      ( genlpreds(ARG1,INS)
     => predicate(INS) ) )).

fof(just17,axiom,(
    ! [INS,ARG2] :
      ( genlpreds(INS,ARG2)
     => predicate(INS) ) )).

fof(just18,axiom,(
    ! [INS,ARG2] :
      ( genlpreds(INS,ARG2)
     => predicate(INS) ) )).

fof(just19,axiom,(
    ! [X,Y,Z] :
      ( ( genlpreds(X,Y)
        & genlpreds(Y,Z) )
     => genlpreds(X,Z) ) )).

fof(just20,axiom,(
    ! [X] :
      ( predicate(X)
     => genlpreds(X,X) ) )).

fof(just21,axiom,(
    ! [X] :
      ( predicate(X)
     => genlpreds(X,X) ) )).

% Cyc Constant #78648:
fof(just22,axiom,(
    ! [ARG1,INS] :
      ( disjointwith(ARG1,INS)
     => collection(INS) ) )).

fof(just23,axiom,(
    ! [INS,ARG2] :
      ( disjointwith(INS,ARG2)
     => collection(INS) ) )).

fof(just24,axiom,(
    ! [X,Y] :
      ( disjointwith(X,Y)
     => disjointwith(Y,X) ) )).

fof(just25,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( disjointwith(ARG1,OLD)
        & genls(NEW,OLD) )
     => disjointwith(ARG1,NEW) ) )).

fof(just26,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( disjointwith(OLD,ARG2)
        & genls(NEW,OLD) )
     => disjointwith(NEW,ARG2) ) )).

% Cyc Constant #380145:
fof(just27,axiom,(
    ! [X] :
      ( isa(X,c_geolevel_3)
     => geolevel_3(X) ) )).

fof(just28,axiom,(
    ! [X] :
      ( geolevel_3(X)
     => isa(X,c_geolevel_3) ) )).

% Cyc Constant #119918:
fof(just29,axiom,(
    ! [ARG1,INS] :
      ( geographicalsubregions(ARG1,INS)
     => geographicalregion(INS) ) )).

fof(just30,axiom,(
    ! [INS,ARG2] :
      ( geographicalsubregions(INS,ARG2)
     => geographicalregion(INS) ) )).

fof(just31,axiom,(
    ! [X,Y,Z] :
      ( ( geographicalsubregions(X,Y)
        & geographicalsubregions(Y,Z) )
     => geographicalsubregions(X,Z) ) )).

fof(just32,axiom,(
    ! [X] :
      ( geographicalregion(X)
     => geographicalsubregions(X,X) ) )).

% Cyc Constant #45259:
fof(just33,axiom,(
    ! [ARG1,INS] :
      ( genlinverse(ARG1,INS)
     => binarypredicate(INS) ) )).

fof(just34,axiom,(
    ! [INS,ARG2] :
      ( genlinverse(INS,ARG2)
     => binarypredicate(INS) ) )).

fof(just35,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( genlinverse(OLD,ARG2)
        & genlpreds(NEW,OLD) )
     => genlinverse(NEW,ARG2) ) )).

fof(just36,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( genlinverse(ARG1,OLD)
        & genlpreds(OLD,NEW) )
     => genlinverse(ARG1,NEW) ) )).

% Cyc Constant #127156:
fof(just37,axiom,(
    ! [X] :
      ( isa(X,c_transitivebinarypredicate)
     => transitivebinarypredicate(X) ) )).

fof(just38,axiom,(
    ! [X] :
      ( transitivebinarypredicate(X)
     => isa(X,c_transitivebinarypredicate) ) )).

% Cyc Constant #98385:
fof(just39,axiom,(
    ! [ARG1,INS] :
      ( inregion(ARG1,INS)
     => spatialthing_nonsituational(INS) ) )).

fof(just40,axiom,(
    ! [INS,ARG2] :
      ( inregion(INS,ARG2)
     => spatialthing_nonsituational(INS) ) )).

fof(just41,axiom,(
    ! [X,Y,Z] :
      ( ( inregion(X,Y)
        & inregion(Y,Z) )
     => inregion(X,Z) ) )).

fof(just42,axiom,(
    ! [X] :
      ( spatialthing_nonsituational(X)
     => inregion(X,X) ) )).

% Cyc Constant #72115:
fof(just43,axiom,(
    ! [ARG1,INS] :
      ( isa(ARG1,INS)
     => collection(INS) ) )).

fof(just44,axiom,(
    ! [ARG1,INS] :
      ( isa(ARG1,INS)
     => collection(INS) ) )).

fof(just45,axiom,(
    ! [INS,ARG2] :
      ( isa(INS,ARG2)
     => thing(INS) ) )).

fof(just46,axiom,(
    ! [INS,ARG2] :
      ( isa(INS,ARG2)
     => thing(INS) ) )).

fof(just47,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( isa(ARG1,OLD)
        & genls(OLD,NEW) )
     => isa(ARG1,NEW) ) )).

% Cyc Constant #95028:
fof(just48,axiom,(
    mtvisible(c_universalvocabularymt) )).

% Cyc Constant #19550:
fof(just49,axiom,(
    ! [SPECMT,GENLMT] :
      ( ( mtvisible(SPECMT)
        & genlmt(SPECMT,GENLMT) )
     => mtvisible(GENLMT) ) )).

fof(just50,axiom,(
    ! [ARG1,INS] :
      ( genlmt(ARG1,INS)
     => microtheory(INS) ) )).

fof(just51,axiom,(
    ! [ARG1,INS] :
      ( genlmt(ARG1,INS)
     => microtheory(INS) ) )).

fof(just52,axiom,(
    ! [INS,ARG2] :
      ( genlmt(INS,ARG2)
     => microtheory(INS) ) )).

fof(just53,axiom,(
    ! [INS,ARG2] :
      ( genlmt(INS,ARG2)
     => microtheory(INS) ) )).

fof(just54,axiom,(
    ! [X,Y,Z] :
      ( ( genlmt(X,Y)
        & genlmt(Y,Z) )
     => genlmt(X,Z) ) )).

fof(just55,axiom,(
    ! [X] :
      ( microtheory(X)
     => genlmt(X,X) ) )).

fof(just56,axiom,(
    ! [X] :
      ( microtheory(X)
     => genlmt(X,X) ) )).

% Cyc Constant #27757:
fof(just57,axiom,(
    mtvisible(c_basekb) )).

fof(query29,conjecture,
    ( mtvisible(c_tptpgeo_member3_mt)
   => ( inregion(c_geolocation_x14_y39,c_georegion_l3_x4_y13)
      & geolevel_3(c_georegion_l3_x4_y13) ) )).

%------------------------------------------------------------------------------
