%------------------------------------------------------------------------------
% File     : CSR061+1 : TPTP v6.1.0. Released v3.4.0.
% Domain   : Common Sense Reasoning
% Problem  : Autogenerated Cyc Problem CSR061+1
% Version  : Especial.
% English  :

% Refs     : [RS+]   Reagan Smith et al., The Cyc TPTP Challenge Problem
% Source   : [RS+]
% Names    :

% Status   : Theorem
% Rating   : 0.00 v5.5.0, 0.11 v5.3.0, 0.09 v5.2.0, 0.00 v4.1.0, 0.11 v4.0.1, 0.05 v3.7.0, 0.00 v3.4.0
% Syntax   : Number of formulae    :  119 (  23 unit)
%            Number of atoms       :  228 (   0 equality)
%            Maximal formula depth :    7 (   3 average)
%            Number of connectives :  111 (   2 ~  ;   0  |;  15  &)
%                                         (   0 <=>;  94 =>;   0 <=)
%                                         (   0 <~>;   0 ~|;   0 ~&)
%            Number of predicates  :   31 (   0 propositional; 1-2 arity)
%            Number of functors    :   24 (  24 constant; 0-0 arity)
%            Number of variables   :  141 (   0 singleton; 141 !;   0 ?)
%            Maximal term depth    :    1 (   1 average)
% SPC      : FOF_THM_EPR

% Comments : Autogenerated from the OpenCyc KB. Documentation can be found at
%            http://opencyc.org/doc/#TPTP_Challenge_Problem_Set
%          : Cyc(R) Knowledge Base Copyright(C) 1995-2007 Cycorp, Inc., Austin,
%            TX, USA. All rights reserved.
%          : OpenCyc Knowledge Base Copyright(C) 2001-2007 Cycorp, Inc.,
%            Austin, TX, USA. All rights reserved.
%------------------------------------------------------------------------------
%$problem_series(cyc_scaling_1,[CSR025+1,CSR026+1,CSR027+1,CSR028+1,CSR029+1,CSR030+1,CSR031+1,CSR032+1,CSR033+1,CSR034+1,CSR035+1,CSR036+1,CSR037+1,CSR038+1,CSR039+1,CSR040+1,CSR041+1,CSR042+1,CSR043+1,CSR044+1,CSR045+1,CSR046+1,CSR047+1,CSR048+1,CSR049+1,CSR050+1,CSR051+1,CSR052+1,CSR053+1,CSR054+1,CSR055+1,CSR056+1,CSR057+1,CSR058+1,CSR059+1,CSR060+1,CSR061+1,CSR062+1,CSR063+1,CSR064+1,CSR065+1,CSR066+1,CSR067+1,CSR068+1,CSR069+1,CSR070+1,CSR071+1,CSR072+1,CSR073+1,CSR074+1])
%$static(cyc_scaling_1,include('Axioms/CSR002+0.ax'))
%----Empty file include('Axioms/CSR002+0.ax').
%------------------------------------------------------------------------------
% Cyc Assertion #1322220:
fof(just1,axiom,(
    transitivebinarypredicate(c_genlmt) )).

% Cyc Assertion #1462275:
fof(just2,axiom,(
    genlmt(c_generictemporalmt,c_basekb) )).

% Cyc Assertion #1473451:
fof(just3,axiom,(
    genlmt(c_timehasnoendmt,c_generictemporalmt) )).

% Cyc Assertion #1650755:
fof(just4,axiom,(
    genlmt(c_basekb,c_universalvocabularymt) )).

% Cyc Assertion #2088991:
fof(just5,axiom,(
    genls(c_tptpcol_4_106497,c_tptpcol_3_98305) )).

fof(just6,axiom,(
    ! [OBJ] :
      ( tptpcol_4_106497(OBJ)
     => tptpcol_3_98305(OBJ) ) )).

% Cyc Assertion #2099230:
fof(just7,axiom,(
    genls(c_tptpcol_5_110593,c_tptpcol_4_106497) )).

fof(just8,axiom,(
    ! [OBJ] :
      ( tptpcol_5_110593(OBJ)
     => tptpcol_4_106497(OBJ) ) )).

% Cyc Assertion #2104349:
fof(just9,axiom,(
    genls(c_tptpcol_6_112641,c_tptpcol_5_110593) )).

fof(just10,axiom,(
    ! [OBJ] :
      ( tptpcol_6_112641(OBJ)
     => tptpcol_5_110593(OBJ) ) )).

% Cyc Assertion #2106908:
fof(just11,axiom,(
    genls(c_tptpcol_7_113665,c_tptpcol_6_112641) )).

fof(just12,axiom,(
    ! [OBJ] :
      ( tptpcol_7_113665(OBJ)
     => tptpcol_6_112641(OBJ) ) )).

% Cyc Assertion #2108187:
fof(just13,axiom,(
    genls(c_tptpcol_8_114177,c_tptpcol_7_113665) )).

fof(just14,axiom,(
    ! [OBJ] :
      ( tptpcol_8_114177(OBJ)
     => tptpcol_7_113665(OBJ) ) )).

% Cyc Assertion #2109471:
fof(just15,axiom,(
    genls(c_tptpcol_4_114689,c_tptpcol_3_114688) )).

fof(just16,axiom,(
    ! [OBJ] :
      ( tptpcol_4_114689(OBJ)
     => tptpcol_3_114688(OBJ) ) )).

% Cyc Assertion #2109473:
fof(just17,axiom,(
    genls(c_tptpcol_5_114690,c_tptpcol_4_114689) )).

fof(just18,axiom,(
    ! [OBJ] :
      ( tptpcol_5_114690(OBJ)
     => tptpcol_4_114689(OBJ) ) )).

% Cyc Assertion #2114592:
fof(just19,axiom,(
    genls(c_tptpcol_6_116738,c_tptpcol_5_114690) )).

fof(just20,axiom,(
    ! [OBJ] :
      ( tptpcol_6_116738(OBJ)
     => tptpcol_5_114690(OBJ) ) )).

% Cyc Assertion #2117151:
fof(just21,axiom,(
    genls(c_tptpcol_7_117762,c_tptpcol_6_116738) )).

fof(just22,axiom,(
    ! [OBJ] :
      ( tptpcol_7_117762(OBJ)
     => tptpcol_6_116738(OBJ) ) )).

% Cyc Assertion #2117153:
fof(just23,axiom,(
    genls(c_tptpcol_8_117763,c_tptpcol_7_117762) )).

fof(just24,axiom,(
    ! [OBJ] :
      ( tptpcol_8_117763(OBJ)
     => tptpcol_7_117762(OBJ) ) )).

% Cyc Assertion #2117792:
fof(just25,axiom,(
    genls(c_tptpcol_9_118019,c_tptpcol_8_117763) )).

fof(just26,axiom,(
    ! [OBJ] :
      ( tptpcol_9_118019(OBJ)
     => tptpcol_8_117763(OBJ) ) )).

% Cyc Assertion #2117794:
fof(just27,axiom,(
    genls(c_tptpcol_10_118020,c_tptpcol_9_118019) )).

fof(just28,axiom,(
    ! [OBJ] :
      ( tptpcol_10_118020(OBJ)
     => tptpcol_9_118019(OBJ) ) )).

% Cyc Assertion #2117953:
fof(just29,axiom,(
    genls(c_tptpcol_11_118084,c_tptpcol_10_118020) )).

fof(just30,axiom,(
    ! [OBJ] :
      ( tptpcol_11_118084(OBJ)
     => tptpcol_10_118020(OBJ) ) )).

% Cyc Assertion #2118032:
fof(just31,axiom,(
    genls(c_tptpcol_12_118116,c_tptpcol_11_118084) )).

fof(just32,axiom,(
    ! [OBJ] :
      ( tptpcol_12_118116(OBJ)
     => tptpcol_11_118084(OBJ) ) )).

% Cyc Assertion #2118034:
fof(just33,axiom,(
    genls(c_tptpcol_13_118117,c_tptpcol_12_118116) )).

fof(just34,axiom,(
    ! [OBJ] :
      ( tptpcol_13_118117(OBJ)
     => tptpcol_12_118116(OBJ) ) )).

% Cyc Assertion #2118036:
fof(just35,axiom,(
    genls(c_tptpcol_14_118118,c_tptpcol_13_118117) )).

fof(just36,axiom,(
    ! [OBJ] :
      ( tptpcol_14_118118(OBJ)
     => tptpcol_13_118117(OBJ) ) )).

% Cyc Assertion #2150425:
fof(just37,axiom,(
    disjointwith(c_tptpcol_3_98305,c_tptpcol_3_114688) )).

fof(just38,axiom,(
    ! [OBJ] :
      ~ ( tptpcol_3_98305(OBJ)
        & tptpcol_3_114688(OBJ) ) )).

% Cyc Assertion #398814:
fof(just39,axiom,(
    ! [OBJ,COL1,COL2] :
      ~ ( isa(OBJ,COL1)
        & isa(OBJ,COL2)
        & disjointwith(COL1,COL2) ) )).

% Cyc Assertion #831913:
fof(just40,axiom,(
    ! [SPECPRED,PRED,GENLPRED] :
      ( ( genlinverse(SPECPRED,PRED)
        & genlinverse(PRED,GENLPRED) )
     => genlpreds(SPECPRED,GENLPRED) ) )).

% Cyc Constant #40273:
fof(just41,axiom,(
    ! [ARG1,INS] :
      ( genlpreds(ARG1,INS)
     => predicate(INS) ) )).

fof(just42,axiom,(
    ! [ARG1,INS] :
      ( genlpreds(ARG1,INS)
     => predicate(INS) ) )).

fof(just43,axiom,(
    ! [INS,ARG2] :
      ( genlpreds(INS,ARG2)
     => predicate(INS) ) )).

fof(just44,axiom,(
    ! [INS,ARG2] :
      ( genlpreds(INS,ARG2)
     => predicate(INS) ) )).

fof(just45,axiom,(
    ! [X,Y,Z] :
      ( ( genlpreds(X,Y)
        & genlpreds(Y,Z) )
     => genlpreds(X,Z) ) )).

fof(just46,axiom,(
    ! [X] :
      ( predicate(X)
     => genlpreds(X,X) ) )).

fof(just47,axiom,(
    ! [X] :
      ( predicate(X)
     => genlpreds(X,X) ) )).

% Cyc Constant #45259:
fof(just48,axiom,(
    ! [ARG1,INS] :
      ( genlinverse(ARG1,INS)
     => binarypredicate(INS) ) )).

fof(just49,axiom,(
    ! [INS,ARG2] :
      ( genlinverse(INS,ARG2)
     => binarypredicate(INS) ) )).

fof(just50,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( genlinverse(OLD,ARG2)
        & genlpreds(NEW,OLD) )
     => genlinverse(NEW,ARG2) ) )).

fof(just51,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( genlinverse(ARG1,OLD)
        & genlpreds(OLD,NEW) )
     => genlinverse(ARG1,NEW) ) )).

% Cyc Constant #78648:
fof(just52,axiom,(
    ! [ARG1,INS] :
      ( disjointwith(ARG1,INS)
     => collection(INS) ) )).

fof(just53,axiom,(
    ! [INS,ARG2] :
      ( disjointwith(INS,ARG2)
     => collection(INS) ) )).

fof(just54,axiom,(
    ! [X,Y] :
      ( disjointwith(X,Y)
     => disjointwith(Y,X) ) )).

fof(just55,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( disjointwith(ARG1,OLD)
        & genls(NEW,OLD) )
     => disjointwith(ARG1,NEW) ) )).

fof(just56,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( disjointwith(OLD,ARG2)
        & genls(NEW,OLD) )
     => disjointwith(NEW,ARG2) ) )).

% Cyc Constant #247715:
fof(just57,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_14_118118)
     => tptpcol_14_118118(X) ) )).

fof(just58,axiom,(
    ! [X] :
      ( tptpcol_14_118118(X)
     => isa(X,c_tptpcol_14_118118) ) )).

% Cyc Constant #247714:
fof(just59,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_13_118117)
     => tptpcol_13_118117(X) ) )).

fof(just60,axiom,(
    ! [X] :
      ( tptpcol_13_118117(X)
     => isa(X,c_tptpcol_13_118117) ) )).

% Cyc Constant #247713:
fof(just61,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_12_118116)
     => tptpcol_12_118116(X) ) )).

fof(just62,axiom,(
    ! [X] :
      ( tptpcol_12_118116(X)
     => isa(X,c_tptpcol_12_118116) ) )).

% Cyc Constant #247681:
fof(just63,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_11_118084)
     => tptpcol_11_118084(X) ) )).

fof(just64,axiom,(
    ! [X] :
      ( tptpcol_11_118084(X)
     => isa(X,c_tptpcol_11_118084) ) )).

% Cyc Constant #247617:
fof(just65,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_10_118020)
     => tptpcol_10_118020(X) ) )).

fof(just66,axiom,(
    ! [X] :
      ( tptpcol_10_118020(X)
     => isa(X,c_tptpcol_10_118020) ) )).

% Cyc Constant #247616:
fof(just67,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_9_118019)
     => tptpcol_9_118019(X) ) )).

fof(just68,axiom,(
    ! [X] :
      ( tptpcol_9_118019(X)
     => isa(X,c_tptpcol_9_118019) ) )).

% Cyc Constant #247360:
fof(just69,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_8_117763)
     => tptpcol_8_117763(X) ) )).

fof(just70,axiom,(
    ! [X] :
      ( tptpcol_8_117763(X)
     => isa(X,c_tptpcol_8_117763) ) )).

% Cyc Constant #247359:
fof(just71,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_7_117762)
     => tptpcol_7_117762(X) ) )).

fof(just72,axiom,(
    ! [X] :
      ( tptpcol_7_117762(X)
     => isa(X,c_tptpcol_7_117762) ) )).

% Cyc Constant #246335:
fof(just73,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_6_116738)
     => tptpcol_6_116738(X) ) )).

fof(just74,axiom,(
    ! [X] :
      ( tptpcol_6_116738(X)
     => isa(X,c_tptpcol_6_116738) ) )).

% Cyc Constant #244287:
fof(just75,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_5_114690)
     => tptpcol_5_114690(X) ) )).

fof(just76,axiom,(
    ! [X] :
      ( tptpcol_5_114690(X)
     => isa(X,c_tptpcol_5_114690) ) )).

% Cyc Constant #244285:
fof(just77,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_3_114688)
     => tptpcol_3_114688(X) ) )).

fof(just78,axiom,(
    ! [X] :
      ( tptpcol_3_114688(X)
     => isa(X,c_tptpcol_3_114688) ) )).

% Cyc Constant #244286:
fof(just79,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_4_114689)
     => tptpcol_4_114689(X) ) )).

fof(just80,axiom,(
    ! [X] :
      ( tptpcol_4_114689(X)
     => isa(X,c_tptpcol_4_114689) ) )).

% Cyc Constant #243774:
fof(just81,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_8_114177)
     => tptpcol_8_114177(X) ) )).

fof(just82,axiom,(
    ! [X] :
      ( tptpcol_8_114177(X)
     => isa(X,c_tptpcol_8_114177) ) )).

% Cyc Constant #243262:
fof(just83,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_7_113665)
     => tptpcol_7_113665(X) ) )).

fof(just84,axiom,(
    ! [X] :
      ( tptpcol_7_113665(X)
     => isa(X,c_tptpcol_7_113665) ) )).

% Cyc Constant #242238:
fof(just85,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_6_112641)
     => tptpcol_6_112641(X) ) )).

fof(just86,axiom,(
    ! [X] :
      ( tptpcol_6_112641(X)
     => isa(X,c_tptpcol_6_112641) ) )).

% Cyc Constant #240190:
fof(just87,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_5_110593)
     => tptpcol_5_110593(X) ) )).

fof(just88,axiom,(
    ! [X] :
      ( tptpcol_5_110593(X)
     => isa(X,c_tptpcol_5_110593) ) )).

% Cyc Constant #227902:
fof(just89,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_3_98305)
     => tptpcol_3_98305(X) ) )).

fof(just90,axiom,(
    ! [X] :
      ( tptpcol_3_98305(X)
     => isa(X,c_tptpcol_3_98305) ) )).

% Cyc Constant #236094:
fof(just91,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_4_106497)
     => tptpcol_4_106497(X) ) )).

fof(just92,axiom,(
    ! [X] :
      ( tptpcol_4_106497(X)
     => isa(X,c_tptpcol_4_106497) ) )).

% Cyc Constant #0:
fof(just93,axiom,(
    ! [ARG1,INS] :
      ( genls(ARG1,INS)
     => collection(INS) ) )).

fof(just94,axiom,(
    ! [ARG1,INS] :
      ( genls(ARG1,INS)
     => collection(INS) ) )).

fof(just95,axiom,(
    ! [INS,ARG2] :
      ( genls(INS,ARG2)
     => collection(INS) ) )).

fof(just96,axiom,(
    ! [INS,ARG2] :
      ( genls(INS,ARG2)
     => collection(INS) ) )).

fof(just97,axiom,(
    ! [X,Y,Z] :
      ( ( genls(X,Y)
        & genls(Y,Z) )
     => genls(X,Z) ) )).

fof(just98,axiom,(
    ! [X] :
      ( collection(X)
     => genls(X,X) ) )).

fof(just99,axiom,(
    ! [X] :
      ( collection(X)
     => genls(X,X) ) )).

fof(just100,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( genls(OLD,ARG2)
        & genls(NEW,OLD) )
     => genls(NEW,ARG2) ) )).

fof(just101,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( genls(ARG1,OLD)
        & genls(OLD,NEW) )
     => genls(ARG1,NEW) ) )).

% Cyc Constant #27757:
fof(just102,axiom,(
    mtvisible(c_basekb) )).

% Cyc Constant #127156:
fof(just103,axiom,(
    ! [X] :
      ( isa(X,c_transitivebinarypredicate)
     => transitivebinarypredicate(X) ) )).

fof(just104,axiom,(
    ! [X] :
      ( transitivebinarypredicate(X)
     => isa(X,c_transitivebinarypredicate) ) )).

% Cyc Constant #19550:
fof(just105,axiom,(
    ! [SPECMT,GENLMT] :
      ( ( mtvisible(SPECMT)
        & genlmt(SPECMT,GENLMT) )
     => mtvisible(GENLMT) ) )).

fof(just106,axiom,(
    ! [ARG1,INS] :
      ( genlmt(ARG1,INS)
     => microtheory(INS) ) )).

fof(just107,axiom,(
    ! [ARG1,INS] :
      ( genlmt(ARG1,INS)
     => microtheory(INS) ) )).

fof(just108,axiom,(
    ! [INS,ARG2] :
      ( genlmt(INS,ARG2)
     => microtheory(INS) ) )).

fof(just109,axiom,(
    ! [INS,ARG2] :
      ( genlmt(INS,ARG2)
     => microtheory(INS) ) )).

fof(just110,axiom,(
    ! [X,Y,Z] :
      ( ( genlmt(X,Y)
        & genlmt(Y,Z) )
     => genlmt(X,Z) ) )).

fof(just111,axiom,(
    ! [X] :
      ( microtheory(X)
     => genlmt(X,X) ) )).

fof(just112,axiom,(
    ! [X] :
      ( microtheory(X)
     => genlmt(X,X) ) )).

% Cyc Constant #72115:
fof(just113,axiom,(
    ! [ARG1,INS] :
      ( isa(ARG1,INS)
     => collection(INS) ) )).

fof(just114,axiom,(
    ! [ARG1,INS] :
      ( isa(ARG1,INS)
     => collection(INS) ) )).

fof(just115,axiom,(
    ! [INS,ARG2] :
      ( isa(INS,ARG2)
     => thing(INS) ) )).

fof(just116,axiom,(
    ! [INS,ARG2] :
      ( isa(INS,ARG2)
     => thing(INS) ) )).

fof(just117,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( isa(ARG1,OLD)
        & genls(OLD,NEW) )
     => isa(ARG1,NEW) ) )).

% Cyc Constant #95028:
fof(just118,axiom,(
    mtvisible(c_universalvocabularymt) )).

fof(query61,conjecture,
    ( mtvisible(c_timehasnoendmt)
   => disjointwith(c_tptpcol_8_114177,c_tptpcol_14_118118) )).

%------------------------------------------------------------------------------
