%------------------------------------------------------------------------------
% File     : CSR064+1 : TPTP v6.1.0. Released v3.4.0.
% Domain   : Common Sense Reasoning
% Problem  : Autogenerated Cyc Problem CSR064+1
% Version  : Especial.
% English  :

% Refs     : [RS+]   Reagan Smith et al., The Cyc TPTP Challenge Problem
% Source   : [RS+]
% Names    :

% Status   : Theorem
% Rating   : 0.00 v6.1.0, 0.04 v6.0.0, 0.25 v5.5.0, 0.12 v5.4.0, 0.13 v5.3.0, 0.22 v5.2.0, 0.07 v5.0.0, 0.10 v4.1.0, 0.06 v4.0.1, 0.00 v3.4.0
% Syntax   : Number of formulae    :   77 (  12 unit)
%            Number of atoms       :  165 (   0 equality)
%            Maximal formula depth :    7 (   4 average)
%            Number of connectives :   93 (   5 ~  ;   0  |;  27  &)
%                                         (   0 <=>;  61 =>;   0 <=)
%                                         (   0 <~>;   0 ~|;   0 ~&)
%            Number of predicates  :   20 (   0 propositional; 1-3 arity)
%            Number of functors    :   14 (  13 constant; 0-1 arity)
%            Number of variables   :  142 (   0 singleton; 142 !;   0 ?)
%            Maximal term depth    :    3 (   1 average)
% SPC      : FOF_THM_RFO_NEQ

% Comments : Autogenerated from the OpenCyc KB. Documentation can be found at
%            http://opencyc.org/doc/#TPTP_Challenge_Problem_Set
%          : Cyc(R) Knowledge Base Copyright(C) 1995-2007 Cycorp, Inc., Austin,
%            TX, USA. All rights reserved.
%          : OpenCyc Knowledge Base Copyright(C) 2001-2007 Cycorp, Inc.,
%            Austin, TX, USA. All rights reserved.
%------------------------------------------------------------------------------
%$problem_series(cyc_scaling_1,[CSR025+1,CSR026+1,CSR027+1,CSR028+1,CSR029+1,CSR030+1,CSR031+1,CSR032+1,CSR033+1,CSR034+1,CSR035+1,CSR036+1,CSR037+1,CSR038+1,CSR039+1,CSR040+1,CSR041+1,CSR042+1,CSR043+1,CSR044+1,CSR045+1,CSR046+1,CSR047+1,CSR048+1,CSR049+1,CSR050+1,CSR051+1,CSR052+1,CSR053+1,CSR054+1,CSR055+1,CSR056+1,CSR057+1,CSR058+1,CSR059+1,CSR060+1,CSR061+1,CSR062+1,CSR063+1,CSR064+1,CSR065+1,CSR066+1,CSR067+1,CSR068+1,CSR069+1,CSR070+1,CSR071+1,CSR072+1,CSR073+1,CSR074+1])
%$static(cyc_scaling_1,include('Axioms/CSR002+0.ax'))
%----Empty file include('Axioms/CSR002+0.ax').
%------------------------------------------------------------------------------
% Cyc Assertion #1419921:
fof(just1,axiom,(
    disjointwith(c_individual,c_setorcollection) )).

fof(just2,axiom,(
    ! [OBJ] :
      ~ ( individual(OBJ)
        & setorcollection(OBJ) ) )).

% Cyc Assertion #1668072:
fof(just3,axiom,(
    individual(f_urlfn(f_urlfn(s_http_wwwahwatukeecomafnentertainmentarticles030423ahtml))) )).

% Cyc Assertion #398814:
fof(just4,axiom,(
    ! [OBJ,COL1,COL2] :
      ~ ( isa(OBJ,COL1)
        & isa(OBJ,COL2)
        & disjointwith(COL1,COL2) ) )).

% Cyc Assertion #831913:
fof(just5,axiom,(
    ! [SPECPRED,PRED,GENLPRED] :
      ( ( genlinverse(SPECPRED,PRED)
        & genlinverse(PRED,GENLPRED) )
     => genlpreds(SPECPRED,GENLPRED) ) )).

% Cyc Assertion #606520:
fof(just6,axiom,(
    genlpreds(c_subsetof,c_most) )).

fof(just7,axiom,(
    ! [ARG1,ARG2] :
      ( subsetof(ARG1,ARG2)
     => most(ARG1,ARG2) ) )).

% Cyc Assertion #849068:
fof(just8,axiom,(
    transitivebinarypredicate(c_genlpreds) )).

% Cyc Assertion #1738068:
fof(just9,axiom,(
    genlpreds(c_genls,c_subsetof) )).

fof(just10,axiom,(
    ! [ARG1,ARG2] :
      ( genls(ARG1,ARG2)
     => subsetof(ARG1,ARG2) ) )).

% Cyc Assertion #398814:
fof(just11,axiom,(
    ! [OBJ,COL1,COL2] :
      ~ ( isa(OBJ,COL1)
        & isa(OBJ,COL2)
        & disjointwith(COL1,COL2) ) )).

% Cyc Assertion #831913:
fof(just12,axiom,(
    ! [SPECPRED,PRED,GENLPRED] :
      ( ( genlinverse(SPECPRED,PRED)
        & genlinverse(PRED,GENLPRED) )
     => genlpreds(SPECPRED,GENLPRED) ) )).

% Cyc Assertion #1243931:
fof(just13,axiom,(
    arg1isa(c_most,c_setorcollection) )).

fof(just14,axiom,(
    ! [ARG1,ARG2] :
      ( most(ARG1,ARG2)
     => setorcollection(ARG1) ) )).

% Cyc Assertion #398814:
fof(just15,axiom,(
    ! [OBJ,COL1,COL2] :
      ~ ( isa(OBJ,COL1)
        & isa(OBJ,COL2)
        & disjointwith(COL1,COL2) ) )).

% Cyc Assertion #831913:
fof(just16,axiom,(
    ! [SPECPRED,PRED,GENLPRED] :
      ( ( genlinverse(SPECPRED,PRED)
        & genlinverse(PRED,GENLPRED) )
     => genlpreds(SPECPRED,GENLPRED) ) )).

% Cyc Constant #54485:
fof(just17,axiom,(
    ! [ARG1,INS] :
      ( arg1isa(ARG1,INS)
     => collection(INS) ) )).

fof(just18,axiom,(
    ! [INS,ARG2] :
      ( arg1isa(INS,ARG2)
     => relation(INS) ) )).

fof(just19,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( arg1isa(ARG1,OLD)
        & genls(OLD,NEW) )
     => arg1isa(ARG1,NEW) ) )).

fof(just20,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( arg1isa(ARG1,OLD)
        & genls(OLD,NEW) )
     => arg1isa(ARG1,NEW) ) )).

% Cyc Constant #0:
fof(just21,axiom,(
    ! [ARG1,INS] :
      ( genls(ARG1,INS)
     => collection(INS) ) )).

fof(just22,axiom,(
    ! [ARG1,INS] :
      ( genls(ARG1,INS)
     => collection(INS) ) )).

fof(just23,axiom,(
    ! [INS,ARG2] :
      ( genls(INS,ARG2)
     => collection(INS) ) )).

fof(just24,axiom,(
    ! [INS,ARG2] :
      ( genls(INS,ARG2)
     => collection(INS) ) )).

fof(just25,axiom,(
    ! [X,Y,Z] :
      ( ( genls(X,Y)
        & genls(Y,Z) )
     => genls(X,Z) ) )).

fof(just26,axiom,(
    ! [X] :
      ( collection(X)
     => genls(X,X) ) )).

fof(just27,axiom,(
    ! [X] :
      ( collection(X)
     => genls(X,X) ) )).

fof(just28,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( genls(OLD,ARG2)
        & genls(NEW,OLD) )
     => genls(NEW,ARG2) ) )).

fof(just29,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( genls(ARG1,OLD)
        & genls(OLD,NEW) )
     => genls(ARG1,NEW) ) )).

% Cyc Constant #127156:
fof(just30,axiom,(
    ! [X] :
      ( isa(X,c_transitivebinarypredicate)
     => transitivebinarypredicate(X) ) )).

fof(just31,axiom,(
    ! [X] :
      ( transitivebinarypredicate(X)
     => isa(X,c_transitivebinarypredicate) ) )).

% Cyc Constant #10889:
fof(just32,axiom,(
    ! [ARG1,INS] :
      ( most(ARG1,INS)
     => setorcollection(INS) ) )).

fof(just33,axiom,(
    ! [ARG1,INS] :
      ( most(ARG1,INS)
     => setorcollection(INS) ) )).

fof(just34,axiom,(
    ! [INS,ARG2] :
      ( most(INS,ARG2)
     => setorcollection(INS) ) )).

fof(just35,axiom,(
    ! [INS,ARG2] :
      ( most(INS,ARG2)
     => setorcollection(INS) ) )).

fof(just36,axiom,(
    ! [X] :
      ( setorcollection(X)
     => most(X,X) ) )).

fof(just37,axiom,(
    ! [X] :
      ( setorcollection(X)
     => most(X,X) ) )).

fof(just38,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( most(ARG1,OLD)
        & subsetof(OLD,NEW) )
     => most(ARG1,NEW) ) )).

fof(just39,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( most(ARG1,OLD)
        & subsetof(OLD,NEW) )
     => most(ARG1,NEW) ) )).

% Cyc Constant #115179:
fof(just40,axiom,(
    ! [ARG1,INS] :
      ( subsetof(ARG1,INS)
     => setorcollection(INS) ) )).

fof(just41,axiom,(
    ! [INS,ARG2] :
      ( subsetof(INS,ARG2)
     => setorcollection(INS) ) )).

fof(just42,axiom,(
    ! [X,Y,Z] :
      ( ( subsetof(X,Y)
        & subsetof(Y,Z) )
     => subsetof(X,Z) ) )).

fof(just43,axiom,(
    ! [X] :
      ( setorcollection(X)
     => subsetof(X,X) ) )).

fof(just44,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( subsetof(OLD,ARG2)
        & subsetof(NEW,OLD) )
     => subsetof(NEW,ARG2) ) )).

fof(just45,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( subsetof(ARG1,OLD)
        & subsetof(OLD,NEW) )
     => subsetof(ARG1,NEW) ) )).

fof(just46,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( subsetof(ARG1,OLD)
        & subsetof(OLD,NEW) )
     => subsetof(ARG1,NEW) ) )).

% Cyc Constant #40273:
fof(just47,axiom,(
    ! [ARG1,INS] :
      ( genlpreds(ARG1,INS)
     => predicate(INS) ) )).

fof(just48,axiom,(
    ! [ARG1,INS] :
      ( genlpreds(ARG1,INS)
     => predicate(INS) ) )).

fof(just49,axiom,(
    ! [INS,ARG2] :
      ( genlpreds(INS,ARG2)
     => predicate(INS) ) )).

fof(just50,axiom,(
    ! [INS,ARG2] :
      ( genlpreds(INS,ARG2)
     => predicate(INS) ) )).

fof(just51,axiom,(
    ! [X,Y,Z] :
      ( ( genlpreds(X,Y)
        & genlpreds(Y,Z) )
     => genlpreds(X,Z) ) )).

fof(just52,axiom,(
    ! [X] :
      ( predicate(X)
     => genlpreds(X,X) ) )).

fof(just53,axiom,(
    ! [X] :
      ( predicate(X)
     => genlpreds(X,X) ) )).

% Cyc Constant #45259:
fof(just54,axiom,(
    ! [ARG1,INS] :
      ( genlinverse(ARG1,INS)
     => binarypredicate(INS) ) )).

fof(just55,axiom,(
    ! [INS,ARG2] :
      ( genlinverse(INS,ARG2)
     => binarypredicate(INS) ) )).

fof(just56,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( genlinverse(OLD,ARG2)
        & genlpreds(NEW,OLD) )
     => genlinverse(NEW,ARG2) ) )).

fof(just57,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( genlinverse(ARG1,OLD)
        & genlpreds(OLD,NEW) )
     => genlinverse(ARG1,NEW) ) )).

% Cyc Constant #27757:
fof(just58,axiom,(
    mtvisible(c_basekb) )).

% Cyc Constant #129091:
fof(just59,axiom,(
    ! [ARG1] : natfunction(f_urlfn(ARG1),c_urlfn) )).

fof(just60,axiom,(
    ! [ARG1] : natargument(f_urlfn(ARG1),n_1,ARG1) )).

fof(just61,axiom,(
    ! [ARG1] : uniformresourcelocator(f_urlfn(ARG1)) )).

% Cyc Constant #72115:
fof(just62,axiom,(
    ! [ARG1,INS] :
      ( isa(ARG1,INS)
     => collection(INS) ) )).

fof(just63,axiom,(
    ! [ARG1,INS] :
      ( isa(ARG1,INS)
     => collection(INS) ) )).

fof(just64,axiom,(
    ! [INS,ARG2] :
      ( isa(INS,ARG2)
     => thing(INS) ) )).

fof(just65,axiom,(
    ! [INS,ARG2] :
      ( isa(INS,ARG2)
     => thing(INS) ) )).

fof(just66,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( isa(ARG1,OLD)
        & genls(OLD,NEW) )
     => isa(ARG1,NEW) ) )).

% Cyc Constant #29216:
fof(just67,axiom,(
    ! [X] :
      ( isa(X,c_setorcollection)
     => setorcollection(X) ) )).

fof(just68,axiom,(
    ! [X] :
      ( setorcollection(X)
     => isa(X,c_setorcollection) ) )).

% Cyc Constant #113597:
fof(just69,axiom,(
    ! [X] :
      ( isa(X,c_individual)
     => individual(X) ) )).

fof(just70,axiom,(
    ! [X] :
      ( individual(X)
     => isa(X,c_individual) ) )).

% Cyc Constant #78648:
fof(just71,axiom,(
    ! [ARG1,INS] :
      ( disjointwith(ARG1,INS)
     => collection(INS) ) )).

fof(just72,axiom,(
    ! [INS,ARG2] :
      ( disjointwith(INS,ARG2)
     => collection(INS) ) )).

fof(just73,axiom,(
    ! [X,Y] :
      ( disjointwith(X,Y)
     => disjointwith(Y,X) ) )).

fof(just74,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( disjointwith(ARG1,OLD)
        & genls(NEW,OLD) )
     => disjointwith(ARG1,NEW) ) )).

fof(just75,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( disjointwith(OLD,ARG2)
        & genls(NEW,OLD) )
     => disjointwith(NEW,ARG2) ) )).

% Cyc Constant #95028:
fof(just76,axiom,(
    mtvisible(c_universalvocabularymt) )).

fof(query64,conjecture,(
    ~ genls(f_urlfn(f_urlfn(s_http_wwwahwatukeecomafnentertainmentarticles030423ahtml)),c_tptpcol_15_74743) )).

%------------------------------------------------------------------------------
