%------------------------------------------------------------------------------
% File     : CSR034+3 : TPTP v6.1.0. Released v3.4.0.
% Domain   : Common Sense Reasoning
% Problem  : Autogenerated Cyc Problem CSR034+3
% Version  : Especial.
% English  :

% Refs     : [RS+]   Reagan Smith et al., The Cyc TPTP Challenge Problem
% Source   : [RS+]
% Names    :

% Status   : Theorem
% Rating   : 0.27 v6.1.0, 0.24 v6.0.0, 0.25 v5.5.0, 0.33 v5.4.0, 0.30 v5.3.0, 0.39 v5.2.0, 0.36 v5.0.0, 0.30 v4.1.0, 0.39 v4.0.1, 0.42 v4.0.0, 0.45 v3.7.0, 0.00 v3.4.0
% Syntax   : Number of formulae    : 8006 (3281 unit)
%            Number of atoms       : 13036 (   0 equality)
%            Maximal formula depth :    7 (   2 average)
%            Number of connectives : 5104 (  74 ~  ;   0  |; 347  &)
%                                         (   0 <=>;4683 =>;   0 <=)
%                                         (   0 <~>;   0 ~|;   0 ~&)
%            Number of predicates  : 1520 (   0 propositional; 1-5 arity)
%            Number of functors    : 3266 (3136 constant; 0-4 arity)
%            Number of variables   : 5971 (   0 singleton;5970 !;   1 ?)
%            Maximal term depth    :    6 (   1 average)
% SPC      : FOF_THM_RFO_NEQ

% Comments : Autogenerated from the OpenCyc KB. Documentation can be found at
%            http://opencyc.org/doc/#TPTP_Challenge_Problem_Set
%          : Cyc(R) Knowledge Base Copyright(C) 1995-2007 Cycorp, Inc., Austin,
%            TX, USA. All rights reserved.
%          : OpenCyc Knowledge Base Copyright(C) 2001-2007 Cycorp, Inc.,
%            Austin, TX, USA. All rights reserved.
%------------------------------------------------------------------------------
%$problem_series(cyc_scaling_3,[CSR025+3,CSR026+3,CSR027+3,CSR028+3,CSR029+3,CSR030+3,CSR031+3,CSR032+3,CSR033+3,CSR034+3,CSR035+3,CSR036+3,CSR037+3,CSR038+3,CSR039+3,CSR040+3,CSR041+3,CSR042+3,CSR043+3,CSR044+3,CSR045+3,CSR046+3,CSR047+3,CSR048+3,CSR049+3,CSR050+3,CSR051+3,CSR052+3,CSR053+3,CSR054+3,CSR055+3,CSR056+3,CSR057+3,CSR058+3,CSR059+3,CSR060+3,CSR061+3,CSR062+3,CSR063+3,CSR064+3,CSR065+3,CSR066+3,CSR067+3,CSR068+3,CSR069+3,CSR070+3,CSR071+3,CSR072+3,CSR073+3,CSR074+3])
%$static(cyc_scaling_3,include('Axioms/CSR002+2.ax'))
include('Axioms/CSR002+2.ax').
%------------------------------------------------------------------------------
fof(query134,conjecture,(
    ? [COL] :
      ( mtvisible(c_tptp_member3515_mt)
     => isa(c_wanica_districtsuriname,COL) ) )).

%------------------------------------------------------------------------------
