%------------------------------------------------------------------------------
% File     : CSR071+1 : TPTP v6.1.0. Released v3.4.0.
% Domain   : Common Sense Reasoning
% Problem  : Autogenerated Cyc Problem CSR071+1
% Version  : Especial.
% English  :

% Refs     : [RS+]   Reagan Smith et al., The Cyc TPTP Challenge Problem
% Source   : [RS+]
% Names    :

% Status   : Theorem
% Rating   : 0.00 v6.1.0, 0.04 v6.0.0, 0.25 v5.5.0, 0.08 v5.4.0, 0.13 v5.3.0, 0.22 v5.2.0, 0.07 v5.0.0, 0.15 v4.1.0, 0.11 v4.0.1, 0.05 v3.7.0, 0.00 v3.4.0
% Syntax   : Number of formulae    :   72 (  16 unit)
%            Number of atoms       :  142 (   0 equality)
%            Maximal formula depth :    7 (   4 average)
%            Number of connectives :   71 (   1 ~  ;   0  |;  15  &)
%                                         (   0 <=>;  55 =>;   0 <=)
%                                         (   0 <~>;   0 ~|;   0 ~&)
%            Number of predicates  :   21 (   0 propositional; 1-3 arity)
%            Number of functors    :   20 (  19 constant; 0-1 arity)
%            Number of variables   :  110 (   0 singleton; 110 !;   0 ?)
%            Maximal term depth    :    2 (   1 average)
% SPC      : FOF_THM_RFO_NEQ

% Comments : Autogenerated from the OpenCyc KB. Documentation can be found at
%            http://opencyc.org/doc/#TPTP_Challenge_Problem_Set
%          : Cyc(R) Knowledge Base Copyright(C) 1995-2007 Cycorp, Inc., Austin,
%            TX, USA. All rights reserved.
%          : OpenCyc Knowledge Base Copyright(C) 2001-2007 Cycorp, Inc.,
%            Austin, TX, USA. All rights reserved.
%------------------------------------------------------------------------------
%$problem_series(cyc_scaling_1,[CSR025+1,CSR026+1,CSR027+1,CSR028+1,CSR029+1,CSR030+1,CSR031+1,CSR032+1,CSR033+1,CSR034+1,CSR035+1,CSR036+1,CSR037+1,CSR038+1,CSR039+1,CSR040+1,CSR041+1,CSR042+1,CSR043+1,CSR044+1,CSR045+1,CSR046+1,CSR047+1,CSR048+1,CSR049+1,CSR050+1,CSR051+1,CSR052+1,CSR053+1,CSR054+1,CSR055+1,CSR056+1,CSR057+1,CSR058+1,CSR059+1,CSR060+1,CSR061+1,CSR062+1,CSR063+1,CSR064+1,CSR065+1,CSR066+1,CSR067+1,CSR068+1,CSR069+1,CSR070+1,CSR071+1,CSR072+1,CSR073+1,CSR074+1])
%$static(cyc_scaling_1,include('Axioms/CSR002+0.ax'))
%----Empty file include('Axioms/CSR002+0.ax').
%------------------------------------------------------------------------------
% Cyc Assertion #665347:
fof(just1,axiom,(
    genls(c_navypersonnel,c_militaryperson) )).

fof(just2,axiom,(
    ! [OBJ] :
      ( navypersonnel(OBJ)
     => militaryperson(OBJ) ) )).

% Cyc Assertion #1077444:
fof(just3,axiom,(
    genlmt(c_calendarsmt,c_calendarsvocabularymt) )).

% Cyc Assertion #1322220:
fof(just4,axiom,(
    transitivebinarypredicate(c_genlmt) )).

% Cyc Assertion #1650755:
fof(just5,axiom,(
    genlmt(c_basekb,c_universalvocabularymt) )).

% Cyc Assertion #1706514:
fof(just6,axiom,(
    genlmt(c_cyclistsmt,c_calendarsmt) )).

% Cyc Assertion #1746783:
fof(just7,axiom,(
    genlmt(c_calendarsvocabularymt,c_basekb) )).

% Cyc Assertion #2170932:
fof(just8,axiom,(
    genlmt(c_tptp_spindleheadmt,c_cyclistsmt) )).

% Cyc Assertion #2173728:
fof(just9,axiom,(
    genlmt(c_tptp_spindlecollectormt,c_tptp_member698_mt) )).

% Cyc Assertion #2177624:
fof(just10,axiom,(
    genlmt(c_tptp_spindlecollectormt,c_tptp_member1672_mt) )).

% Cyc Assertion #2186907:
fof(just11,axiom,(
    genlmt(c_tptp_member3993_mt,c_tptp_spindleheadmt) )).

% Cyc Assertion #2186908:
fof(just12,axiom,(
    genlmt(c_tptp_spindlecollectormt,c_tptp_member3993_mt) )).

% Cyc Assertion #2362336:
fof(just13,axiom,(
    ! [INS] :
      ( ( mtvisible(c_tptp_member698_mt)
        & militaryperson(INS) )
     => tptpofobject(INS,f_tptpquantityfn_6(n_414)) ) )).

fof(just14,axiom,
    ( mtvisible(c_tptp_member698_mt)
   => relationallinstance(c_tptpofobject,c_militaryperson,f_tptpquantityfn_6(n_414)) )).

% Cyc Assertion #2418340:
fof(just15,axiom,
    ( mtvisible(c_tptp_member1672_mt)
   => navypersonnel(c_tptpnavypersonnel_3) )).

% Cyc Assertion #398814:
fof(just16,axiom,(
    ! [OBJ,COL1,COL2] :
      ~ ( isa(OBJ,COL1)
        & isa(OBJ,COL2)
        & disjointwith(COL1,COL2) ) )).

% Cyc Assertion #831913:
fof(just17,axiom,(
    ! [SPECPRED,PRED,GENLPRED] :
      ( ( genlinverse(SPECPRED,PRED)
        & genlinverse(PRED,GENLPRED) )
     => genlpreds(SPECPRED,GENLPRED) ) )).

% Cyc Constant #40273:
fof(just18,axiom,(
    ! [ARG1,INS] :
      ( genlpreds(ARG1,INS)
     => predicate(INS) ) )).

fof(just19,axiom,(
    ! [ARG1,INS] :
      ( genlpreds(ARG1,INS)
     => predicate(INS) ) )).

fof(just20,axiom,(
    ! [INS,ARG2] :
      ( genlpreds(INS,ARG2)
     => predicate(INS) ) )).

fof(just21,axiom,(
    ! [INS,ARG2] :
      ( genlpreds(INS,ARG2)
     => predicate(INS) ) )).

fof(just22,axiom,(
    ! [X,Y,Z] :
      ( ( genlpreds(X,Y)
        & genlpreds(Y,Z) )
     => genlpreds(X,Z) ) )).

fof(just23,axiom,(
    ! [X] :
      ( predicate(X)
     => genlpreds(X,X) ) )).

fof(just24,axiom,(
    ! [X] :
      ( predicate(X)
     => genlpreds(X,X) ) )).

% Cyc Constant #45259:
fof(just25,axiom,(
    ! [ARG1,INS] :
      ( genlinverse(ARG1,INS)
     => binarypredicate(INS) ) )).

fof(just26,axiom,(
    ! [INS,ARG2] :
      ( genlinverse(INS,ARG2)
     => binarypredicate(INS) ) )).

fof(just27,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( genlinverse(OLD,ARG2)
        & genlpreds(NEW,OLD) )
     => genlinverse(NEW,ARG2) ) )).

fof(just28,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( genlinverse(ARG1,OLD)
        & genlpreds(OLD,NEW) )
     => genlinverse(ARG1,NEW) ) )).

% Cyc Constant #78648:
fof(just29,axiom,(
    ! [ARG1,INS] :
      ( disjointwith(ARG1,INS)
     => collection(INS) ) )).

fof(just30,axiom,(
    ! [INS,ARG2] :
      ( disjointwith(INS,ARG2)
     => collection(INS) ) )).

fof(just31,axiom,(
    ! [X,Y] :
      ( disjointwith(X,Y)
     => disjointwith(Y,X) ) )).

fof(just32,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( disjointwith(ARG1,OLD)
        & genls(NEW,OLD) )
     => disjointwith(ARG1,NEW) ) )).

fof(just33,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( disjointwith(OLD,ARG2)
        & genls(NEW,OLD) )
     => disjointwith(NEW,ARG2) ) )).

% Cyc Constant #347762:
fof(just34,axiom,(
    ! [ARG1] : natfunction(f_tptpquantityfn_6(ARG1),c_tptpquantityfn_6) )).

fof(just35,axiom,(
    ! [ARG1] : natargument(f_tptpquantityfn_6(ARG1),n_1,ARG1) )).

fof(just36,axiom,(
    ! [ARG1] : tptpquantity(f_tptpquantityfn_6(ARG1)) )).

% Cyc Constant #347754:
fof(just37,axiom,(
    ! [ARG1,INS] :
      ( tptpofobject(ARG1,INS)
     => tptpquantity(INS) ) )).

fof(just38,axiom,(
    ! [INS,ARG2] :
      ( tptpofobject(INS,ARG2)
     => partiallytangible(INS) ) )).

% Cyc Constant #3338:
fof(just39,axiom,(
    ! [ARG1,ARG2,INS] :
      ( relationallinstance(ARG1,ARG2,INS)
     => thing(INS) ) )).

fof(just40,axiom,(
    ! [ARG1,INS,ARG3] :
      ( relationallinstance(ARG1,INS,ARG3)
     => collection(INS) ) )).

fof(just41,axiom,(
    ! [INS,ARG2,ARG3] :
      ( relationallinstance(INS,ARG2,ARG3)
     => binarypredicate(INS) ) )).

% Cyc Constant #27757:
fof(just42,axiom,(
    mtvisible(c_basekb) )).

% Cyc Constant #127156:
fof(just43,axiom,(
    ! [X] :
      ( isa(X,c_transitivebinarypredicate)
     => transitivebinarypredicate(X) ) )).

fof(just44,axiom,(
    ! [X] :
      ( transitivebinarypredicate(X)
     => isa(X,c_transitivebinarypredicate) ) )).

% Cyc Constant #72115:
fof(just45,axiom,(
    ! [ARG1,INS] :
      ( isa(ARG1,INS)
     => collection(INS) ) )).

fof(just46,axiom,(
    ! [ARG1,INS] :
      ( isa(ARG1,INS)
     => collection(INS) ) )).

fof(just47,axiom,(
    ! [INS,ARG2] :
      ( isa(INS,ARG2)
     => thing(INS) ) )).

fof(just48,axiom,(
    ! [INS,ARG2] :
      ( isa(INS,ARG2)
     => thing(INS) ) )).

fof(just49,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( isa(ARG1,OLD)
        & genls(OLD,NEW) )
     => isa(ARG1,NEW) ) )).

% Cyc Constant #19550:
fof(just50,axiom,(
    ! [SPECMT,GENLMT] :
      ( ( mtvisible(SPECMT)
        & genlmt(SPECMT,GENLMT) )
     => mtvisible(GENLMT) ) )).

fof(just51,axiom,(
    ! [ARG1,INS] :
      ( genlmt(ARG1,INS)
     => microtheory(INS) ) )).

fof(just52,axiom,(
    ! [ARG1,INS] :
      ( genlmt(ARG1,INS)
     => microtheory(INS) ) )).

fof(just53,axiom,(
    ! [INS,ARG2] :
      ( genlmt(INS,ARG2)
     => microtheory(INS) ) )).

fof(just54,axiom,(
    ! [INS,ARG2] :
      ( genlmt(INS,ARG2)
     => microtheory(INS) ) )).

fof(just55,axiom,(
    ! [X,Y,Z] :
      ( ( genlmt(X,Y)
        & genlmt(Y,Z) )
     => genlmt(X,Z) ) )).

fof(just56,axiom,(
    ! [X] :
      ( microtheory(X)
     => genlmt(X,X) ) )).

fof(just57,axiom,(
    ! [X] :
      ( microtheory(X)
     => genlmt(X,X) ) )).

% Cyc Constant #29025:
fof(just58,axiom,(
    ! [X] :
      ( isa(X,c_militaryperson)
     => militaryperson(X) ) )).

fof(just59,axiom,(
    ! [X] :
      ( militaryperson(X)
     => isa(X,c_militaryperson) ) )).

% Cyc Constant #96482:
fof(just60,axiom,(
    ! [X] :
      ( isa(X,c_navypersonnel)
     => navypersonnel(X) ) )).

fof(just61,axiom,(
    ! [X] :
      ( navypersonnel(X)
     => isa(X,c_navypersonnel) ) )).

% Cyc Constant #0:
fof(just62,axiom,(
    ! [ARG1,INS] :
      ( genls(ARG1,INS)
     => collection(INS) ) )).

fof(just63,axiom,(
    ! [ARG1,INS] :
      ( genls(ARG1,INS)
     => collection(INS) ) )).

fof(just64,axiom,(
    ! [INS,ARG2] :
      ( genls(INS,ARG2)
     => collection(INS) ) )).

fof(just65,axiom,(
    ! [INS,ARG2] :
      ( genls(INS,ARG2)
     => collection(INS) ) )).

fof(just66,axiom,(
    ! [X,Y,Z] :
      ( ( genls(X,Y)
        & genls(Y,Z) )
     => genls(X,Z) ) )).

fof(just67,axiom,(
    ! [X] :
      ( collection(X)
     => genls(X,X) ) )).

fof(just68,axiom,(
    ! [X] :
      ( collection(X)
     => genls(X,X) ) )).

fof(just69,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( genls(OLD,ARG2)
        & genls(NEW,OLD) )
     => genls(NEW,ARG2) ) )).

fof(just70,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( genls(ARG1,OLD)
        & genls(OLD,NEW) )
     => genls(ARG1,NEW) ) )).

% Cyc Constant #95028:
fof(just71,axiom,(
    mtvisible(c_universalvocabularymt) )).

fof(query71,conjecture,
    ( mtvisible(c_tptp_spindlecollectormt)
   => tptpofobject(c_tptpnavypersonnel_3,f_tptpquantityfn_6(n_414)) )).

%------------------------------------------------------------------------------
