%------------------------------------------------------------------------------
% File     : CSR057+1 : TPTP v6.1.0. Released v3.4.0.
% Domain   : Common Sense Reasoning
% Problem  : Autogenerated Cyc Problem CSR057+1
% Version  : Especial.
% English  :

% Refs     : [RS+]   Reagan Smith et al., The Cyc TPTP Challenge Problem
% Source   : [RS+]
% Names    :

% Status   : Theorem
% Rating   : 0.00 v5.5.0, 0.11 v5.3.0, 0.09 v5.2.0, 0.00 v4.1.0, 0.06 v4.0.1, 0.00 v3.4.0
% Syntax   : Number of formulae    :  102 (  29 unit)
%            Number of atoms       :  193 (   0 equality)
%            Maximal formula depth :    7 (   3 average)
%            Number of connectives :   94 (   3 ~  ;   0  |;  21  &)
%                                         (   0 <=>;  70 =>;   0 <=)
%                                         (   0 <~>;   0 ~|;   0 ~&)
%            Number of predicates  :   20 (   0 propositional; 1-2 arity)
%            Number of functors    :   16 (  16 constant; 0-0 arity)
%            Number of variables   :  129 (   0 singleton; 128 !;   1 ?)
%            Maximal term depth    :    1 (   1 average)
% SPC      : FOF_THM_EPR

% Comments : Autogenerated from the OpenCyc KB. Documentation can be found at
%            http://opencyc.org/doc/#TPTP_Challenge_Problem_Set
%          : Cyc(R) Knowledge Base Copyright(C) 1995-2007 Cycorp, Inc., Austin,
%            TX, USA. All rights reserved.
%          : OpenCyc Knowledge Base Copyright(C) 2001-2007 Cycorp, Inc.,
%            Austin, TX, USA. All rights reserved.
%------------------------------------------------------------------------------
%$problem_series(cyc_scaling_1,[CSR025+1,CSR026+1,CSR027+1,CSR028+1,CSR029+1,CSR030+1,CSR031+1,CSR032+1,CSR033+1,CSR034+1,CSR035+1,CSR036+1,CSR037+1,CSR038+1,CSR039+1,CSR040+1,CSR041+1,CSR042+1,CSR043+1,CSR044+1,CSR045+1,CSR046+1,CSR047+1,CSR048+1,CSR049+1,CSR050+1,CSR051+1,CSR052+1,CSR053+1,CSR054+1,CSR055+1,CSR056+1,CSR057+1,CSR058+1,CSR059+1,CSR060+1,CSR061+1,CSR062+1,CSR063+1,CSR064+1,CSR065+1,CSR066+1,CSR067+1,CSR068+1,CSR069+1,CSR070+1,CSR071+1,CSR072+1,CSR073+1,CSR074+1])
%$static(cyc_scaling_1,include('Axioms/CSR002+0.ax'))
%----Empty file include('Axioms/CSR002+0.ax').
%------------------------------------------------------------------------------
% Cyc Assertion #253062:
fof(just1,axiom,(
    genlmt(c_geographymt,c_basekb) )).

% Cyc Assertion #631445:
fof(just2,axiom,(
    genlmt(c_worldgeographymt,c_geographymt) )).

% Cyc Assertion #1322220:
fof(just3,axiom,(
    transitivebinarypredicate(c_genlmt) )).

% Cyc Assertion #1494491:
fof(just4,axiom,(
    reflexivebinarypredicate(c_inregion) )).

% Cyc Assertion #1650755:
fof(just5,axiom,(
    genlmt(c_basekb,c_universalvocabularymt) )).

% Cyc Assertion #2463131:
fof(just6,axiom,(
    genlmt(c_tptpgeo_spindleheadmt,c_worldgeographymt) )).

% Cyc Assertion #2463166:
fof(just7,axiom,(
    genlmt(c_tptpgeo_member8_mt,c_tptpgeo_spindleheadmt) )).

% Cyc Assertion #831913:
fof(just8,axiom,(
    ! [SPECPRED,PRED,GENLPRED] :
      ( ( genlinverse(SPECPRED,PRED)
        & genlinverse(PRED,GENLPRED) )
     => genlpreds(SPECPRED,GENLPRED) ) )).

% Cyc Assertion #398814:
fof(just9,axiom,(
    ! [OBJ,COL1,COL2] :
      ~ ( isa(OBJ,COL1)
        & isa(OBJ,COL2)
        & disjointwith(COL1,COL2) ) )).

% Cyc Assertion #2484090:
fof(just10,axiom,
    ( mtvisible(c_worldgeographymt)
   => geolevel_4(c_georegion_l4_x75_y75) )).

% Cyc Assertion #2463177:
fof(just11,axiom,(
    genls(c_geolevel_4,c_geographicalregion) )).

fof(just12,axiom,(
    ! [OBJ] :
      ( geolevel_4(OBJ)
     => geographicalregion(OBJ) ) )).

% Cyc Assertion #2463166:
fof(just13,axiom,(
    genlmt(c_tptpgeo_member8_mt,c_tptpgeo_spindleheadmt) )).

% Cyc Assertion #2463131:
fof(just14,axiom,(
    genlmt(c_tptpgeo_spindleheadmt,c_worldgeographymt) )).

% Cyc Assertion #1650755:
fof(just15,axiom,(
    genlmt(c_basekb,c_universalvocabularymt) )).

% Cyc Assertion #1639598:
fof(just16,axiom,(
    genls(c_enduringthing_localized,c_spatialthing_nonsituational) )).

fof(just17,axiom,(
    ! [OBJ] :
      ( enduringthing_localized(OBJ)
     => spatialthing_nonsituational(OBJ) ) )).

% Cyc Assertion #1610132:
fof(just18,axiom,(
    genls(c_partiallytangible,c_enduringthing_localized) )).

fof(just19,axiom,(
    ! [OBJ] :
      ( partiallytangible(OBJ)
     => enduringthing_localized(OBJ) ) )).

% Cyc Assertion #1322220:
fof(just20,axiom,(
    transitivebinarypredicate(c_genlmt) )).

% Cyc Assertion #631445:
fof(just21,axiom,(
    genlmt(c_worldgeographymt,c_geographymt) )).

% Cyc Assertion #612894:
fof(just22,axiom,(
    genls(c_geographicalregion,c_partiallytangible) )).

fof(just23,axiom,(
    ! [OBJ] :
      ( geographicalregion(OBJ)
     => partiallytangible(OBJ) ) )).

% Cyc Assertion #253062:
fof(just24,axiom,(
    genlmt(c_geographymt,c_basekb) )).

% Cyc Assertion #831913:
fof(just25,axiom,(
    ! [SPECPRED,PRED,GENLPRED] :
      ( ( genlinverse(SPECPRED,PRED)
        & genlinverse(PRED,GENLPRED) )
     => genlpreds(SPECPRED,GENLPRED) ) )).

% Cyc Assertion #398814:
fof(just26,axiom,(
    ! [OBJ,COL1,COL2] :
      ~ ( isa(OBJ,COL1)
        & isa(OBJ,COL2)
        & disjointwith(COL1,COL2) ) )).

% Cyc Assertion #2484090:
fof(just27,axiom,
    ( mtvisible(c_worldgeographymt)
   => geolevel_4(c_georegion_l4_x75_y75) )).

% Cyc Assertion #2463177:
fof(just28,axiom,(
    genls(c_geolevel_4,c_geographicalregion) )).

fof(just29,axiom,(
    ! [OBJ] :
      ( geolevel_4(OBJ)
     => geographicalregion(OBJ) ) )).

% Cyc Assertion #2463166:
fof(just30,axiom,(
    genlmt(c_tptpgeo_member8_mt,c_tptpgeo_spindleheadmt) )).

% Cyc Assertion #2463131:
fof(just31,axiom,(
    genlmt(c_tptpgeo_spindleheadmt,c_worldgeographymt) )).

% Cyc Assertion #1650755:
fof(just32,axiom,(
    genlmt(c_basekb,c_universalvocabularymt) )).

% Cyc Assertion #1639598:
fof(just33,axiom,(
    genls(c_enduringthing_localized,c_spatialthing_nonsituational) )).

fof(just34,axiom,(
    ! [OBJ] :
      ( enduringthing_localized(OBJ)
     => spatialthing_nonsituational(OBJ) ) )).

% Cyc Assertion #1610132:
fof(just35,axiom,(
    genls(c_partiallytangible,c_enduringthing_localized) )).

fof(just36,axiom,(
    ! [OBJ] :
      ( partiallytangible(OBJ)
     => enduringthing_localized(OBJ) ) )).

% Cyc Assertion #1322220:
fof(just37,axiom,(
    transitivebinarypredicate(c_genlmt) )).

% Cyc Assertion #631445:
fof(just38,axiom,(
    genlmt(c_worldgeographymt,c_geographymt) )).

% Cyc Assertion #612894:
fof(just39,axiom,(
    genls(c_geographicalregion,c_partiallytangible) )).

fof(just40,axiom,(
    ! [OBJ] :
      ( geographicalregion(OBJ)
     => partiallytangible(OBJ) ) )).

% Cyc Assertion #253062:
fof(just41,axiom,(
    genlmt(c_geographymt,c_basekb) )).

% Cyc Assertion #398814:
fof(just42,axiom,(
    ! [OBJ,COL1,COL2] :
      ~ ( isa(OBJ,COL1)
        & isa(OBJ,COL2)
        & disjointwith(COL1,COL2) ) )).

% Cyc Assertion #831913:
fof(just43,axiom,(
    ! [SPECPRED,PRED,GENLPRED] :
      ( ( genlinverse(SPECPRED,PRED)
        & genlinverse(PRED,GENLPRED) )
     => genlpreds(SPECPRED,GENLPRED) ) )).

% Cyc Constant #36435:
fof(just44,axiom,(
    ! [X] :
      ( isa(X,c_partiallytangible)
     => partiallytangible(X) ) )).

fof(just45,axiom,(
    ! [X] :
      ( partiallytangible(X)
     => isa(X,c_partiallytangible) ) )).

% Cyc Constant #25931:
fof(just46,axiom,(
    ! [X] :
      ( isa(X,c_spatialthing_nonsituational)
     => spatialthing_nonsituational(X) ) )).

fof(just47,axiom,(
    ! [X] :
      ( spatialthing_nonsituational(X)
     => isa(X,c_spatialthing_nonsituational) ) )).

% Cyc Constant #62476:
fof(just48,axiom,(
    ! [X] :
      ( isa(X,c_enduringthing_localized)
     => enduringthing_localized(X) ) )).

fof(just49,axiom,(
    ! [X] :
      ( enduringthing_localized(X)
     => isa(X,c_enduringthing_localized) ) )).

% Cyc Constant #30683:
fof(just50,axiom,(
    ! [X] :
      ( isa(X,c_geographicalregion)
     => geographicalregion(X) ) )).

fof(just51,axiom,(
    ! [X] :
      ( geographicalregion(X)
     => isa(X,c_geographicalregion) ) )).

% Cyc Constant #0:
fof(just52,axiom,(
    ! [ARG1,INS] :
      ( genls(ARG1,INS)
     => collection(INS) ) )).

fof(just53,axiom,(
    ! [ARG1,INS] :
      ( genls(ARG1,INS)
     => collection(INS) ) )).

fof(just54,axiom,(
    ! [INS,ARG2] :
      ( genls(INS,ARG2)
     => collection(INS) ) )).

fof(just55,axiom,(
    ! [INS,ARG2] :
      ( genls(INS,ARG2)
     => collection(INS) ) )).

fof(just56,axiom,(
    ! [X,Y,Z] :
      ( ( genls(X,Y)
        & genls(Y,Z) )
     => genls(X,Z) ) )).

fof(just57,axiom,(
    ! [X] :
      ( collection(X)
     => genls(X,X) ) )).

fof(just58,axiom,(
    ! [X] :
      ( collection(X)
     => genls(X,X) ) )).

fof(just59,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( genls(OLD,ARG2)
        & genls(NEW,OLD) )
     => genls(NEW,ARG2) ) )).

fof(just60,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( genls(ARG1,OLD)
        & genls(OLD,NEW) )
     => genls(ARG1,NEW) ) )).

% Cyc Constant #380146:
fof(just61,axiom,(
    ! [X] :
      ( isa(X,c_geolevel_4)
     => geolevel_4(X) ) )).

fof(just62,axiom,(
    ! [X] :
      ( geolevel_4(X)
     => isa(X,c_geolevel_4) ) )).

% Cyc Constant #78648:
fof(just63,axiom,(
    ! [ARG1,INS] :
      ( disjointwith(ARG1,INS)
     => collection(INS) ) )).

fof(just64,axiom,(
    ! [INS,ARG2] :
      ( disjointwith(INS,ARG2)
     => collection(INS) ) )).

fof(just65,axiom,(
    ! [X,Y] :
      ( disjointwith(X,Y)
     => disjointwith(Y,X) ) )).

fof(just66,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( disjointwith(ARG1,OLD)
        & genls(NEW,OLD) )
     => disjointwith(ARG1,NEW) ) )).

fof(just67,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( disjointwith(OLD,ARG2)
        & genls(NEW,OLD) )
     => disjointwith(NEW,ARG2) ) )).

% Cyc Constant #40273:
fof(just68,axiom,(
    ! [ARG1,INS] :
      ( genlpreds(ARG1,INS)
     => predicate(INS) ) )).

fof(just69,axiom,(
    ! [ARG1,INS] :
      ( genlpreds(ARG1,INS)
     => predicate(INS) ) )).

fof(just70,axiom,(
    ! [INS,ARG2] :
      ( genlpreds(INS,ARG2)
     => predicate(INS) ) )).

fof(just71,axiom,(
    ! [INS,ARG2] :
      ( genlpreds(INS,ARG2)
     => predicate(INS) ) )).

fof(just72,axiom,(
    ! [X,Y,Z] :
      ( ( genlpreds(X,Y)
        & genlpreds(Y,Z) )
     => genlpreds(X,Z) ) )).

fof(just73,axiom,(
    ! [X] :
      ( predicate(X)
     => genlpreds(X,X) ) )).

fof(just74,axiom,(
    ! [X] :
      ( predicate(X)
     => genlpreds(X,X) ) )).

% Cyc Constant #45259:
fof(just75,axiom,(
    ! [ARG1,INS] :
      ( genlinverse(ARG1,INS)
     => binarypredicate(INS) ) )).

fof(just76,axiom,(
    ! [INS,ARG2] :
      ( genlinverse(INS,ARG2)
     => binarypredicate(INS) ) )).

fof(just77,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( genlinverse(OLD,ARG2)
        & genlpreds(NEW,OLD) )
     => genlinverse(NEW,ARG2) ) )).

fof(just78,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( genlinverse(ARG1,OLD)
        & genlpreds(OLD,NEW) )
     => genlinverse(ARG1,NEW) ) )).

% Cyc Constant #1988:
fof(just79,axiom,(
    ! [X] :
      ( isa(X,c_reflexivebinarypredicate)
     => reflexivebinarypredicate(X) ) )).

fof(just80,axiom,(
    ! [X] :
      ( reflexivebinarypredicate(X)
     => isa(X,c_reflexivebinarypredicate) ) )).

% Cyc Constant #98385:
fof(just81,axiom,(
    ! [ARG1,INS] :
      ( inregion(ARG1,INS)
     => spatialthing_nonsituational(INS) ) )).

fof(just82,axiom,(
    ! [INS,ARG2] :
      ( inregion(INS,ARG2)
     => spatialthing_nonsituational(INS) ) )).

fof(just83,axiom,(
    ! [X,Y,Z] :
      ( ( inregion(X,Y)
        & inregion(Y,Z) )
     => inregion(X,Z) ) )).

fof(just84,axiom,(
    ! [X] :
      ( spatialthing_nonsituational(X)
     => inregion(X,X) ) )).

% Cyc Constant #127156:
fof(just85,axiom,(
    ! [X] :
      ( isa(X,c_transitivebinarypredicate)
     => transitivebinarypredicate(X) ) )).

fof(just86,axiom,(
    ! [X] :
      ( transitivebinarypredicate(X)
     => isa(X,c_transitivebinarypredicate) ) )).

% Cyc Constant #72115:
fof(just87,axiom,(
    ! [ARG1,INS] :
      ( isa(ARG1,INS)
     => collection(INS) ) )).

fof(just88,axiom,(
    ! [ARG1,INS] :
      ( isa(ARG1,INS)
     => collection(INS) ) )).

fof(just89,axiom,(
    ! [INS,ARG2] :
      ( isa(INS,ARG2)
     => thing(INS) ) )).

fof(just90,axiom,(
    ! [INS,ARG2] :
      ( isa(INS,ARG2)
     => thing(INS) ) )).

fof(just91,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( isa(ARG1,OLD)
        & genls(OLD,NEW) )
     => isa(ARG1,NEW) ) )).

% Cyc Constant #95028:
fof(just92,axiom,(
    mtvisible(c_universalvocabularymt) )).

% Cyc Constant #19550:
fof(just93,axiom,(
    ! [SPECMT,GENLMT] :
      ( ( mtvisible(SPECMT)
        & genlmt(SPECMT,GENLMT) )
     => mtvisible(GENLMT) ) )).

fof(just94,axiom,(
    ! [ARG1,INS] :
      ( genlmt(ARG1,INS)
     => microtheory(INS) ) )).

fof(just95,axiom,(
    ! [ARG1,INS] :
      ( genlmt(ARG1,INS)
     => microtheory(INS) ) )).

fof(just96,axiom,(
    ! [INS,ARG2] :
      ( genlmt(INS,ARG2)
     => microtheory(INS) ) )).

fof(just97,axiom,(
    ! [INS,ARG2] :
      ( genlmt(INS,ARG2)
     => microtheory(INS) ) )).

fof(just98,axiom,(
    ! [X,Y,Z] :
      ( ( genlmt(X,Y)
        & genlmt(Y,Z) )
     => genlmt(X,Z) ) )).

fof(just99,axiom,(
    ! [X] :
      ( microtheory(X)
     => genlmt(X,X) ) )).

fof(just100,axiom,(
    ! [X] :
      ( microtheory(X)
     => genlmt(X,X) ) )).

% Cyc Constant #27757:
fof(just101,axiom,(
    mtvisible(c_basekb) )).

fof(query57,conjecture,(
    ? [X] :
      ( mtvisible(c_tptpgeo_member8_mt)
     => inregion(X,c_georegion_l4_x75_y75) ) )).

%------------------------------------------------------------------------------
