%------------------------------------------------------------------------------
% File     : CSR050+1 : TPTP v6.1.0. Released v3.4.0.
% Domain   : Common Sense Reasoning
% Problem  : Autogenerated Cyc Problem CSR050+1
% Version  : Especial.
% English  :

% Refs     : [RS+]   Reagan Smith et al., The Cyc TPTP Challenge Problem
% Source   : [RS+]
% Names    :

% Status   : Theorem
% Rating   : 0.00 v6.1.0, 0.08 v6.0.0, 0.25 v5.5.0, 0.12 v5.4.0, 0.17 v5.3.0, 0.30 v5.2.0, 0.14 v5.1.0, 0.07 v5.0.0, 0.15 v4.1.0, 0.11 v4.0.0, 0.10 v3.7.0, 0.00 v3.4.0
% Syntax   : Number of formulae    :   87 (  30 unit)
%            Number of atoms       :  158 (   0 equality)
%            Maximal formula depth :    7 (   3 average)
%            Number of connectives :   73 (   2 ~  ;   0  |;  15  &)
%                                         (   0 <=>;  56 =>;   0 <=)
%                                         (   0 <~>;   0 ~|;   0 ~&)
%            Number of predicates  :   30 (   0 propositional; 1-3 arity)
%            Number of functors    :   31 (  27 constant; 0-3 arity)
%            Number of variables   :  141 (   0 singleton; 141 !;   0 ?)
%            Maximal term depth    :    4 (   1 average)
% SPC      : FOF_THM_RFO_NEQ

% Comments : Autogenerated from the OpenCyc KB. Documentation can be found at
%            http://opencyc.org/doc/#TPTP_Challenge_Problem_Set
%          : Cyc(R) Knowledge Base Copyright(C) 1995-2007 Cycorp, Inc., Austin,
%            TX, USA. All rights reserved.
%          : OpenCyc Knowledge Base Copyright(C) 2001-2007 Cycorp, Inc.,
%            Austin, TX, USA. All rights reserved.
%------------------------------------------------------------------------------
%$problem_series(cyc_scaling_1,[CSR025+1,CSR026+1,CSR027+1,CSR028+1,CSR029+1,CSR030+1,CSR031+1,CSR032+1,CSR033+1,CSR034+1,CSR035+1,CSR036+1,CSR037+1,CSR038+1,CSR039+1,CSR040+1,CSR041+1,CSR042+1,CSR043+1,CSR044+1,CSR045+1,CSR046+1,CSR047+1,CSR048+1,CSR049+1,CSR050+1,CSR051+1,CSR052+1,CSR053+1,CSR054+1,CSR055+1,CSR056+1,CSR057+1,CSR058+1,CSR059+1,CSR060+1,CSR061+1,CSR062+1,CSR063+1,CSR064+1,CSR065+1,CSR066+1,CSR067+1,CSR068+1,CSR069+1,CSR070+1,CSR071+1,CSR072+1,CSR073+1,CSR074+1])
%$static(cyc_scaling_1,include('Axioms/CSR002+0.ax'))
%----Empty file include('Axioms/CSR002+0.ax').
%------------------------------------------------------------------------------
% Cyc Assertion #518539:
fof(just1,axiom,(
    genlmt(c_ldscdemonstrationspindleheadmt,c_currentworlddatacollectormt_nonhomocentric) )).

% Cyc Assertion #592971:
fof(just2,axiom,(
    genlmt(c_cycorpproductsmt,c_basekb) )).

% Cyc Assertion #600900:
fof(just3,axiom,(
    genlmt(c_cycnounlearnermt,c_cycorpproductsmt) )).

% Cyc Assertion #880523:
fof(just4,axiom,(
    genlmt(f_contentmtofcdafromeventfn(f_urlreferentfn(f_urlfn(s_http_memberstripodcomindygalfordtriviahtm)),c_translation_32),c_machinelearningspindleheadmt) )).

% Cyc Assertion #964779:
fof(just5,axiom,(
    genlmt(c_machinelearningspindleheadmt,c_miptdatabase19681997_termsmt) )).

% Cyc Assertion #1028120:
fof(just6,axiom,(
    genlmt(c_miptdatabase19681997_termsmt,c_ldscgeneralcollectormt) )).

% Cyc Assertion #1103756:
fof(just7,axiom,(
    genlmt(c_ldscgeneralcollectormt,c_ldscdemonstrationspindleheadmt) )).

% Cyc Assertion #1322220:
fof(just8,axiom,(
    transitivebinarypredicate(c_genlmt) )).

% Cyc Assertion #1614635:
fof(just9,axiom,(
    genlmt(c_machinelearningspindleheadmt,c_cycnounlearnermt) )).

% Cyc Assertion #1650755:
fof(just10,axiom,(
    genlmt(c_basekb,c_universalvocabularymt) )).

% Cyc Assertion #2155278:
fof(just11,axiom,(
    genlinverse(c_tptptypes_8_692,c_tptptypes_7_691) )).

fof(just12,axiom,(
    ! [ARG1,ARG2] :
      ( tptptypes_8_692(ARG1,ARG2)
     => tptptypes_7_691(ARG2,ARG1) ) )).

% Cyc Assertion #2155285:
fof(just13,axiom,(
    genlpreds(c_tptptypes_9_693,c_tptptypes_8_692) )).

fof(just14,axiom,(
    ! [ARG1,ARG2] :
      ( tptptypes_9_693(ARG1,ARG2)
     => tptptypes_8_692(ARG1,ARG2) ) )).

% Cyc Assertion #2189688:
fof(just15,axiom,
    ( mtvisible(c_currentworlddatacollectormt_nonhomocentric)
   => tptptypes_9_693(f_subcollectionofwithrelationtofn(c_ship,c_objectfoundinlocation,c_cityofbostonma),c_tptpcol_16_26939) )).

% Cyc Assertion #398814:
fof(just16,axiom,(
    ! [OBJ,COL1,COL2] :
      ~ ( isa(OBJ,COL1)
        & isa(OBJ,COL2)
        & disjointwith(COL1,COL2) ) )).

% Cyc Assertion #831913:
fof(just17,axiom,(
    ! [SPECPRED,PRED,GENLPRED] :
      ( ( genlinverse(SPECPRED,PRED)
        & genlinverse(PRED,GENLPRED) )
     => genlpreds(SPECPRED,GENLPRED) ) )).

% Cyc Constant #78648:
fof(just18,axiom,(
    ! [ARG1,INS] :
      ( disjointwith(ARG1,INS)
     => collection(INS) ) )).

fof(just19,axiom,(
    ! [INS,ARG2] :
      ( disjointwith(INS,ARG2)
     => collection(INS) ) )).

fof(just20,axiom,(
    ! [X,Y] :
      ( disjointwith(X,Y)
     => disjointwith(Y,X) ) )).

fof(just21,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( disjointwith(ARG1,OLD)
        & genls(NEW,OLD) )
     => disjointwith(ARG1,NEW) ) )).

fof(just22,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( disjointwith(OLD,ARG2)
        & genls(NEW,OLD) )
     => disjointwith(NEW,ARG2) ) )).

% Cyc Constant #156536:
fof(just23,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_16_26939)
     => tptpcol_16_26939(X) ) )).

fof(just24,axiom,(
    ! [X] :
      ( tptpcol_16_26939(X)
     => isa(X,c_tptpcol_16_26939) ) )).

% Cyc Constant #66840:
fof(just25,axiom,(
    ! [ARG1,INS] :
      ( objectfoundinlocation(ARG1,INS)
     => spatialthing_nonsituational(INS) ) )).

fof(just26,axiom,(
    ! [ARG1,INS] :
      ( objectfoundinlocation(ARG1,INS)
     => spatialthing_localized(INS) ) )).

fof(just27,axiom,(
    ! [INS,ARG2] :
      ( objectfoundinlocation(INS,ARG2)
     => spatialthing_nonsituational(INS) ) )).

fof(just28,axiom,(
    ! [INS,ARG2] :
      ( objectfoundinlocation(INS,ARG2)
     => spatialthing_localized(INS) ) )).

fof(just29,axiom,(
    ! [X,Y,Z] :
      ( ( objectfoundinlocation(X,Y)
        & objectfoundinlocation(Y,Z) )
     => objectfoundinlocation(X,Z) ) )).

fof(just30,axiom,(
    ! [X] : ~ objectfoundinlocation(X,X) )).

fof(just31,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( objectfoundinlocation(ARG1,OLD)
        & geopoliticalsubdivision(NEW,OLD) )
     => objectfoundinlocation(ARG1,NEW) ) )).

fof(just32,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( objectfoundinlocation(ARG1,OLD)
        & geographicallysubsumes(NEW,OLD) )
     => objectfoundinlocation(ARG1,NEW) ) )).

fof(just33,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( objectfoundinlocation(ARG1,OLD)
        & subregions(NEW,OLD) )
     => objectfoundinlocation(ARG1,NEW) ) )).

% Cyc Constant #54624:
fof(just34,axiom,(
    ! [X] :
      ( isa(X,c_ship)
     => ship(X) ) )).

fof(just35,axiom,(
    ! [X] :
      ( ship(X)
     => isa(X,c_ship) ) )).

% Cyc Constant #93912:
fof(just36,axiom,(
    ! [ARG1,ARG2,ARG3] : natfunction(f_subcollectionofwithrelationtofn(ARG1,ARG2,ARG3),c_subcollectionofwithrelationtofn) )).

fof(just37,axiom,(
    ! [ARG1,ARG2,ARG3] : natargument(f_subcollectionofwithrelationtofn(ARG1,ARG2,ARG3),n_1,ARG1) )).

fof(just38,axiom,(
    ! [ARG1,ARG2,ARG3] : natargument(f_subcollectionofwithrelationtofn(ARG1,ARG2,ARG3),n_2,ARG2) )).

fof(just39,axiom,(
    ! [ARG1,ARG2,ARG3] : natargument(f_subcollectionofwithrelationtofn(ARG1,ARG2,ARG3),n_3,ARG3) )).

fof(just40,axiom,(
    ! [ARG1,ARG2,ARG3] : collection(f_subcollectionofwithrelationtofn(ARG1,ARG2,ARG3)) )).

% Cyc NART #11809:
fof(just41,axiom,(
    ! [X] :
      ( isa(X,f_subcollectionofwithrelationtofn(c_ship,c_objectfoundinlocation,c_cityofbostonma))
     => subcollectionofwithrelationtofnshipobjectfoundinlocationcityofbostonma(X) ) )).

fof(just42,axiom,(
    ! [X] :
      ( subcollectionofwithrelationtofnshipobjectfoundinlocationcityofbostonma(X)
     => isa(X,f_subcollectionofwithrelationtofn(c_ship,c_objectfoundinlocation,c_cityofbostonma)) ) )).

% Cyc Constant #261362:
fof(just43,axiom,(
    ! [ARG1,INS] :
      ( tptptypes_9_693(ARG1,INS)
     => firstordercollection(INS) ) )).

fof(just44,axiom,(
    ! [INS,ARG2] :
      ( tptptypes_9_693(INS,ARG2)
     => firstordercollection(INS) ) )).

% Cyc Constant #40273:
fof(just45,axiom,(
    ! [ARG1,INS] :
      ( genlpreds(ARG1,INS)
     => predicate(INS) ) )).

fof(just46,axiom,(
    ! [ARG1,INS] :
      ( genlpreds(ARG1,INS)
     => predicate(INS) ) )).

fof(just47,axiom,(
    ! [INS,ARG2] :
      ( genlpreds(INS,ARG2)
     => predicate(INS) ) )).

fof(just48,axiom,(
    ! [INS,ARG2] :
      ( genlpreds(INS,ARG2)
     => predicate(INS) ) )).

fof(just49,axiom,(
    ! [X,Y,Z] :
      ( ( genlpreds(X,Y)
        & genlpreds(Y,Z) )
     => genlpreds(X,Z) ) )).

fof(just50,axiom,(
    ! [X] :
      ( predicate(X)
     => genlpreds(X,X) ) )).

fof(just51,axiom,(
    ! [X] :
      ( predicate(X)
     => genlpreds(X,X) ) )).

% Cyc Constant #261360:
fof(just52,axiom,(
    ! [ARG1,INS] :
      ( tptptypes_7_691(ARG1,INS)
     => firstordercollection(INS) ) )).

fof(just53,axiom,(
    ! [INS,ARG2] :
      ( tptptypes_7_691(INS,ARG2)
     => firstordercollection(INS) ) )).

% Cyc Constant #261361:
fof(just54,axiom,(
    ! [ARG1,INS] :
      ( tptptypes_8_692(ARG1,INS)
     => firstordercollection(INS) ) )).

fof(just55,axiom,(
    ! [INS,ARG2] :
      ( tptptypes_8_692(INS,ARG2)
     => firstordercollection(INS) ) )).

% Cyc Constant #45259:
fof(just56,axiom,(
    ! [ARG1,INS] :
      ( genlinverse(ARG1,INS)
     => binarypredicate(INS) ) )).

fof(just57,axiom,(
    ! [INS,ARG2] :
      ( genlinverse(INS,ARG2)
     => binarypredicate(INS) ) )).

fof(just58,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( genlinverse(OLD,ARG2)
        & genlpreds(NEW,OLD) )
     => genlinverse(NEW,ARG2) ) )).

fof(just59,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( genlinverse(ARG1,OLD)
        & genlpreds(OLD,NEW) )
     => genlinverse(ARG1,NEW) ) )).

% Cyc Constant #127156:
fof(just60,axiom,(
    ! [X] :
      ( isa(X,c_transitivebinarypredicate)
     => transitivebinarypredicate(X) ) )).

fof(just61,axiom,(
    ! [X] :
      ( transitivebinarypredicate(X)
     => isa(X,c_transitivebinarypredicate) ) )).

% Cyc Constant #72115:
fof(just62,axiom,(
    ! [ARG1,INS] :
      ( isa(ARG1,INS)
     => collection(INS) ) )).

fof(just63,axiom,(
    ! [ARG1,INS] :
      ( isa(ARG1,INS)
     => collection(INS) ) )).

fof(just64,axiom,(
    ! [INS,ARG2] :
      ( isa(INS,ARG2)
     => thing(INS) ) )).

fof(just65,axiom,(
    ! [INS,ARG2] :
      ( isa(INS,ARG2)
     => thing(INS) ) )).

fof(just66,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( isa(ARG1,OLD)
        & genls(OLD,NEW) )
     => isa(ARG1,NEW) ) )).

% Cyc Constant #129091:
fof(just67,axiom,(
    ! [ARG1] : natfunction(f_urlfn(ARG1),c_urlfn) )).

fof(just68,axiom,(
    ! [ARG1] : natargument(f_urlfn(ARG1),n_1,ARG1) )).

fof(just69,axiom,(
    ! [ARG1] : uniformresourcelocator(f_urlfn(ARG1)) )).

% Cyc Constant #78971:
fof(just70,axiom,(
    ! [ARG1] : natfunction(f_urlreferentfn(ARG1),c_urlreferentfn) )).

fof(just71,axiom,(
    ! [ARG1] : natargument(f_urlreferentfn(ARG1),n_1,ARG1) )).

fof(just72,axiom,(
    ! [ARG1] : computerdataartifact(f_urlreferentfn(ARG1)) )).

% Cyc Constant #71728:
fof(just73,axiom,(
    ! [ARG1,ARG2] : natfunction(f_contentmtofcdafromeventfn(ARG1,ARG2),c_contentmtofcdafromeventfn) )).

fof(just74,axiom,(
    ! [ARG1,ARG2] : natargument(f_contentmtofcdafromeventfn(ARG1,ARG2),n_1,ARG1) )).

fof(just75,axiom,(
    ! [ARG1,ARG2] : natargument(f_contentmtofcdafromeventfn(ARG1,ARG2),n_2,ARG2) )).

fof(just76,axiom,(
    ! [ARG1,ARG2] : microtheory(f_contentmtofcdafromeventfn(ARG1,ARG2)) )).

% Cyc Constant #27757:
fof(just77,axiom,(
    mtvisible(c_basekb) )).

% Cyc Constant #19550:
fof(just78,axiom,(
    ! [SPECMT,GENLMT] :
      ( ( mtvisible(SPECMT)
        & genlmt(SPECMT,GENLMT) )
     => mtvisible(GENLMT) ) )).

fof(just79,axiom,(
    ! [ARG1,INS] :
      ( genlmt(ARG1,INS)
     => microtheory(INS) ) )).

fof(just80,axiom,(
    ! [ARG1,INS] :
      ( genlmt(ARG1,INS)
     => microtheory(INS) ) )).

fof(just81,axiom,(
    ! [INS,ARG2] :
      ( genlmt(INS,ARG2)
     => microtheory(INS) ) )).

fof(just82,axiom,(
    ! [INS,ARG2] :
      ( genlmt(INS,ARG2)
     => microtheory(INS) ) )).

fof(just83,axiom,(
    ! [X,Y,Z] :
      ( ( genlmt(X,Y)
        & genlmt(Y,Z) )
     => genlmt(X,Z) ) )).

fof(just84,axiom,(
    ! [X] :
      ( microtheory(X)
     => genlmt(X,X) ) )).

fof(just85,axiom,(
    ! [X] :
      ( microtheory(X)
     => genlmt(X,X) ) )).

% Cyc Constant #95028:
fof(just86,axiom,(
    mtvisible(c_universalvocabularymt) )).

fof(query50,conjecture,
    ( mtvisible(f_contentmtofcdafromeventfn(f_urlreferentfn(f_urlfn(s_http_memberstripodcomindygalfordtriviahtm)),c_translation_32))
   => tptptypes_7_691(c_tptpcol_16_26939,f_subcollectionofwithrelationtofn(c_ship,c_objectfoundinlocation,c_cityofbostonma)) )).

%------------------------------------------------------------------------------
