%------------------------------------------------------------------------------
% File     : CSR027+1 : TPTP v6.1.0. Released v3.4.0.
% Domain   : Common Sense Reasoning
% Problem  : Autogenerated Cyc Problem CSR027+1
% Version  : Especial.
% English  :

% Refs     : [RS+]   Reagan Smith et al., The Cyc TPTP Challenge Problem
% Source   : [RS+]
% Names    :

% Status   : Theorem
% Rating   : 0.00 v6.1.0, 0.04 v6.0.0, 0.25 v5.5.0, 0.12 v5.4.0, 0.17 v5.3.0, 0.26 v5.2.0, 0.14 v5.0.0, 0.15 v4.1.0, 0.11 v4.0.0, 0.10 v3.7.0, 0.00 v3.4.0
% Syntax   : Number of formulae    :   80 (  25 unit)
%            Number of atoms       :  149 (   0 equality)
%            Maximal formula depth :    7 (   4 average)
%            Number of connectives :   70 (   1 ~  ;   0  |;  15  &)
%                                         (   0 <=>;  54 =>;   0 <=)
%                                         (   0 <~>;   0 ~|;   0 ~&)
%            Number of predicates  :   27 (   0 propositional; 1-3 arity)
%            Number of functors    :   25 (  23 constant; 0-4 arity)
%            Number of variables   :  146 (   0 singleton; 145 !;   1 ?)
%            Maximal term depth    :    3 (   1 average)
% SPC      : FOF_THM_RFO_NEQ

% Comments : Autogenerated from the OpenCyc KB. Documentation can be found at
%            http://opencyc.org/doc/#TPTP_Challenge_Problem_Set
%          : Cyc(R) Knowledge Base Copyright(C) 1995-2007 Cycorp, Inc., Austin,
%            TX, USA. All rights reserved.
%          : OpenCyc Knowledge Base Copyright(C) 2001-2007 Cycorp, Inc.,
%            Austin, TX, USA. All rights reserved.
%------------------------------------------------------------------------------
%$problem_series(cyc_scaling_1,[CSR025+1,CSR026+1,CSR027+1,CSR028+1,CSR029+1,CSR030+1,CSR031+1,CSR032+1,CSR033+1,CSR034+1,CSR035+1,CSR036+1,CSR037+1,CSR038+1,CSR039+1,CSR040+1,CSR041+1,CSR042+1,CSR043+1,CSR044+1,CSR045+1,CSR046+1,CSR047+1,CSR048+1,CSR049+1,CSR050+1,CSR051+1,CSR052+1,CSR053+1,CSR054+1,CSR055+1,CSR056+1,CSR057+1,CSR058+1,CSR059+1,CSR060+1,CSR061+1,CSR062+1,CSR063+1,CSR064+1,CSR065+1,CSR066+1,CSR067+1,CSR068+1,CSR069+1,CSR070+1,CSR071+1,CSR072+1,CSR073+1,CSR074+1])
%$static(cyc_scaling_1,include('Axioms/CSR002+0.ax'))
%----Empty file include('Axioms/CSR002+0.ax').
%------------------------------------------------------------------------------
% Cyc Assertion #1008490:
fof(just1,axiom,(
    ! [TERM,INDEPCOL,PRED,DEPCOL] :
      ( ( isa(TERM,INDEPCOL)
        & relationallexists(PRED,INDEPCOL,DEPCOL) )
     => isa(f_relationallexistsfn(TERM,PRED,INDEPCOL,DEPCOL),DEPCOL) ) )).

fof(just2,axiom,(
    resultisaarg(c_relationallexistsfn,n_4) )).

% Cyc Assertion #1077444:
fof(just3,axiom,(
    genlmt(c_calendarsmt,c_calendarsvocabularymt) )).

% Cyc Assertion #1322220:
fof(just4,axiom,(
    transitivebinarypredicate(c_genlmt) )).

% Cyc Assertion #1650755:
fof(just5,axiom,(
    genlmt(c_basekb,c_universalvocabularymt) )).

% Cyc Assertion #1706514:
fof(just6,axiom,(
    genlmt(c_cyclistsmt,c_calendarsmt) )).

% Cyc Assertion #1746783:
fof(just7,axiom,(
    genlmt(c_calendarsvocabularymt,c_basekb) )).

% Cyc Assertion #2170932:
fof(just8,axiom,(
    genlmt(c_tptp_spindleheadmt,c_cyclistsmt) )).

% Cyc Assertion #2181376:
fof(just9,axiom,(
    genlmt(c_tptp_spindlecollectormt,c_tptp_member2610_mt) )).

% Cyc Assertion #2186907:
fof(just10,axiom,(
    genlmt(c_tptp_member3993_mt,c_tptp_spindleheadmt) )).

% Cyc Assertion #2186908:
fof(just11,axiom,(
    genlmt(c_tptp_spindlecollectormt,c_tptp_member3993_mt) )).

% Cyc Assertion #2194401:
fof(just12,axiom,(
    ! [TERM] :
      ( ( mtvisible(c_tptp_member2610_mt)
        & isa(TERM,f_subcollectionofwithrelationfromtypefn(c_unitvectorinterval,c_directionoftranslation_throughout,c_movement_translationevent)) )
     => tptp_8_875(TERM,f_relationallexistsfn(TERM,c_tptp_8_875,f_subcollectionofwithrelationfromtypefn(c_unitvectorinterval,c_directionoftranslation_throughout,c_movement_translationevent),c_tptpcol_16_31868)) ) )).

fof(just13,axiom,
    ( mtvisible(c_tptp_member2610_mt)
   => relationallexists(c_tptp_8_875,f_subcollectionofwithrelationfromtypefn(c_unitvectorinterval,c_directionoftranslation_throughout,c_movement_translationevent),c_tptpcol_16_31868) )).

% Cyc Assertion #2287217:
fof(just14,axiom,(
    isa(c_tptpnsubcollectionofwithrelationfromtypefnunitvectorintervaldirectionoftranslation_throughoutmovement_translationevent_786,f_subcollectionofwithrelationfromtypefn(c_unitvectorinterval,c_directionoftranslation_throughout,c_movement_translationevent)) )).

fof(just15,axiom,(
    subcollectionofwithrelationfromtypefnunitvectorintervaldirectionoftranslation_throughoutmovement_translationevent(c_tptpnsubcollectionofwithrelationfromtypefnunitvectorintervaldirectionoftranslation_throughoutmovement_translationevent_786) )).

% Cyc Assertion #398814:
fof(just16,axiom,(
    ! [OBJ,COL1,COL2] :
      ~ ( isa(OBJ,COL1)
        & isa(OBJ,COL2)
        & disjointwith(COL1,COL2) ) )).

% Cyc Assertion #831913:
fof(just17,axiom,(
    ! [SPECPRED,PRED,GENLPRED] :
      ( ( genlinverse(SPECPRED,PRED)
        & genlinverse(PRED,GENLPRED) )
     => genlpreds(SPECPRED,GENLPRED) ) )).

% Cyc Constant #40273:
fof(just18,axiom,(
    ! [ARG1,INS] :
      ( genlpreds(ARG1,INS)
     => predicate(INS) ) )).

fof(just19,axiom,(
    ! [ARG1,INS] :
      ( genlpreds(ARG1,INS)
     => predicate(INS) ) )).

fof(just20,axiom,(
    ! [INS,ARG2] :
      ( genlpreds(INS,ARG2)
     => predicate(INS) ) )).

fof(just21,axiom,(
    ! [INS,ARG2] :
      ( genlpreds(INS,ARG2)
     => predicate(INS) ) )).

fof(just22,axiom,(
    ! [X,Y,Z] :
      ( ( genlpreds(X,Y)
        & genlpreds(Y,Z) )
     => genlpreds(X,Z) ) )).

fof(just23,axiom,(
    ! [X] :
      ( predicate(X)
     => genlpreds(X,X) ) )).

fof(just24,axiom,(
    ! [X] :
      ( predicate(X)
     => genlpreds(X,X) ) )).

% Cyc Constant #45259:
fof(just25,axiom,(
    ! [ARG1,INS] :
      ( genlinverse(ARG1,INS)
     => binarypredicate(INS) ) )).

fof(just26,axiom,(
    ! [INS,ARG2] :
      ( genlinverse(INS,ARG2)
     => binarypredicate(INS) ) )).

fof(just27,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( genlinverse(OLD,ARG2)
        & genlpreds(NEW,OLD) )
     => genlinverse(NEW,ARG2) ) )).

fof(just28,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( genlinverse(ARG1,OLD)
        & genlpreds(OLD,NEW) )
     => genlinverse(ARG1,NEW) ) )).

% Cyc Constant #78648:
fof(just29,axiom,(
    ! [ARG1,INS] :
      ( disjointwith(ARG1,INS)
     => collection(INS) ) )).

fof(just30,axiom,(
    ! [INS,ARG2] :
      ( disjointwith(INS,ARG2)
     => collection(INS) ) )).

fof(just31,axiom,(
    ! [X,Y] :
      ( disjointwith(X,Y)
     => disjointwith(Y,X) ) )).

fof(just32,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( disjointwith(ARG1,OLD)
        & genls(NEW,OLD) )
     => disjointwith(ARG1,NEW) ) )).

fof(just33,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( disjointwith(OLD,ARG2)
        & genls(NEW,OLD) )
     => disjointwith(NEW,ARG2) ) )).

% Cyc Constant #161465:
fof(just34,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_16_31868)
     => tptpcol_16_31868(X) ) )).

fof(just35,axiom,(
    ! [X] :
      ( tptpcol_16_31868(X)
     => isa(X,c_tptpcol_16_31868) ) )).

% Cyc Constant #63493:
fof(just36,axiom,(
    ! [X] :
      ( isa(X,c_movement_translationevent)
     => movement_translationevent(X) ) )).

fof(just37,axiom,(
    ! [X] :
      ( movement_translationevent(X)
     => isa(X,c_movement_translationevent) ) )).

% Cyc Constant #99582:
fof(just38,axiom,(
    ! [ARG1,INS] :
      ( directionoftranslation_throughout(ARG1,INS)
     => unitvectorinterval(INS) ) )).

fof(just39,axiom,(
    ! [INS,ARG2] :
      ( directionoftranslation_throughout(INS,ARG2)
     => movement_translationevent(INS) ) )).

fof(just40,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( directionoftranslation_throughout(OLD,ARG2)
        & subevents(OLD,NEW) )
     => directionoftranslation_throughout(NEW,ARG2) ) )).

% Cyc Constant #19603:
fof(just41,axiom,(
    ! [X] :
      ( isa(X,c_unitvectorinterval)
     => unitvectorinterval(X) ) )).

fof(just42,axiom,(
    ! [X] :
      ( unitvectorinterval(X)
     => isa(X,c_unitvectorinterval) ) )).

% Cyc Constant #42488:
fof(just43,axiom,(
    ! [ARG1,ARG2,ARG3] : natfunction(f_subcollectionofwithrelationfromtypefn(ARG1,ARG2,ARG3),c_subcollectionofwithrelationfromtypefn) )).

fof(just44,axiom,(
    ! [ARG1,ARG2,ARG3] : natargument(f_subcollectionofwithrelationfromtypefn(ARG1,ARG2,ARG3),n_1,ARG1) )).

fof(just45,axiom,(
    ! [ARG1,ARG2,ARG3] : natargument(f_subcollectionofwithrelationfromtypefn(ARG1,ARG2,ARG3),n_2,ARG2) )).

fof(just46,axiom,(
    ! [ARG1,ARG2,ARG3] : natargument(f_subcollectionofwithrelationfromtypefn(ARG1,ARG2,ARG3),n_3,ARG3) )).

fof(just47,axiom,(
    ! [ARG1,ARG2,ARG3] : collection(f_subcollectionofwithrelationfromtypefn(ARG1,ARG2,ARG3)) )).

% Cyc NART #89985:
fof(just48,axiom,(
    ! [X] :
      ( isa(X,f_subcollectionofwithrelationfromtypefn(c_unitvectorinterval,c_directionoftranslation_throughout,c_movement_translationevent))
     => subcollectionofwithrelationfromtypefnunitvectorintervaldirectionoftranslation_throughoutmovement_translationevent(X) ) )).

fof(just49,axiom,(
    ! [X] :
      ( subcollectionofwithrelationfromtypefnunitvectorintervaldirectionoftranslation_throughoutmovement_translationevent(X)
     => isa(X,f_subcollectionofwithrelationfromtypefn(c_unitvectorinterval,c_directionoftranslation_throughout,c_movement_translationevent)) ) )).

% Cyc Constant #261842:
fof(just50,axiom,(
    ! [ARG1,INS] :
      ( tptp_8_875(ARG1,INS)
     => tptpcol_4_24578(INS) ) )).

fof(just51,axiom,(
    ! [INS,ARG2] :
      ( tptp_8_875(INS,ARG2)
     => subcollectionofwithrelationfromtypefnunitvectorintervaldirectionoftranslation_throughoutmovement_translationevent(INS) ) )).

% Cyc Constant #67447:
fof(just52,axiom,(
    ! [ARG1,ARG2,INS] :
      ( relationallexists(ARG1,ARG2,INS)
     => collection(INS) ) )).

fof(just53,axiom,(
    ! [ARG1,INS,ARG3] :
      ( relationallexists(ARG1,INS,ARG3)
     => collection(INS) ) )).

fof(just54,axiom,(
    ! [INS,ARG2,ARG3] :
      ( relationallexists(INS,ARG2,ARG3)
     => binarypredicate(INS) ) )).

% Cyc Constant #27757:
fof(just55,axiom,(
    mtvisible(c_basekb) )).

% Cyc Constant #127156:
fof(just56,axiom,(
    ! [X] :
      ( isa(X,c_transitivebinarypredicate)
     => transitivebinarypredicate(X) ) )).

fof(just57,axiom,(
    ! [X] :
      ( transitivebinarypredicate(X)
     => isa(X,c_transitivebinarypredicate) ) )).

% Cyc Constant #72115:
fof(just58,axiom,(
    ! [ARG1,INS] :
      ( isa(ARG1,INS)
     => collection(INS) ) )).

fof(just59,axiom,(
    ! [ARG1,INS] :
      ( isa(ARG1,INS)
     => collection(INS) ) )).

fof(just60,axiom,(
    ! [INS,ARG2] :
      ( isa(INS,ARG2)
     => thing(INS) ) )).

fof(just61,axiom,(
    ! [INS,ARG2] :
      ( isa(INS,ARG2)
     => thing(INS) ) )).

fof(just62,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( isa(ARG1,OLD)
        & genls(OLD,NEW) )
     => isa(ARG1,NEW) ) )).

% Cyc Constant #19550:
fof(just63,axiom,(
    ! [SPECMT,GENLMT] :
      ( ( mtvisible(SPECMT)
        & genlmt(SPECMT,GENLMT) )
     => mtvisible(GENLMT) ) )).

fof(just64,axiom,(
    ! [ARG1,INS] :
      ( genlmt(ARG1,INS)
     => microtheory(INS) ) )).

fof(just65,axiom,(
    ! [ARG1,INS] :
      ( genlmt(ARG1,INS)
     => microtheory(INS) ) )).

fof(just66,axiom,(
    ! [INS,ARG2] :
      ( genlmt(INS,ARG2)
     => microtheory(INS) ) )).

fof(just67,axiom,(
    ! [INS,ARG2] :
      ( genlmt(INS,ARG2)
     => microtheory(INS) ) )).

fof(just68,axiom,(
    ! [X,Y,Z] :
      ( ( genlmt(X,Y)
        & genlmt(Y,Z) )
     => genlmt(X,Z) ) )).

fof(just69,axiom,(
    ! [X] :
      ( microtheory(X)
     => genlmt(X,X) ) )).

fof(just70,axiom,(
    ! [X] :
      ( microtheory(X)
     => genlmt(X,X) ) )).

% Cyc Constant #104318:
fof(just71,axiom,(
    ! [ARG1,ARG2,ARG3,ARG4] : natfunction(f_relationallexistsfn(ARG1,ARG2,ARG3,ARG4),c_relationallexistsfn) )).

fof(just72,axiom,(
    ! [ARG1,ARG2,ARG3,ARG4] : natargument(f_relationallexistsfn(ARG1,ARG2,ARG3,ARG4),n_1,ARG1) )).

fof(just73,axiom,(
    ! [ARG1,ARG2,ARG3,ARG4] : natargument(f_relationallexistsfn(ARG1,ARG2,ARG3,ARG4),n_2,ARG2) )).

fof(just74,axiom,(
    ! [ARG1,ARG2,ARG3,ARG4] : natargument(f_relationallexistsfn(ARG1,ARG2,ARG3,ARG4),n_3,ARG3) )).

fof(just75,axiom,(
    ! [ARG1,ARG2,ARG3,ARG4] : natargument(f_relationallexistsfn(ARG1,ARG2,ARG3,ARG4),n_4,ARG4) )).

fof(just76,axiom,(
    ! [ARG1,ARG2,ARG3,ARG4] : thing(f_relationallexistsfn(ARG1,ARG2,ARG3,ARG4)) )).

% Cyc Constant #97397:
fof(just77,axiom,(
    ! [ARG1,INS] :
      ( resultisaarg(ARG1,INS)
     => positiveinteger(INS) ) )).

fof(just78,axiom,(
    ! [INS,ARG2] :
      ( resultisaarg(INS,ARG2)
     => function_denotational(INS) ) )).

% Cyc Constant #95028:
fof(just79,axiom,(
    mtvisible(c_universalvocabularymt) )).

fof(query27,conjecture,(
    ? [X] :
      ( mtvisible(c_tptp_spindlecollectormt)
     => ( tptp_8_875(c_tptpnsubcollectionofwithrelationfromtypefnunitvectorintervaldirectionoftranslation_throughoutmovement_translationevent_786,X)
        & tptpcol_16_31868(X) ) ) )).

%------------------------------------------------------------------------------
