%------------------------------------------------------------------------------
% File     : CSR039+1 : TPTP v6.1.0. Released v3.4.0.
% Domain   : Common Sense Reasoning
% Problem  : Autogenerated Cyc Problem CSR039+1
% Version  : Especial.
% English  :

% Refs     : [RS+]   Reagan Smith et al., The Cyc TPTP Challenge Problem
% Source   : [RS+]
% Names    :

% Status   : Theorem
% Rating   : 0.09 v6.1.0, 0.04 v6.0.0, 0.50 v5.5.0, 0.08 v5.4.0, 0.13 v5.3.0, 0.22 v5.2.0, 0.07 v5.0.0, 0.20 v4.1.0, 0.22 v4.0.1, 0.21 v4.0.0, 0.20 v3.7.0, 0.00 v3.4.0
% Syntax   : Number of formulae    :  171 (  45 unit)
%            Number of atoms       :  310 (   0 equality)
%            Maximal formula depth :    7 (   3 average)
%            Number of connectives :  141 (   2 ~  ;   0  |;  15  &)
%                                         (   0 <=>; 124 =>;   0 <=)
%                                         (   0 <~>;   0 ~|;   0 ~&)
%            Number of predicates  :   45 (   0 propositional; 1-3 arity)
%            Number of functors    :   45 (  42 constant; 0-2 arity)
%            Number of variables   :  185 (   0 singleton; 185 !;   0 ?)
%            Maximal term depth    :    4 (   1 average)
% SPC      : FOF_THM_RFO_NEQ

% Comments : Autogenerated from the OpenCyc KB. Documentation can be found at
%            http://opencyc.org/doc/#TPTP_Challenge_Problem_Set
%          : Cyc(R) Knowledge Base Copyright(C) 1995-2007 Cycorp, Inc., Austin,
%            TX, USA. All rights reserved.
%          : OpenCyc Knowledge Base Copyright(C) 2001-2007 Cycorp, Inc.,
%            Austin, TX, USA. All rights reserved.
%------------------------------------------------------------------------------
%$problem_series(cyc_scaling_1,[CSR025+1,CSR026+1,CSR027+1,CSR028+1,CSR029+1,CSR030+1,CSR031+1,CSR032+1,CSR033+1,CSR034+1,CSR035+1,CSR036+1,CSR037+1,CSR038+1,CSR039+1,CSR040+1,CSR041+1,CSR042+1,CSR043+1,CSR044+1,CSR045+1,CSR046+1,CSR047+1,CSR048+1,CSR049+1,CSR050+1,CSR051+1,CSR052+1,CSR053+1,CSR054+1,CSR055+1,CSR056+1,CSR057+1,CSR058+1,CSR059+1,CSR060+1,CSR061+1,CSR062+1,CSR063+1,CSR064+1,CSR065+1,CSR066+1,CSR067+1,CSR068+1,CSR069+1,CSR070+1,CSR071+1,CSR072+1,CSR073+1,CSR074+1])
%$static(cyc_scaling_1,include('Axioms/CSR002+0.ax'))
%----Empty file include('Axioms/CSR002+0.ax').
%------------------------------------------------------------------------------
% Cyc Assertion #592971:
fof(just1,axiom,(
    genlmt(c_cycorpproductsmt,c_basekb) )).

% Cyc Assertion #600900:
fof(just2,axiom,(
    genlmt(c_cycnounlearnermt,c_cycorpproductsmt) )).

% Cyc Assertion #1322220:
fof(just3,axiom,(
    transitivebinarypredicate(c_genlmt) )).

% Cyc Assertion #1439735:
fof(just4,axiom,(
    genlmt(f_contentmtofcdafromeventfn(f_urlreferentfn(f_urlfn(s_http_wwwpoweripodsearchinfobrown_ipodhtml)),c_translation_7),c_machinelearningspindleheadmt) )).

% Cyc Assertion #1614635:
fof(just5,axiom,(
    genlmt(c_machinelearningspindleheadmt,c_cycnounlearnermt) )).

% Cyc Assertion #1650755:
fof(just6,axiom,(
    genlmt(c_basekb,c_universalvocabularymt) )).

% Cyc Assertion #1822756:
fof(just7,axiom,(
    genls(c_tptpcol_2_2,c_tptpcol_1_1) )).

fof(just8,axiom,(
    ! [OBJ] :
      ( tptpcol_2_2(OBJ)
     => tptpcol_1_1(OBJ) ) )).

% Cyc Assertion #1863715:
fof(just9,axiom,(
    genls(c_tptpcol_3_16386,c_tptpcol_2_2) )).

fof(just10,axiom,(
    ! [OBJ] :
      ( tptpcol_3_16386(OBJ)
     => tptpcol_2_2(OBJ) ) )).

% Cyc Assertion #1863717:
fof(just11,axiom,(
    genls(c_tptpcol_4_16387,c_tptpcol_3_16386) )).

fof(just12,axiom,(
    ! [OBJ] :
      ( tptpcol_4_16387(OBJ)
     => tptpcol_3_16386(OBJ) ) )).

% Cyc Assertion #1863719:
fof(just13,axiom,(
    genls(c_tptpcol_5_16388,c_tptpcol_4_16387) )).

fof(just14,axiom,(
    ! [OBJ] :
      ( tptpcol_5_16388(OBJ)
     => tptpcol_4_16387(OBJ) ) )).

% Cyc Assertion #1868838:
fof(just15,axiom,(
    genls(c_tptpcol_6_18436,c_tptpcol_5_16388) )).

fof(just16,axiom,(
    ! [OBJ] :
      ( tptpcol_6_18436(OBJ)
     => tptpcol_5_16388(OBJ) ) )).

% Cyc Assertion #1868840:
fof(just17,axiom,(
    genls(c_tptpcol_7_18437,c_tptpcol_6_18436) )).

fof(just18,axiom,(
    ! [OBJ] :
      ( tptpcol_7_18437(OBJ)
     => tptpcol_6_18436(OBJ) ) )).

% Cyc Assertion #1868842:
fof(just19,axiom,(
    genls(c_tptpcol_8_18438,c_tptpcol_7_18437) )).

fof(just20,axiom,(
    ! [OBJ] :
      ( tptpcol_8_18438(OBJ)
     => tptpcol_7_18437(OBJ) ) )).

% Cyc Assertion #1868844:
fof(just21,axiom,(
    genls(c_tptpcol_9_18439,c_tptpcol_8_18438) )).

fof(just22,axiom,(
    ! [OBJ] :
      ( tptpcol_9_18439(OBJ)
     => tptpcol_8_18438(OBJ) ) )).

% Cyc Assertion #1869163:
fof(just23,axiom,(
    genls(c_tptpcol_10_18567,c_tptpcol_9_18439) )).

fof(just24,axiom,(
    ! [OBJ] :
      ( tptpcol_10_18567(OBJ)
     => tptpcol_9_18439(OBJ) ) )).

% Cyc Assertion #1869322:
fof(just25,axiom,(
    genls(c_tptpcol_11_18631,c_tptpcol_10_18567) )).

fof(just26,axiom,(
    ! [OBJ] :
      ( tptpcol_11_18631(OBJ)
     => tptpcol_10_18567(OBJ) ) )).

% Cyc Assertion #1869401:
fof(just27,axiom,(
    genls(c_tptpcol_12_18663,c_tptpcol_11_18631) )).

fof(just28,axiom,(
    ! [OBJ] :
      ( tptpcol_12_18663(OBJ)
     => tptpcol_11_18631(OBJ) ) )).

% Cyc Assertion #1869403:
fof(just29,axiom,(
    genls(c_tptpcol_13_18664,c_tptpcol_12_18663) )).

fof(just30,axiom,(
    ! [OBJ] :
      ( tptpcol_13_18664(OBJ)
     => tptpcol_12_18663(OBJ) ) )).

% Cyc Assertion #1986593:
fof(just31,axiom,(
    genls(c_tptpcol_2_65537,c_tptpcol_1_65536) )).

fof(just32,axiom,(
    ! [OBJ] :
      ( tptpcol_2_65537(OBJ)
     => tptpcol_1_65536(OBJ) ) )).

% Cyc Assertion #2027552:
fof(just33,axiom,(
    genls(c_tptpcol_3_81921,c_tptpcol_2_65537) )).

fof(just34,axiom,(
    ! [OBJ] :
      ( tptpcol_3_81921(OBJ)
     => tptpcol_2_65537(OBJ) ) )).

% Cyc Assertion #2048031:
fof(just35,axiom,(
    genls(c_tptpcol_4_90113,c_tptpcol_3_81921) )).

fof(just36,axiom,(
    ! [OBJ] :
      ( tptpcol_4_90113(OBJ)
     => tptpcol_3_81921(OBJ) ) )).

% Cyc Assertion #2048033:
fof(just37,axiom,(
    genls(c_tptpcol_5_90114,c_tptpcol_4_90113) )).

fof(just38,axiom,(
    ! [OBJ] :
      ( tptpcol_5_90114(OBJ)
     => tptpcol_4_90113(OBJ) ) )).

% Cyc Assertion #2053152:
fof(just39,axiom,(
    genls(c_tptpcol_6_92162,c_tptpcol_5_90114) )).

fof(just40,axiom,(
    ! [OBJ] :
      ( tptpcol_6_92162(OBJ)
     => tptpcol_5_90114(OBJ) ) )).

% Cyc Assertion #2055711:
fof(just41,axiom,(
    genls(c_tptpcol_7_93186,c_tptpcol_6_92162) )).

fof(just42,axiom,(
    ! [OBJ] :
      ( tptpcol_7_93186(OBJ)
     => tptpcol_6_92162(OBJ) ) )).

% Cyc Assertion #2056990:
fof(just43,axiom,(
    genls(c_tptpcol_8_93698,c_tptpcol_7_93186) )).

fof(just44,axiom,(
    ! [OBJ] :
      ( tptpcol_8_93698(OBJ)
     => tptpcol_7_93186(OBJ) ) )).

% Cyc Assertion #2056992:
fof(just45,axiom,(
    genls(c_tptpcol_9_93699,c_tptpcol_8_93698) )).

fof(just46,axiom,(
    ! [OBJ] :
      ( tptpcol_9_93699(OBJ)
     => tptpcol_8_93698(OBJ) ) )).

% Cyc Assertion #2056994:
fof(just47,axiom,(
    genls(c_tptpcol_10_93700,c_tptpcol_9_93699) )).

fof(just48,axiom,(
    ! [OBJ] :
      ( tptpcol_10_93700(OBJ)
     => tptpcol_9_93699(OBJ) ) )).

% Cyc Assertion #2057153:
fof(just49,axiom,(
    genls(c_tptpcol_11_93764,c_tptpcol_10_93700) )).

fof(just50,axiom,(
    ! [OBJ] :
      ( tptpcol_11_93764(OBJ)
     => tptpcol_10_93700(OBJ) ) )).

% Cyc Assertion #2057155:
fof(just51,axiom,(
    genls(c_tptpcol_12_93765,c_tptpcol_11_93764) )).

fof(just52,axiom,(
    ! [OBJ] :
      ( tptpcol_12_93765(OBJ)
     => tptpcol_11_93764(OBJ) ) )).

% Cyc Assertion #2057157:
fof(just53,axiom,(
    genls(c_tptpcol_13_93766,c_tptpcol_12_93765) )).

fof(just54,axiom,(
    ! [OBJ] :
      ( tptpcol_13_93766(OBJ)
     => tptpcol_12_93765(OBJ) ) )).

% Cyc Assertion #2057176:
fof(just55,axiom,(
    genls(c_tptpcol_14_93774,c_tptpcol_13_93766) )).

fof(just56,axiom,(
    ! [OBJ] :
      ( tptpcol_14_93774(OBJ)
     => tptpcol_13_93766(OBJ) ) )).

% Cyc Assertion #2057178:
fof(just57,axiom,(
    genls(c_tptpcol_15_93775,c_tptpcol_14_93774) )).

fof(just58,axiom,(
    ! [OBJ] :
      ( tptpcol_15_93775(OBJ)
     => tptpcol_14_93774(OBJ) ) )).

% Cyc Assertion #2150427:
fof(just59,axiom,(
    disjointwith(c_tptpcol_1_1,c_tptpcol_1_65536) )).

fof(just60,axiom,(
    ! [OBJ] :
      ~ ( tptpcol_1_1(OBJ)
        & tptpcol_1_65536(OBJ) ) )).

% Cyc Assertion #398814:
fof(just61,axiom,(
    ! [OBJ,COL1,COL2] :
      ~ ( isa(OBJ,COL1)
        & isa(OBJ,COL2)
        & disjointwith(COL1,COL2) ) )).

% Cyc Assertion #831913:
fof(just62,axiom,(
    ! [SPECPRED,PRED,GENLPRED] :
      ( ( genlinverse(SPECPRED,PRED)
        & genlinverse(PRED,GENLPRED) )
     => genlpreds(SPECPRED,GENLPRED) ) )).

% Cyc Constant #40273:
fof(just63,axiom,(
    ! [ARG1,INS] :
      ( genlpreds(ARG1,INS)
     => predicate(INS) ) )).

fof(just64,axiom,(
    ! [ARG1,INS] :
      ( genlpreds(ARG1,INS)
     => predicate(INS) ) )).

fof(just65,axiom,(
    ! [INS,ARG2] :
      ( genlpreds(INS,ARG2)
     => predicate(INS) ) )).

fof(just66,axiom,(
    ! [INS,ARG2] :
      ( genlpreds(INS,ARG2)
     => predicate(INS) ) )).

fof(just67,axiom,(
    ! [X,Y,Z] :
      ( ( genlpreds(X,Y)
        & genlpreds(Y,Z) )
     => genlpreds(X,Z) ) )).

fof(just68,axiom,(
    ! [X] :
      ( predicate(X)
     => genlpreds(X,X) ) )).

fof(just69,axiom,(
    ! [X] :
      ( predicate(X)
     => genlpreds(X,X) ) )).

% Cyc Constant #45259:
fof(just70,axiom,(
    ! [ARG1,INS] :
      ( genlinverse(ARG1,INS)
     => binarypredicate(INS) ) )).

fof(just71,axiom,(
    ! [INS,ARG2] :
      ( genlinverse(INS,ARG2)
     => binarypredicate(INS) ) )).

fof(just72,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( genlinverse(OLD,ARG2)
        & genlpreds(NEW,OLD) )
     => genlinverse(NEW,ARG2) ) )).

fof(just73,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( genlinverse(ARG1,OLD)
        & genlpreds(OLD,NEW) )
     => genlinverse(ARG1,NEW) ) )).

% Cyc Constant #78648:
fof(just74,axiom,(
    ! [ARG1,INS] :
      ( disjointwith(ARG1,INS)
     => collection(INS) ) )).

fof(just75,axiom,(
    ! [INS,ARG2] :
      ( disjointwith(INS,ARG2)
     => collection(INS) ) )).

fof(just76,axiom,(
    ! [X,Y] :
      ( disjointwith(X,Y)
     => disjointwith(Y,X) ) )).

fof(just77,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( disjointwith(ARG1,OLD)
        & genls(NEW,OLD) )
     => disjointwith(ARG1,NEW) ) )).

fof(just78,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( disjointwith(OLD,ARG2)
        & genls(NEW,OLD) )
     => disjointwith(NEW,ARG2) ) )).

% Cyc Constant #223372:
fof(just79,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_15_93775)
     => tptpcol_15_93775(X) ) )).

fof(just80,axiom,(
    ! [X] :
      ( tptpcol_15_93775(X)
     => isa(X,c_tptpcol_15_93775) ) )).

% Cyc Constant #223371:
fof(just81,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_14_93774)
     => tptpcol_14_93774(X) ) )).

fof(just82,axiom,(
    ! [X] :
      ( tptpcol_14_93774(X)
     => isa(X,c_tptpcol_14_93774) ) )).

% Cyc Constant #223363:
fof(just83,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_13_93766)
     => tptpcol_13_93766(X) ) )).

fof(just84,axiom,(
    ! [X] :
      ( tptpcol_13_93766(X)
     => isa(X,c_tptpcol_13_93766) ) )).

% Cyc Constant #223362:
fof(just85,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_12_93765)
     => tptpcol_12_93765(X) ) )).

fof(just86,axiom,(
    ! [X] :
      ( tptpcol_12_93765(X)
     => isa(X,c_tptpcol_12_93765) ) )).

% Cyc Constant #223361:
fof(just87,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_11_93764)
     => tptpcol_11_93764(X) ) )).

fof(just88,axiom,(
    ! [X] :
      ( tptpcol_11_93764(X)
     => isa(X,c_tptpcol_11_93764) ) )).

% Cyc Constant #223297:
fof(just89,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_10_93700)
     => tptpcol_10_93700(X) ) )).

fof(just90,axiom,(
    ! [X] :
      ( tptpcol_10_93700(X)
     => isa(X,c_tptpcol_10_93700) ) )).

% Cyc Constant #223296:
fof(just91,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_9_93699)
     => tptpcol_9_93699(X) ) )).

fof(just92,axiom,(
    ! [X] :
      ( tptpcol_9_93699(X)
     => isa(X,c_tptpcol_9_93699) ) )).

% Cyc Constant #223295:
fof(just93,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_8_93698)
     => tptpcol_8_93698(X) ) )).

fof(just94,axiom,(
    ! [X] :
      ( tptpcol_8_93698(X)
     => isa(X,c_tptpcol_8_93698) ) )).

% Cyc Constant #222783:
fof(just95,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_7_93186)
     => tptpcol_7_93186(X) ) )).

fof(just96,axiom,(
    ! [X] :
      ( tptpcol_7_93186(X)
     => isa(X,c_tptpcol_7_93186) ) )).

% Cyc Constant #221759:
fof(just97,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_6_92162)
     => tptpcol_6_92162(X) ) )).

fof(just98,axiom,(
    ! [X] :
      ( tptpcol_6_92162(X)
     => isa(X,c_tptpcol_6_92162) ) )).

% Cyc Constant #219711:
fof(just99,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_5_90114)
     => tptpcol_5_90114(X) ) )).

fof(just100,axiom,(
    ! [X] :
      ( tptpcol_5_90114(X)
     => isa(X,c_tptpcol_5_90114) ) )).

% Cyc Constant #219710:
fof(just101,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_4_90113)
     => tptpcol_4_90113(X) ) )).

fof(just102,axiom,(
    ! [X] :
      ( tptpcol_4_90113(X)
     => isa(X,c_tptpcol_4_90113) ) )).

% Cyc Constant #211518:
fof(just103,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_3_81921)
     => tptpcol_3_81921(X) ) )).

fof(just104,axiom,(
    ! [X] :
      ( tptpcol_3_81921(X)
     => isa(X,c_tptpcol_3_81921) ) )).

% Cyc Constant #195133:
fof(just105,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_1_65536)
     => tptpcol_1_65536(X) ) )).

fof(just106,axiom,(
    ! [X] :
      ( tptpcol_1_65536(X)
     => isa(X,c_tptpcol_1_65536) ) )).

% Cyc Constant #195134:
fof(just107,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_2_65537)
     => tptpcol_2_65537(X) ) )).

fof(just108,axiom,(
    ! [X] :
      ( tptpcol_2_65537(X)
     => isa(X,c_tptpcol_2_65537) ) )).

% Cyc Constant #148261:
fof(just109,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_13_18664)
     => tptpcol_13_18664(X) ) )).

fof(just110,axiom,(
    ! [X] :
      ( tptpcol_13_18664(X)
     => isa(X,c_tptpcol_13_18664) ) )).

% Cyc Constant #148260:
fof(just111,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_12_18663)
     => tptpcol_12_18663(X) ) )).

fof(just112,axiom,(
    ! [X] :
      ( tptpcol_12_18663(X)
     => isa(X,c_tptpcol_12_18663) ) )).

% Cyc Constant #148228:
fof(just113,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_11_18631)
     => tptpcol_11_18631(X) ) )).

fof(just114,axiom,(
    ! [X] :
      ( tptpcol_11_18631(X)
     => isa(X,c_tptpcol_11_18631) ) )).

% Cyc Constant #148164:
fof(just115,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_10_18567)
     => tptpcol_10_18567(X) ) )).

fof(just116,axiom,(
    ! [X] :
      ( tptpcol_10_18567(X)
     => isa(X,c_tptpcol_10_18567) ) )).

% Cyc Constant #148036:
fof(just117,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_9_18439)
     => tptpcol_9_18439(X) ) )).

fof(just118,axiom,(
    ! [X] :
      ( tptpcol_9_18439(X)
     => isa(X,c_tptpcol_9_18439) ) )).

% Cyc Constant #148035:
fof(just119,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_8_18438)
     => tptpcol_8_18438(X) ) )).

fof(just120,axiom,(
    ! [X] :
      ( tptpcol_8_18438(X)
     => isa(X,c_tptpcol_8_18438) ) )).

% Cyc Constant #148034:
fof(just121,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_7_18437)
     => tptpcol_7_18437(X) ) )).

fof(just122,axiom,(
    ! [X] :
      ( tptpcol_7_18437(X)
     => isa(X,c_tptpcol_7_18437) ) )).

% Cyc Constant #148033:
fof(just123,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_6_18436)
     => tptpcol_6_18436(X) ) )).

fof(just124,axiom,(
    ! [X] :
      ( tptpcol_6_18436(X)
     => isa(X,c_tptpcol_6_18436) ) )).

% Cyc Constant #145985:
fof(just125,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_5_16388)
     => tptpcol_5_16388(X) ) )).

fof(just126,axiom,(
    ! [X] :
      ( tptpcol_5_16388(X)
     => isa(X,c_tptpcol_5_16388) ) )).

% Cyc Constant #145984:
fof(just127,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_4_16387)
     => tptpcol_4_16387(X) ) )).

fof(just128,axiom,(
    ! [X] :
      ( tptpcol_4_16387(X)
     => isa(X,c_tptpcol_4_16387) ) )).

% Cyc Constant #145983:
fof(just129,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_3_16386)
     => tptpcol_3_16386(X) ) )).

fof(just130,axiom,(
    ! [X] :
      ( tptpcol_3_16386(X)
     => isa(X,c_tptpcol_3_16386) ) )).

% Cyc Constant #129598:
fof(just131,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_1_1)
     => tptpcol_1_1(X) ) )).

fof(just132,axiom,(
    ! [X] :
      ( tptpcol_1_1(X)
     => isa(X,c_tptpcol_1_1) ) )).

% Cyc Constant #129599:
fof(just133,axiom,(
    ! [X] :
      ( isa(X,c_tptpcol_2_2)
     => tptpcol_2_2(X) ) )).

fof(just134,axiom,(
    ! [X] :
      ( tptpcol_2_2(X)
     => isa(X,c_tptpcol_2_2) ) )).

% Cyc Constant #0:
fof(just135,axiom,(
    ! [ARG1,INS] :
      ( genls(ARG1,INS)
     => collection(INS) ) )).

fof(just136,axiom,(
    ! [ARG1,INS] :
      ( genls(ARG1,INS)
     => collection(INS) ) )).

fof(just137,axiom,(
    ! [INS,ARG2] :
      ( genls(INS,ARG2)
     => collection(INS) ) )).

fof(just138,axiom,(
    ! [INS,ARG2] :
      ( genls(INS,ARG2)
     => collection(INS) ) )).

fof(just139,axiom,(
    ! [X,Y,Z] :
      ( ( genls(X,Y)
        & genls(Y,Z) )
     => genls(X,Z) ) )).

fof(just140,axiom,(
    ! [X] :
      ( collection(X)
     => genls(X,X) ) )).

fof(just141,axiom,(
    ! [X] :
      ( collection(X)
     => genls(X,X) ) )).

fof(just142,axiom,(
    ! [OLD,ARG2,NEW] :
      ( ( genls(OLD,ARG2)
        & genls(NEW,OLD) )
     => genls(NEW,ARG2) ) )).

fof(just143,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( genls(ARG1,OLD)
        & genls(OLD,NEW) )
     => genls(ARG1,NEW) ) )).

% Cyc Constant #129091:
fof(just144,axiom,(
    ! [ARG1] : natfunction(f_urlfn(ARG1),c_urlfn) )).

fof(just145,axiom,(
    ! [ARG1] : natargument(f_urlfn(ARG1),n_1,ARG1) )).

fof(just146,axiom,(
    ! [ARG1] : uniformresourcelocator(f_urlfn(ARG1)) )).

% Cyc Constant #78971:
fof(just147,axiom,(
    ! [ARG1] : natfunction(f_urlreferentfn(ARG1),c_urlreferentfn) )).

fof(just148,axiom,(
    ! [ARG1] : natargument(f_urlreferentfn(ARG1),n_1,ARG1) )).

fof(just149,axiom,(
    ! [ARG1] : computerdataartifact(f_urlreferentfn(ARG1)) )).

% Cyc Constant #71728:
fof(just150,axiom,(
    ! [ARG1,ARG2] : natfunction(f_contentmtofcdafromeventfn(ARG1,ARG2),c_contentmtofcdafromeventfn) )).

fof(just151,axiom,(
    ! [ARG1,ARG2] : natargument(f_contentmtofcdafromeventfn(ARG1,ARG2),n_1,ARG1) )).

fof(just152,axiom,(
    ! [ARG1,ARG2] : natargument(f_contentmtofcdafromeventfn(ARG1,ARG2),n_2,ARG2) )).

fof(just153,axiom,(
    ! [ARG1,ARG2] : microtheory(f_contentmtofcdafromeventfn(ARG1,ARG2)) )).

% Cyc Constant #127156:
fof(just154,axiom,(
    ! [X] :
      ( isa(X,c_transitivebinarypredicate)
     => transitivebinarypredicate(X) ) )).

fof(just155,axiom,(
    ! [X] :
      ( transitivebinarypredicate(X)
     => isa(X,c_transitivebinarypredicate) ) )).

% Cyc Constant #72115:
fof(just156,axiom,(
    ! [ARG1,INS] :
      ( isa(ARG1,INS)
     => collection(INS) ) )).

fof(just157,axiom,(
    ! [ARG1,INS] :
      ( isa(ARG1,INS)
     => collection(INS) ) )).

fof(just158,axiom,(
    ! [INS,ARG2] :
      ( isa(INS,ARG2)
     => thing(INS) ) )).

fof(just159,axiom,(
    ! [INS,ARG2] :
      ( isa(INS,ARG2)
     => thing(INS) ) )).

fof(just160,axiom,(
    ! [ARG1,OLD,NEW] :
      ( ( isa(ARG1,OLD)
        & genls(OLD,NEW) )
     => isa(ARG1,NEW) ) )).

% Cyc Constant #95028:
fof(just161,axiom,(
    mtvisible(c_universalvocabularymt) )).

% Cyc Constant #19550:
fof(just162,axiom,(
    ! [SPECMT,GENLMT] :
      ( ( mtvisible(SPECMT)
        & genlmt(SPECMT,GENLMT) )
     => mtvisible(GENLMT) ) )).

fof(just163,axiom,(
    ! [ARG1,INS] :
      ( genlmt(ARG1,INS)
     => microtheory(INS) ) )).

fof(just164,axiom,(
    ! [ARG1,INS] :
      ( genlmt(ARG1,INS)
     => microtheory(INS) ) )).

fof(just165,axiom,(
    ! [INS,ARG2] :
      ( genlmt(INS,ARG2)
     => microtheory(INS) ) )).

fof(just166,axiom,(
    ! [INS,ARG2] :
      ( genlmt(INS,ARG2)
     => microtheory(INS) ) )).

fof(just167,axiom,(
    ! [X,Y,Z] :
      ( ( genlmt(X,Y)
        & genlmt(Y,Z) )
     => genlmt(X,Z) ) )).

fof(just168,axiom,(
    ! [X] :
      ( microtheory(X)
     => genlmt(X,X) ) )).

fof(just169,axiom,(
    ! [X] :
      ( microtheory(X)
     => genlmt(X,X) ) )).

% Cyc Constant #27757:
fof(just170,axiom,(
    mtvisible(c_basekb) )).

fof(query39,conjecture,
    ( mtvisible(f_contentmtofcdafromeventfn(f_urlreferentfn(f_urlfn(s_http_wwwpoweripodsearchinfobrown_ipodhtml)),c_translation_7))
   => disjointwith(c_tptpcol_15_93775,c_tptpcol_13_18664) )).

%------------------------------------------------------------------------------
