%--------------------------------------------------------------------------
% File     : NLP001+1 : TPTP v6.1.0. Released v2.4.0.
% Domain   : Natural Language Processing
% Problem  : "The old dirty white Chevy" problem
% Version  : [Bos00] axioms.
% English  : A problem generated by the DORIS [Bos00] system when parsing
%            the statement "The old dirty white Chevy barrels down a lonely
%            street in Hollywood".

% Refs     : [Bos00] Bos (2000), DORIS: Discourse Oriented Representation an
%            [Bau99] Baumgartner (1999), FTP'2000 - Problem Sets
% Source   : [Bau99]
% Names    :

% Status   : Theorem
% Rating   : 0.00 v5.3.0, 0.09 v5.2.0, 0.00 v4.1.0, 0.06 v4.0.1, 0.11 v4.0.0, 0.10 v3.7.0, 0.00 v3.3.0, 0.11 v3.2.0, 0.22 v3.1.0, 0.50 v2.7.0, 0.33 v2.6.0, 0.00 v2.4.0
% Syntax   : Number of formulae    :    1 (   0 unit)
%            Number of atoms       :   56 (   0 equality)
%            Maximal formula depth :   20 (  20 average)
%            Number of connectives :   55 (   0 ~  ;   0  |;  53  &)
%                                         (   0 <=>;   2 =>;   0 <=)
%                                         (   0 <~>;   0 ~|;   0 ~&)
%            Number of predicates  :   14 (   0 propositional; 1-2 arity)
%            Number of functors    :    0 (   0 constant; --- arity)
%            Number of variables   :   16 (   0 singleton;   0 !;  16 ?)
%            Maximal term depth    :    1 (   1 average)
% SPC      : FOF_THM_EPR

% Comments :
%--------------------------------------------------------------------------
fof(co1,conjecture,
    ( ( ? [U,V,W,X] :
          ( hollywood(U)
          & city(U)
          & event(V)
          & street(W)
          & way(W)
          & lonely(W)
          & chevy(X)
          & car(X)
          & white(X)
          & dirty(X)
          & old(X)
          & barrel(V,X)
          & down(V,W)
          & in(V,U) )
     => ? [Y,Z,X1,X2] :
          ( hollywood(Y)
          & city(Y)
          & event(Z)
          & chevy(X1)
          & car(X1)
          & white(X1)
          & dirty(X1)
          & old(X1)
          & street(X2)
          & way(X2)
          & lonely(X2)
          & barrel(Z,X1)
          & down(Z,X2)
          & in(Z,Y) ) )
    & ( ? [X3,X4,X5,X6] :
          ( hollywood(X3)
          & city(X3)
          & event(X4)
          & chevy(X5)
          & car(X5)
          & white(X5)
          & dirty(X5)
          & old(X5)
          & street(X6)
          & way(X6)
          & lonely(X6)
          & barrel(X4,X5)
          & down(X4,X6)
          & in(X4,X3) )
     => ? [X7,X8,X9,X10] :
          ( hollywood(X7)
          & city(X7)
          & event(X8)
          & street(X9)
          & way(X9)
          & lonely(X9)
          & chevy(X10)
          & car(X10)
          & white(X10)
          & dirty(X10)
          & old(X10)
          & barrel(X8,X10)
          & down(X8,X9)
          & in(X8,X7) ) ) )).

%--------------------------------------------------------------------------
