%------------------------------------------------------------------------------
% File     : NUM531+1 : TPTP v6.1.0. Released v4.0.0.
% Domain   : Number Theory
% Problem  : Ramsey's Infinite Theorem 01, 00 expansion
% Version  : Especial.
% English  :

% Refs     : [VLP07] Verchinine et al. (2007), System for Automated Deduction
%          : [Pas08] Paskevich (2008), Email to G. Sutcliffe
% Source   : [Pas08]
% Names    : ramsey_01.00 [Pas08]

% Status   : Theorem
% Rating   : 0.04 v6.1.0, 0.07 v6.0.0, 0.00 v5.4.0, 0.07 v5.3.0, 0.11 v5.2.0, 0.05 v5.1.0, 0.14 v5.0.0, 0.21 v4.1.0, 0.26 v4.0.1, 0.61 v4.0.0
% Syntax   : Number of formulae    :    9 (   1 unit)
%            Number of atoms       :   23 (   2 equality)
%            Maximal formula depth :    6 (   4 average)
%            Number of connectives :   17 (   3 ~  ;   0  |;   3  &)
%                                         (   1 <=>;  10 =>;   0 <=)
%                                         (   0 <~>;   0 ~|;   0 ~&)
%            Number of predicates  :    6 (   0 propositional; 1-2 arity)
%            Number of functors    :    1 (   1 constant; 0-0 arity)
%            Number of variables   :   10 (   0 singleton;   9 !;   1 ?)
%            Maximal term depth    :    1 (   1 average)
% SPC      : FOF_THM_RFO_SEQ

% Comments : Problem generated by the SAD system [VLP07]
%------------------------------------------------------------------------------
fof(mSetSort,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => $true ) )).

fof(mElmSort,axiom,(
    ! [W0] :
      ( aElement0(W0)
     => $true ) )).

fof(mEOfElem,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => ! [W1] :
          ( aElementOf0(W1,W0)
         => aElement0(W1) ) ) )).

fof(mFinRel,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => ( isFinite0(W0)
       => $true ) ) )).

fof(mDefEmp,definition,(
    ! [W0] :
      ( W0 = slcrc0
    <=> ( aSet0(W0)
        & ~ ( ? [W1] : aElementOf0(W1,W0) ) ) ) )).

fof(mEmpFin,axiom,(
    isFinite0(slcrc0) )).

fof(mCntRel,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => ( isCountable0(W0)
       => $true ) ) )).

fof(mCountNFin,axiom,(
    ! [W0] :
      ( ( aSet0(W0)
        & isCountable0(W0) )
     => ~ isFinite0(W0) ) )).

fof(m__,conjecture,(
    ! [W0] :
      ( ( aSet0(W0)
        & isCountable0(W0) )
     => W0 != slcrc0 ) )).

%------------------------------------------------------------------------------
