%------------------------------------------------------------------------------
% File     : NUM535+2 : TPTP v6.1.0. Released v4.0.0.
% Domain   : Number Theory
% Problem  : Ramsey's Infinite Theorem 04_01, 01 expansion
% Version  : Especial.
% English  :

% Refs     : [VLP07] Verchinine et al. (2007), System for Automated Deduction
%          : [Pas08] Paskevich (2008), Email to G. Sutcliffe
% Source   : [Pas08]
% Names    : ramsey_04_01.01 [Pas08]

% Status   : Theorem
% Rating   : 0.20 v6.1.0, 0.30 v6.0.0, 0.17 v5.5.0, 0.30 v5.4.0, 0.36 v5.3.0, 0.37 v5.2.0, 0.30 v5.1.0, 0.43 v5.0.0, 0.50 v4.1.0, 0.57 v4.0.1, 0.78 v4.0.0
% Syntax   : Number of formulae    :   19 (   3 unit)
%            Number of atoms       :   89 (  11 equality)
%            Maximal formula depth :   12 (   5 average)
%            Number of connectives :   76 (   6 ~  ;   5  |;  28  &)
%                                         (  10 <=>;  27 =>;   0 <=)
%                                         (   0 <~>;   0 ~|;   0 ~&)
%            Number of predicates  :    7 (   0 propositional; 1-2 arity)
%            Number of functors    :    5 (   3 constant; 0-2 arity)
%            Number of variables   :   35 (   0 singleton;  34 !;   1 ?)
%            Maximal term depth    :    3 (   1 average)
% SPC      : FOF_THM_RFO_SEQ

% Comments : Problem generated by the SAD system [VLP07]
%------------------------------------------------------------------------------
fof(mSetSort,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => $true ) )).

fof(mElmSort,axiom,(
    ! [W0] :
      ( aElement0(W0)
     => $true ) )).

fof(mEOfElem,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => ! [W1] :
          ( aElementOf0(W1,W0)
         => aElement0(W1) ) ) )).

fof(mFinRel,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => ( isFinite0(W0)
       => $true ) ) )).

fof(mDefEmp,definition,(
    ! [W0] :
      ( W0 = slcrc0
    <=> ( aSet0(W0)
        & ~ ? [W1] : aElementOf0(W1,W0) ) ) )).

fof(mEmpFin,axiom,(
    isFinite0(slcrc0) )).

fof(mCntRel,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => ( isCountable0(W0)
       => $true ) ) )).

fof(mCountNFin,axiom,(
    ! [W0] :
      ( ( aSet0(W0)
        & isCountable0(W0) )
     => ~ isFinite0(W0) ) )).

fof(mCountNFin_01,axiom,(
    ! [W0] :
      ( ( aSet0(W0)
        & isCountable0(W0) )
     => W0 != slcrc0 ) )).

fof(mDefSub,definition,(
    ! [W0] :
      ( aSet0(W0)
     => ! [W1] :
          ( aSubsetOf0(W1,W0)
        <=> ( aSet0(W1)
            & ! [W2] :
                ( aElementOf0(W2,W1)
               => aElementOf0(W2,W0) ) ) ) ) )).

fof(mSubFSet,axiom,(
    ! [W0] :
      ( ( aSet0(W0)
        & isFinite0(W0) )
     => ! [W1] :
          ( aSubsetOf0(W1,W0)
         => isFinite0(W1) ) ) )).

fof(mSubRefl,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => aSubsetOf0(W0,W0) ) )).

fof(mSubASymm,axiom,(
    ! [W0,W1] :
      ( ( aSet0(W0)
        & aSet0(W1) )
     => ( ( aSubsetOf0(W0,W1)
          & aSubsetOf0(W1,W0) )
       => W0 = W1 ) ) )).

fof(mSubTrans,axiom,(
    ! [W0,W1,W2] :
      ( ( aSet0(W0)
        & aSet0(W1)
        & aSet0(W2) )
     => ( ( aSubsetOf0(W0,W1)
          & aSubsetOf0(W1,W2) )
       => aSubsetOf0(W0,W2) ) ) )).

fof(mDefCons,definition,(
    ! [W0,W1] :
      ( ( aSet0(W0)
        & aElement0(W1) )
     => ! [W2] :
          ( W2 = sdtpldt0(W0,W1)
        <=> ( aSet0(W2)
            & ! [W3] :
                ( aElementOf0(W3,W2)
              <=> ( aElement0(W3)
                  & ( aElementOf0(W3,W0)
                    | W3 = W1 ) ) ) ) ) ) )).

fof(mDefDiff,definition,(
    ! [W0,W1] :
      ( ( aSet0(W0)
        & aElement0(W1) )
     => ! [W2] :
          ( W2 = sdtmndt0(W0,W1)
        <=> ( aSet0(W2)
            & ! [W3] :
                ( aElementOf0(W3,W2)
              <=> ( aElement0(W3)
                  & aElementOf0(W3,W0)
                  & W3 != W1 ) ) ) ) ) )).

fof(m__617,hypothesis,(
    aSet0(xS) )).

fof(m__617_02,hypothesis,(
    aElementOf0(xx,xS) )).

fof(m__,conjecture,
    ( ( ( aSet0(sdtmndt0(xS,xx))
        & ! [W0] :
            ( aElementOf0(W0,sdtmndt0(xS,xx))
          <=> ( aElement0(W0)
              & aElementOf0(W0,xS)
              & W0 != xx ) ) )
     => ( ( aSet0(sdtpldt0(sdtmndt0(xS,xx),xx))
          & ! [W0] :
              ( aElementOf0(W0,sdtpldt0(sdtmndt0(xS,xx),xx))
            <=> ( aElement0(W0)
                & ( aElementOf0(W0,sdtmndt0(xS,xx))
                  | W0 = xx ) ) ) )
       => ( ! [W0] :
              ( aElementOf0(W0,xS)
             => aElementOf0(W0,sdtpldt0(sdtmndt0(xS,xx),xx)) )
          | aSubsetOf0(xS,sdtpldt0(sdtmndt0(xS,xx),xx)) ) ) )
    & ( ( aSet0(sdtmndt0(xS,xx))
        & ! [W0] :
            ( aElementOf0(W0,sdtmndt0(xS,xx))
          <=> ( aElement0(W0)
              & aElementOf0(W0,xS)
              & W0 != xx ) ) )
     => ( ( aSet0(sdtpldt0(sdtmndt0(xS,xx),xx))
          & ! [W0] :
              ( aElementOf0(W0,sdtpldt0(sdtmndt0(xS,xx),xx))
            <=> ( aElement0(W0)
                & ( aElementOf0(W0,sdtmndt0(xS,xx))
                  | W0 = xx ) ) ) )
       => ( ! [W0] :
              ( aElementOf0(W0,sdtpldt0(sdtmndt0(xS,xx),xx))
             => aElementOf0(W0,xS) )
          | aSubsetOf0(sdtpldt0(sdtmndt0(xS,xx),xx),xS) ) ) ) )).

%------------------------------------------------------------------------------
