%------------------------------------------------------------------------------
% File     : NUM560+2 : TPTP v6.1.0. Released v4.0.0.
% Domain   : Number Theory
% Problem  : Ramsey's Infinite Theorem 13, 01 expansion
% Version  : Especial.
% English  :

% Refs     : [VLP07] Verchinine et al. (2007), System for Automated Deduction
%          : [Pas08] Paskevich (2008), Email to G. Sutcliffe
% Source   : [Pas08]
% Names    : ramsey_13.01 [Pas08]

% Status   : Theorem
% Rating   : 0.08 v6.1.0, 0.10 v6.0.0, 0.09 v5.5.0, 0.11 v5.4.0, 0.18 v5.3.0, 0.22 v5.2.0, 0.15 v5.1.0, 0.24 v5.0.0, 0.29 v4.1.0, 0.39 v4.0.1, 0.70 v4.0.0
% Syntax   : Number of formulae    :   68 (   3 unit)
%            Number of atoms       :  265 (  41 equality)
%            Maximal formula depth :   12 (   5 average)
%            Number of connectives :  215 (  18 ~  ;   5  |;  76  &)
%                                         (  20 <=>;  96 =>;   0 <=)
%                                         (   0 <~>;   0 ~|;   0 ~&)
%            Number of predicates  :   10 (   0 propositional; 1-2 arity)
%            Number of functors    :   16 (   5 constant; 0-2 arity)
%            Number of variables   :  123 (   0 singleton; 118 !;   5 ?)
%            Maximal term depth    :    4 (   1 average)
% SPC      : FOF_THM_RFO_SEQ

% Comments : Problem generated by the SAD system [VLP07]
%------------------------------------------------------------------------------
fof(mSetSort,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => $true ) )).

fof(mElmSort,axiom,(
    ! [W0] :
      ( aElement0(W0)
     => $true ) )).

fof(mEOfElem,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => ! [W1] :
          ( aElementOf0(W1,W0)
         => aElement0(W1) ) ) )).

fof(mFinRel,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => ( isFinite0(W0)
       => $true ) ) )).

fof(mDefEmp,definition,(
    ! [W0] :
      ( W0 = slcrc0
    <=> ( aSet0(W0)
        & ~ ? [W1] : aElementOf0(W1,W0) ) ) )).

fof(mEmpFin,axiom,(
    isFinite0(slcrc0) )).

fof(mCntRel,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => ( isCountable0(W0)
       => $true ) ) )).

fof(mCountNFin,axiom,(
    ! [W0] :
      ( ( aSet0(W0)
        & isCountable0(W0) )
     => ~ isFinite0(W0) ) )).

fof(mCountNFin_01,axiom,(
    ! [W0] :
      ( ( aSet0(W0)
        & isCountable0(W0) )
     => W0 != slcrc0 ) )).

fof(mDefSub,definition,(
    ! [W0] :
      ( aSet0(W0)
     => ! [W1] :
          ( aSubsetOf0(W1,W0)
        <=> ( aSet0(W1)
            & ! [W2] :
                ( aElementOf0(W2,W1)
               => aElementOf0(W2,W0) ) ) ) ) )).

fof(mSubFSet,axiom,(
    ! [W0] :
      ( ( aSet0(W0)
        & isFinite0(W0) )
     => ! [W1] :
          ( aSubsetOf0(W1,W0)
         => isFinite0(W1) ) ) )).

fof(mSubRefl,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => aSubsetOf0(W0,W0) ) )).

fof(mSubASymm,axiom,(
    ! [W0,W1] :
      ( ( aSet0(W0)
        & aSet0(W1) )
     => ( ( aSubsetOf0(W0,W1)
          & aSubsetOf0(W1,W0) )
       => W0 = W1 ) ) )).

fof(mSubTrans,axiom,(
    ! [W0,W1,W2] :
      ( ( aSet0(W0)
        & aSet0(W1)
        & aSet0(W2) )
     => ( ( aSubsetOf0(W0,W1)
          & aSubsetOf0(W1,W2) )
       => aSubsetOf0(W0,W2) ) ) )).

fof(mDefCons,definition,(
    ! [W0,W1] :
      ( ( aSet0(W0)
        & aElement0(W1) )
     => ! [W2] :
          ( W2 = sdtpldt0(W0,W1)
        <=> ( aSet0(W2)
            & ! [W3] :
                ( aElementOf0(W3,W2)
              <=> ( aElement0(W3)
                  & ( aElementOf0(W3,W0)
                    | W3 = W1 ) ) ) ) ) ) )).

fof(mDefDiff,definition,(
    ! [W0,W1] :
      ( ( aSet0(W0)
        & aElement0(W1) )
     => ! [W2] :
          ( W2 = sdtmndt0(W0,W1)
        <=> ( aSet0(W2)
            & ! [W3] :
                ( aElementOf0(W3,W2)
              <=> ( aElement0(W3)
                  & aElementOf0(W3,W0)
                  & W3 != W1 ) ) ) ) ) )).

fof(mConsDiff,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => ! [W1] :
          ( aElementOf0(W1,W0)
         => sdtpldt0(sdtmndt0(W0,W1),W1) = W0 ) ) )).

fof(mDiffCons,axiom,(
    ! [W0,W1] :
      ( ( aElement0(W0)
        & aSet0(W1) )
     => ( ~ aElementOf0(W0,W1)
       => sdtmndt0(sdtpldt0(W1,W0),W0) = W1 ) ) )).

fof(mCConsSet,axiom,(
    ! [W0] :
      ( aElement0(W0)
     => ! [W1] :
          ( ( aSet0(W1)
            & isCountable0(W1) )
         => isCountable0(sdtpldt0(W1,W0)) ) ) )).

fof(mCDiffSet,axiom,(
    ! [W0] :
      ( aElement0(W0)
     => ! [W1] :
          ( ( aSet0(W1)
            & isCountable0(W1) )
         => isCountable0(sdtmndt0(W1,W0)) ) ) )).

fof(mFConsSet,axiom,(
    ! [W0] :
      ( aElement0(W0)
     => ! [W1] :
          ( ( aSet0(W1)
            & isFinite0(W1) )
         => isFinite0(sdtpldt0(W1,W0)) ) ) )).

fof(mFDiffSet,axiom,(
    ! [W0] :
      ( aElement0(W0)
     => ! [W1] :
          ( ( aSet0(W1)
            & isFinite0(W1) )
         => isFinite0(sdtmndt0(W1,W0)) ) ) )).

fof(mNATSet,axiom,
    ( aSet0(szNzAzT0)
    & isCountable0(szNzAzT0) )).

fof(mZeroNum,axiom,(
    aElementOf0(sz00,szNzAzT0) )).

fof(mSuccNum,axiom,(
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => ( aElementOf0(szszuzczcdt0(W0),szNzAzT0)
        & szszuzczcdt0(W0) != sz00 ) ) )).

fof(mSuccEquSucc,axiom,(
    ! [W0,W1] :
      ( ( aElementOf0(W0,szNzAzT0)
        & aElementOf0(W1,szNzAzT0) )
     => ( szszuzczcdt0(W0) = szszuzczcdt0(W1)
       => W0 = W1 ) ) )).

fof(mNatExtra,axiom,(
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => ( W0 = sz00
        | ? [W1] :
            ( aElementOf0(W1,szNzAzT0)
            & W0 = szszuzczcdt0(W1) ) ) ) )).

fof(mNatNSucc,axiom,(
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => W0 != szszuzczcdt0(W0) ) )).

fof(mLessRel,axiom,(
    ! [W0,W1] :
      ( ( aElementOf0(W0,szNzAzT0)
        & aElementOf0(W1,szNzAzT0) )
     => ( sdtlseqdt0(W0,W1)
       => $true ) ) )).

fof(mZeroLess,axiom,(
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => sdtlseqdt0(sz00,W0) ) )).

fof(mNoScLessZr,axiom,(
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => ~ sdtlseqdt0(szszuzczcdt0(W0),sz00) ) )).

fof(mSuccLess,axiom,(
    ! [W0,W1] :
      ( ( aElementOf0(W0,szNzAzT0)
        & aElementOf0(W1,szNzAzT0) )
     => ( sdtlseqdt0(W0,W1)
      <=> sdtlseqdt0(szszuzczcdt0(W0),szszuzczcdt0(W1)) ) ) )).

fof(mLessSucc,axiom,(
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => sdtlseqdt0(W0,szszuzczcdt0(W0)) ) )).

fof(mLessRefl,axiom,(
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => sdtlseqdt0(W0,W0) ) )).

fof(mLessASymm,axiom,(
    ! [W0,W1] :
      ( ( aElementOf0(W0,szNzAzT0)
        & aElementOf0(W1,szNzAzT0) )
     => ( ( sdtlseqdt0(W0,W1)
          & sdtlseqdt0(W1,W0) )
       => W0 = W1 ) ) )).

fof(mLessTrans,axiom,(
    ! [W0,W1,W2] :
      ( ( aElementOf0(W0,szNzAzT0)
        & aElementOf0(W1,szNzAzT0)
        & aElementOf0(W2,szNzAzT0) )
     => ( ( sdtlseqdt0(W0,W1)
          & sdtlseqdt0(W1,W2) )
       => sdtlseqdt0(W0,W2) ) ) )).

fof(mLessTotal,axiom,(
    ! [W0,W1] :
      ( ( aElementOf0(W0,szNzAzT0)
        & aElementOf0(W1,szNzAzT0) )
     => ( sdtlseqdt0(W0,W1)
        | sdtlseqdt0(szszuzczcdt0(W1),W0) ) ) )).

fof(mIHSort,axiom,(
    ! [W0,W1] :
      ( ( aElementOf0(W0,szNzAzT0)
        & aElementOf0(W1,szNzAzT0) )
     => ( iLess0(W0,W1)
       => $true ) ) )).

fof(mIH,axiom,(
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => iLess0(W0,szszuzczcdt0(W0)) ) )).

fof(mCardS,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => aElement0(sbrdtbr0(W0)) ) )).

fof(mCardNum,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => ( aElementOf0(sbrdtbr0(W0),szNzAzT0)
      <=> isFinite0(W0) ) ) )).

fof(mCardEmpty,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => ( sbrdtbr0(W0) = sz00
      <=> W0 = slcrc0 ) ) )).

fof(mCardCons,axiom,(
    ! [W0] :
      ( ( aSet0(W0)
        & isFinite0(W0) )
     => ! [W1] :
          ( aElement0(W1)
         => ( ~ aElementOf0(W1,W0)
           => sbrdtbr0(sdtpldt0(W0,W1)) = szszuzczcdt0(sbrdtbr0(W0)) ) ) ) )).

fof(mCardDiff,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => ! [W1] :
          ( ( isFinite0(W0)
            & aElementOf0(W1,W0) )
         => szszuzczcdt0(sbrdtbr0(sdtmndt0(W0,W1))) = sbrdtbr0(W0) ) ) )).

fof(mCardSub,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => ! [W1] :
          ( ( isFinite0(W0)
            & aSubsetOf0(W1,W0) )
         => sdtlseqdt0(sbrdtbr0(W1),sbrdtbr0(W0)) ) ) )).

fof(mCardSubEx,axiom,(
    ! [W0,W1] :
      ( ( aSet0(W0)
        & aElementOf0(W1,szNzAzT0) )
     => ( ( isFinite0(W0)
          & sdtlseqdt0(W1,sbrdtbr0(W0)) )
       => ? [W2] :
            ( aSubsetOf0(W2,W0)
            & sbrdtbr0(W2) = W1 ) ) ) )).

fof(mDefMin,definition,(
    ! [W0] :
      ( ( aSubsetOf0(W0,szNzAzT0)
        & W0 != slcrc0 )
     => ! [W1] :
          ( W1 = szmzizndt0(W0)
        <=> ( aElementOf0(W1,W0)
            & ! [W2] :
                ( aElementOf0(W2,W0)
               => sdtlseqdt0(W1,W2) ) ) ) ) )).

fof(mDefMax,definition,(
    ! [W0] :
      ( ( aSubsetOf0(W0,szNzAzT0)
        & isFinite0(W0)
        & W0 != slcrc0 )
     => ! [W1] :
          ( W1 = szmzazxdt0(W0)
        <=> ( aElementOf0(W1,W0)
            & ! [W2] :
                ( aElementOf0(W2,W0)
               => sdtlseqdt0(W2,W1) ) ) ) ) )).

fof(mMinMin,axiom,(
    ! [W0,W1] :
      ( ( aSubsetOf0(W0,szNzAzT0)
        & aSubsetOf0(W1,szNzAzT0)
        & W0 != slcrc0
        & W1 != slcrc0 )
     => ( ( aElementOf0(szmzizndt0(W0),W1)
          & aElementOf0(szmzizndt0(W1),W0) )
       => szmzizndt0(W0) = szmzizndt0(W1) ) ) )).

fof(mDefSeg,definition,(
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => ! [W1] :
          ( W1 = slbdtrb0(W0)
        <=> ( aSet0(W1)
            & ! [W2] :
                ( aElementOf0(W2,W1)
              <=> ( aElementOf0(W2,szNzAzT0)
                  & sdtlseqdt0(szszuzczcdt0(W2),W0) ) ) ) ) ) )).

fof(mSegFin,axiom,(
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => isFinite0(slbdtrb0(W0)) ) )).

fof(mSegZero,axiom,(
    slbdtrb0(sz00) = slcrc0 )).

fof(mSegSucc,axiom,(
    ! [W0,W1] :
      ( ( aElementOf0(W0,szNzAzT0)
        & aElementOf0(W1,szNzAzT0) )
     => ( aElementOf0(W0,slbdtrb0(szszuzczcdt0(W1)))
      <=> ( aElementOf0(W0,slbdtrb0(W1))
          | W0 = W1 ) ) ) )).

fof(mSegLess,axiom,(
    ! [W0,W1] :
      ( ( aElementOf0(W0,szNzAzT0)
        & aElementOf0(W1,szNzAzT0) )
     => ( sdtlseqdt0(W0,W1)
      <=> aSubsetOf0(slbdtrb0(W0),slbdtrb0(W1)) ) ) )).

fof(mFinSubSeg,axiom,(
    ! [W0] :
      ( ( aSubsetOf0(W0,szNzAzT0)
        & isFinite0(W0) )
     => ? [W1] :
          ( aElementOf0(W1,szNzAzT0)
          & aSubsetOf0(W0,slbdtrb0(W1)) ) ) )).

fof(mCardSeg,axiom,(
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => sbrdtbr0(slbdtrb0(W0)) = W0 ) )).

fof(mDefSel,definition,(
    ! [W0,W1] :
      ( ( aSet0(W0)
        & aElementOf0(W1,szNzAzT0) )
     => ! [W2] :
          ( W2 = slbdtsldtrb0(W0,W1)
        <=> ( aSet0(W2)
            & ! [W3] :
                ( aElementOf0(W3,W2)
              <=> ( aSubsetOf0(W3,W0)
                  & sbrdtbr0(W3) = W1 ) ) ) ) ) )).

fof(mSelFSet,axiom,(
    ! [W0] :
      ( ( aSet0(W0)
        & isFinite0(W0) )
     => ! [W1] :
          ( aElementOf0(W1,szNzAzT0)
         => isFinite0(slbdtsldtrb0(W0,W1)) ) ) )).

fof(mSelNSet,axiom,(
    ! [W0] :
      ( ( aSet0(W0)
        & ~ isFinite0(W0) )
     => ! [W1] :
          ( aElementOf0(W1,szNzAzT0)
         => slbdtsldtrb0(W0,W1) != slcrc0 ) ) )).

fof(mSelCSet,axiom,(
    ! [W0] :
      ( ( aSet0(W0)
        & isCountable0(W0) )
     => ! [W1] :
          ( ( aElementOf0(W1,szNzAzT0)
            & W1 != sz00 )
         => isCountable0(slbdtsldtrb0(W0,W1)) ) ) )).

fof(mSelSub,axiom,(
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => ! [W1,W2] :
          ( ( aSet0(W1)
            & aSet0(W2)
            & W0 != sz00 )
         => ( ( aSubsetOf0(slbdtsldtrb0(W1,W0),slbdtsldtrb0(W2,W0))
              & slbdtsldtrb0(W1,W0) != slcrc0 )
           => aSubsetOf0(W1,W2) ) ) ) )).

fof(mSelExtra,axiom,(
    ! [W0,W1] :
      ( ( aSet0(W0)
        & aElementOf0(W1,szNzAzT0) )
     => ! [W2] :
          ( ( aSubsetOf0(W2,slbdtsldtrb0(W0,W1))
            & isFinite0(W2) )
         => ? [W3] :
              ( aSubsetOf0(W3,W0)
              & isFinite0(W3)
              & aSubsetOf0(W2,slbdtsldtrb0(W3,W1)) ) ) ) )).

fof(mFunSort,axiom,(
    ! [W0] :
      ( aFunction0(W0)
     => $true ) )).

fof(mDomSet,axiom,(
    ! [W0] :
      ( aFunction0(W0)
     => aSet0(szDzozmdt0(W0)) ) )).

fof(mImgElm,axiom,(
    ! [W0] :
      ( aFunction0(W0)
     => ! [W1] :
          ( aElementOf0(W1,szDzozmdt0(W0))
         => aElement0(sdtlpdtrp0(W0,W1)) ) ) )).

fof(mDefPtt,definition,(
    ! [W0,W1] :
      ( ( aFunction0(W0)
        & aElement0(W1) )
     => ! [W2] :
          ( W2 = sdtlbdtrb0(W0,W1)
        <=> ( aSet0(W2)
            & ! [W3] :
                ( aElementOf0(W3,W2)
              <=> ( aElementOf0(W3,szDzozmdt0(W0))
                  & sdtlpdtrp0(W0,W3) = W1 ) ) ) ) ) )).

fof(m__2693,hypothesis,
    ( aFunction0(xF)
    & aElement0(xy) )).

fof(m__,conjecture,
    ( ( aSet0(sdtlbdtrb0(xF,xy))
      & ! [W0] :
          ( aElementOf0(W0,sdtlbdtrb0(xF,xy))
        <=> ( aElementOf0(W0,szDzozmdt0(xF))
            & sdtlpdtrp0(xF,W0) = xy ) ) )
   => ( ! [W0] :
          ( aElementOf0(W0,sdtlbdtrb0(xF,xy))
         => aElementOf0(W0,szDzozmdt0(xF)) )
      | aSubsetOf0(sdtlbdtrb0(xF,xy),szDzozmdt0(xF)) ) )).

%------------------------------------------------------------------------------
