%------------------------------------------------------------------------------
% File     : RNG092+2 : TPTP v6.1.0. Released v4.0.0.
% Domain   : Ring Theory
% Problem  : Chinese remainder theorem in a ring 03_08, 01 expansion
% Version  : Especial.
% English  :

% Refs     : [VLP07] Verchinine et al. (2007), System for Automated Deduction
%          : [Pas08] Paskevich (2008), Email to G. Sutcliffe
% Source   : [Pas08]
% Names    : chines_03_08.01 [Pas08]

% Status   : Theorem
% Rating   : 0.36 v6.1.0, 0.40 v6.0.0, 0.43 v5.5.0, 0.59 v5.4.0, 0.64 v5.3.0, 0.63 v5.2.0, 0.45 v5.1.0, 0.48 v5.0.0, 0.54 v4.1.0, 0.61 v4.0.1, 0.87 v4.0.0
% Syntax   : Number of formulae    :   26 (   3 unit)
%            Number of atoms       :  139 (  32 equality)
%            Maximal formula depth :   28 (   6 average)
%            Number of connectives :  114 (   1 ~  ;   4  |;  63  &)
%                                         (   6 <=>;  40 =>;   0 <=)
%                                         (   0 <~>;   0 ~|;   0 ~&)
%            Number of predicates  :    5 (   0 propositional; 1-2 arity)
%            Number of functors    :    9 (   4 constant; 0-2 arity)
%            Number of variables   :   74 (   0 singleton;  58 !;  16 ?)
%            Maximal term depth    :    3 (   1 average)
% SPC      : FOF_THM_RFO_SEQ

% Comments : Problem generated by the SAD system [VLP07]
%------------------------------------------------------------------------------
fof(mElmSort,axiom,(
    ! [W0] :
      ( aElement0(W0)
     => $true ) )).

fof(mSortsC,axiom,(
    aElement0(sz00) )).

fof(mSortsC_01,axiom,(
    aElement0(sz10) )).

fof(mSortsU,axiom,(
    ! [W0] :
      ( aElement0(W0)
     => aElement0(smndt0(W0)) ) )).

fof(mSortsB,axiom,(
    ! [W0,W1] :
      ( ( aElement0(W0)
        & aElement0(W1) )
     => aElement0(sdtpldt0(W0,W1)) ) )).

fof(mSortsB_02,axiom,(
    ! [W0,W1] :
      ( ( aElement0(W0)
        & aElement0(W1) )
     => aElement0(sdtasdt0(W0,W1)) ) )).

fof(mAddComm,axiom,(
    ! [W0,W1] :
      ( ( aElement0(W0)
        & aElement0(W1) )
     => sdtpldt0(W0,W1) = sdtpldt0(W1,W0) ) )).

fof(mAddAsso,axiom,(
    ! [W0,W1,W2] :
      ( ( aElement0(W0)
        & aElement0(W1)
        & aElement0(W2) )
     => sdtpldt0(sdtpldt0(W0,W1),W2) = sdtpldt0(W0,sdtpldt0(W1,W2)) ) )).

fof(mAddZero,axiom,(
    ! [W0] :
      ( aElement0(W0)
     => ( sdtpldt0(W0,sz00) = W0
        & W0 = sdtpldt0(sz00,W0) ) ) )).

fof(mAddInvr,axiom,(
    ! [W0] :
      ( aElement0(W0)
     => ( sdtpldt0(W0,smndt0(W0)) = sz00
        & sz00 = sdtpldt0(smndt0(W0),W0) ) ) )).

fof(mMulComm,axiom,(
    ! [W0,W1] :
      ( ( aElement0(W0)
        & aElement0(W1) )
     => sdtasdt0(W0,W1) = sdtasdt0(W1,W0) ) )).

fof(mMulAsso,axiom,(
    ! [W0,W1,W2] :
      ( ( aElement0(W0)
        & aElement0(W1)
        & aElement0(W2) )
     => sdtasdt0(sdtasdt0(W0,W1),W2) = sdtasdt0(W0,sdtasdt0(W1,W2)) ) )).

fof(mMulUnit,axiom,(
    ! [W0] :
      ( aElement0(W0)
     => ( sdtasdt0(W0,sz10) = W0
        & W0 = sdtasdt0(sz10,W0) ) ) )).

fof(mAMDistr,axiom,(
    ! [W0,W1,W2] :
      ( ( aElement0(W0)
        & aElement0(W1)
        & aElement0(W2) )
     => ( sdtasdt0(W0,sdtpldt0(W1,W2)) = sdtpldt0(sdtasdt0(W0,W1),sdtasdt0(W0,W2))
        & sdtasdt0(sdtpldt0(W1,W2),W0) = sdtpldt0(sdtasdt0(W1,W0),sdtasdt0(W2,W0)) ) ) )).

fof(mMulMnOne,axiom,(
    ! [W0] :
      ( aElement0(W0)
     => ( sdtasdt0(smndt0(sz10),W0) = smndt0(W0)
        & smndt0(W0) = sdtasdt0(W0,smndt0(sz10)) ) ) )).

fof(mMulZero,axiom,(
    ! [W0] :
      ( aElement0(W0)
     => ( sdtasdt0(W0,sz00) = sz00
        & sz00 = sdtasdt0(sz00,W0) ) ) )).

fof(mCancel,axiom,(
    ! [W0,W1] :
      ( ( aElement0(W0)
        & aElement0(W1) )
     => ( sdtasdt0(W0,W1) = sz00
       => ( W0 = sz00
          | W1 = sz00 ) ) ) )).

fof(mUnNeZr,axiom,(
    sz10 != sz00 )).

fof(mSetSort,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => $true ) )).

fof(mEOfElem,axiom,(
    ! [W0] :
      ( aSet0(W0)
     => ! [W1] :
          ( aElementOf0(W1,W0)
         => aElement0(W1) ) ) )).

fof(mSetEq,axiom,(
    ! [W0,W1] :
      ( ( aSet0(W0)
        & aSet0(W1) )
     => ( ( ! [W2] :
              ( aElementOf0(W2,W0)
             => aElementOf0(W2,W1) )
          & ! [W2] :
              ( aElementOf0(W2,W1)
             => aElementOf0(W2,W0) ) )
       => W0 = W1 ) ) )).

fof(mDefSSum,definition,(
    ! [W0,W1] :
      ( ( aSet0(W0)
        & aSet0(W1) )
     => ! [W2] :
          ( W2 = sdtpldt1(W0,W1)
        <=> ( aSet0(W2)
            & ! [W3] :
                ( aElementOf0(W3,W2)
              <=> ? [W4,W5] :
                    ( aElementOf0(W4,W0)
                    & aElementOf0(W5,W1)
                    & sdtpldt0(W4,W5) = W3 ) ) ) ) ) )).

fof(mDefSInt,definition,(
    ! [W0,W1] :
      ( ( aSet0(W0)
        & aSet0(W1) )
     => ! [W2] :
          ( W2 = sdtasasdt0(W0,W1)
        <=> ( aSet0(W2)
            & ! [W3] :
                ( aElementOf0(W3,W2)
              <=> ( aElementOf0(W3,W0)
                  & aElementOf0(W3,W1) ) ) ) ) ) )).

fof(mDefIdeal,definition,(
    ! [W0] :
      ( aIdeal0(W0)
    <=> ( aSet0(W0)
        & ! [W1] :
            ( aElementOf0(W1,W0)
           => ( ! [W2] :
                  ( aElementOf0(W2,W0)
                 => aElementOf0(sdtpldt0(W1,W2),W0) )
              & ! [W2] :
                  ( aElement0(W2)
                 => aElementOf0(sdtasdt0(W2,W1),W0) ) ) ) ) ) )).

fof(m__870,hypothesis,
    ( aSet0(xI)
    & ! [W0] :
        ( aElementOf0(W0,xI)
       => ( ! [W1] :
              ( aElementOf0(W1,xI)
             => aElementOf0(sdtpldt0(W0,W1),xI) )
          & ! [W1] :
              ( aElement0(W1)
             => aElementOf0(sdtasdt0(W1,W0),xI) ) ) )
    & aIdeal0(xI)
    & aSet0(xJ)
    & ! [W0] :
        ( aElementOf0(W0,xJ)
       => ( ! [W1] :
              ( aElementOf0(W1,xJ)
             => aElementOf0(sdtpldt0(W0,W1),xJ) )
          & ! [W1] :
              ( aElement0(W1)
             => aElementOf0(sdtasdt0(W1,W0),xJ) ) ) )
    & aIdeal0(xJ) )).

fof(m__,conjecture,
    ( ! [W0,W1,W2] :
        ( ( ( ? [W3,W4] :
                ( aElementOf0(W3,xI)
                & aElementOf0(W4,xJ)
                & sdtpldt0(W3,W4) = W0 )
            | aElementOf0(W0,sdtpldt1(xI,xJ)) )
          & ( ? [W3,W4] :
                ( aElementOf0(W3,xI)
                & aElementOf0(W4,xJ)
                & sdtpldt0(W3,W4) = W1 )
            | aElementOf0(W1,sdtpldt1(xI,xJ)) )
          & aElement0(W2) )
       => ? [W3,W4] :
            ( aElementOf0(W3,xI)
            & aElementOf0(W4,xJ)
            & W0 = sdtpldt0(W3,W4)
            & ? [W5,W6] :
                ( aElementOf0(W5,xI)
                & aElementOf0(W6,xJ)
                & W1 = sdtpldt0(W5,W6)
                & aElementOf0(sdtpldt0(W3,W5),xI)
                & aElementOf0(sdtpldt0(W4,W6),xJ)
                & aElementOf0(sdtasdt0(W2,W3),xI)
                & aElementOf0(sdtasdt0(W2,W4),xJ)
                & sdtpldt0(W0,W1) = sdtpldt0(sdtpldt0(W3,W5),sdtpldt0(W4,W6))
                & ? [W7,W8] :
                    ( aElementOf0(W7,xI)
                    & aElementOf0(W8,xJ)
                    & sdtpldt0(W7,W8) = sdtpldt0(W0,W1) )
                & aElementOf0(sdtpldt0(W0,W1),sdtpldt1(xI,xJ))
                & ? [W7,W8] :
                    ( aElementOf0(W7,xI)
                    & aElementOf0(W8,xJ)
                    & sdtpldt0(W7,W8) = sdtasdt0(W2,W0) )
                & aElementOf0(sdtasdt0(W2,W0),sdtpldt1(xI,xJ)) ) ) )
   => ( ( aSet0(sdtpldt1(xI,xJ))
        & ! [W0] :
            ( aElementOf0(W0,sdtpldt1(xI,xJ))
          <=> ? [W1,W2] :
                ( aElementOf0(W1,xI)
                & aElementOf0(W2,xJ)
                & sdtpldt0(W1,W2) = W0 ) ) )
     => ( ! [W0] :
            ( aElementOf0(W0,sdtpldt1(xI,xJ))
           => ( ! [W1] :
                  ( aElementOf0(W1,sdtpldt1(xI,xJ))
                 => aElementOf0(sdtpldt0(W0,W1),sdtpldt1(xI,xJ)) )
              & ! [W1] :
                  ( aElement0(W1)
                 => aElementOf0(sdtasdt0(W1,W0),sdtpldt1(xI,xJ)) ) ) )
        | aIdeal0(sdtpldt1(xI,xJ)) ) ) )).

%------------------------------------------------------------------------------
