%------------------------------------------------------------------------------
% File     : RNG067+1 : TPTP v6.1.0. Released v4.0.0.
% Domain   : Ring Theory
% Problem  : Cauchy-Bouniakowsky-Schwarz inequality 05_16_03_01, 00 expansion
% Version  : Especial.
% English  :

% Refs     : [VLP07] Verchinine et al. (2007), System for Automated Deduction
%          : [Pas08] Paskevich (2008), Email to G. Sutcliffe
% Source   : [Pas08]
% Names    : cauchy_05_16_03_01.00 [Pas08]

% Status   : Theorem
% Rating   : 0.40 v6.1.0, 0.50 v6.0.0, 0.52 v5.5.0, 0.70 v5.4.0, 0.71 v5.3.0, 0.67 v5.2.0, 0.60 v5.1.0, 0.62 v5.0.0, 0.75 v4.1.0, 0.83 v4.0.1, 0.96 v4.0.0
% Syntax   : Number of formulae    :   59 (   8 unit)
%            Number of atoms       :  190 (  57 equality)
%            Maximal formula depth :   10 (   4 average)
%            Number of connectives :  137 (   6 ~  ;   1  |;  76  &)
%                                         (   1 <=>;  53 =>;   0 <=)
%                                         (   0 <~>;   0 ~|;   0 ~&)
%            Number of predicates  :    6 (   0 propositional; 1-2 arity)
%            Number of functors    :   26 (  18 constant; 0-2 arity)
%            Number of variables   :   71 (   0 singleton;  70 !;   1 ?)
%            Maximal term depth    :    5 (   2 average)
% SPC      : FOF_THM_RFO_SEQ

% Comments : Problem generated by the SAD system [VLP07]
%------------------------------------------------------------------------------
fof(mNatSort,axiom,(
    ! [W0] :
      ( aNaturalNumber0(W0)
     => $true ) )).

fof(mZeroNat,axiom,(
    aNaturalNumber0(sz00) )).

fof(mSuccNat,axiom,(
    ! [W0] :
      ( aNaturalNumber0(W0)
     => ( aNaturalNumber0(szszuzczcdt0(W0))
        & szszuzczcdt0(W0) != sz00 ) ) )).

fof(mNatExtr,axiom,(
    ! [W0] :
      ( ( aNaturalNumber0(W0)
        & W0 != sz00 )
     => ? [W1] :
          ( aNaturalNumber0(W1)
          & W0 = szszuzczcdt0(W1) ) ) )).

fof(mSuccEqu,axiom,(
    ! [W0,W1] :
      ( ( aNaturalNumber0(W0)
        & aNaturalNumber0(W1) )
     => ( szszuzczcdt0(W0) = szszuzczcdt0(W1)
       => W0 = W1 ) ) )).

fof(mIHOrd,axiom,(
    ! [W0,W1] :
      ( ( aNaturalNumber0(W0)
        & aNaturalNumber0(W1) )
     => ( iLess0(W0,W1)
       => $true ) ) )).

fof(mIH,axiom,(
    ! [W0] :
      ( aNaturalNumber0(W0)
     => iLess0(W0,szszuzczcdt0(W0)) ) )).

fof(mScSort,axiom,(
    ! [W0] :
      ( aScalar0(W0)
     => $true ) )).

fof(mSZeroSc,axiom,(
    aScalar0(sz0z00) )).

fof(mSumSc,axiom,(
    ! [W0,W1] :
      ( ( aScalar0(W0)
        & aScalar0(W1) )
     => aScalar0(sdtpldt0(W0,W1)) ) )).

fof(mMulSc,axiom,(
    ! [W0,W1] :
      ( ( aScalar0(W0)
        & aScalar0(W1) )
     => aScalar0(sdtasdt0(W0,W1)) ) )).

fof(mNegSc,axiom,(
    ! [W0] :
      ( aScalar0(W0)
     => aScalar0(smndt0(W0)) ) )).

fof(mScZero,axiom,(
    ! [W0] :
      ( aScalar0(W0)
     => ( sdtpldt0(W0,sz0z00) = W0
        & sdtpldt0(sz0z00,W0) = W0
        & sdtasdt0(W0,sz0z00) = sz0z00
        & sdtasdt0(sz0z00,W0) = sz0z00
        & sdtpldt0(W0,smndt0(W0)) = sz0z00
        & sdtpldt0(smndt0(W0),W0) = sz0z00
        & smndt0(smndt0(W0)) = W0
        & smndt0(sz0z00) = sz0z00 ) ) )).

fof(mArith,axiom,(
    ! [W0,W1,W2] :
      ( ( aScalar0(W0)
        & aScalar0(W1)
        & aScalar0(W2) )
     => ( sdtpldt0(sdtpldt0(W0,W1),W2) = sdtpldt0(W0,sdtpldt0(W1,W2))
        & sdtpldt0(W0,W1) = sdtpldt0(W1,W0)
        & sdtasdt0(sdtasdt0(W0,W1),W2) = sdtasdt0(W0,sdtasdt0(W1,W2))
        & sdtasdt0(W0,W1) = sdtasdt0(W1,W0) ) ) )).

fof(mDistr,axiom,(
    ! [W0,W1,W2] :
      ( ( aScalar0(W0)
        & aScalar0(W1)
        & aScalar0(W2) )
     => ( sdtasdt0(W0,sdtpldt0(W1,W2)) = sdtpldt0(sdtasdt0(W0,W1),sdtasdt0(W0,W2))
        & sdtasdt0(sdtpldt0(W0,W1),W2) = sdtpldt0(sdtasdt0(W0,W2),sdtasdt0(W1,W2)) ) ) )).

fof(mDistr2,axiom,(
    ! [W0,W1,W2,W3] :
      ( ( aScalar0(W0)
        & aScalar0(W1)
        & aScalar0(W2)
        & aScalar0(W3) )
     => sdtasdt0(sdtpldt0(W0,W1),sdtpldt0(W2,W3)) = sdtpldt0(sdtpldt0(sdtasdt0(W0,W2),sdtasdt0(W0,W3)),sdtpldt0(sdtasdt0(W1,W2),sdtasdt0(W1,W3))) ) )).

fof(mMNeg,axiom,(
    ! [W0,W1] :
      ( ( aScalar0(W0)
        & aScalar0(W1) )
     => ( sdtasdt0(W0,smndt0(W1)) = smndt0(sdtasdt0(W0,W1))
        & sdtasdt0(smndt0(W0),W1) = smndt0(sdtasdt0(W0,W1)) ) ) )).

fof(mMDNeg,axiom,(
    ! [W0,W1] :
      ( ( aScalar0(W0)
        & aScalar0(W1) )
     => sdtasdt0(smndt0(W0),smndt0(W1)) = sdtasdt0(W0,W1) ) )).

fof(mLess,axiom,(
    ! [W0,W1] :
      ( ( aScalar0(W0)
        & aScalar0(W1) )
     => ( sdtlseqdt0(W0,W1)
       => $true ) ) )).

fof(mLERef,axiom,(
    ! [W0] :
      ( aScalar0(W0)
     => sdtlseqdt0(W0,W0) ) )).

fof(mLEASm,axiom,(
    ! [W0,W1] :
      ( ( aScalar0(W0)
        & aScalar0(W1) )
     => ( ( sdtlseqdt0(W0,W1)
          & sdtlseqdt0(W1,W0) )
       => W0 = W1 ) ) )).

fof(mLETrn,axiom,(
    ! [W0,W1,W2] :
      ( ( aScalar0(W0)
        & aScalar0(W1)
        & aScalar0(W2) )
     => ( ( sdtlseqdt0(W0,W1)
          & sdtlseqdt0(W1,W2) )
       => sdtlseqdt0(W0,W2) ) ) )).

fof(mLEMon,axiom,(
    ! [W0,W1,W2,W3] :
      ( ( aScalar0(W0)
        & aScalar0(W1)
        & aScalar0(W2)
        & aScalar0(W3) )
     => ( ( sdtlseqdt0(W0,W1)
          & sdtlseqdt0(W2,W3) )
       => sdtlseqdt0(sdtpldt0(W0,W2),sdtpldt0(W1,W3)) ) ) )).

fof(mLEMonM,axiom,(
    ! [W0,W1,W2,W3] :
      ( ( aScalar0(W0)
        & aScalar0(W1)
        & aScalar0(W2)
        & aScalar0(W3) )
     => ( ( sdtlseqdt0(W0,W1)
          & sdtlseqdt0(sz0z00,W2)
          & sdtlseqdt0(W2,W3) )
       => sdtlseqdt0(sdtasdt0(W0,W2),sdtasdt0(W1,W3)) ) ) )).

fof(mLETot,axiom,(
    ! [W0,W1] :
      ( ( aScalar0(W0)
        & aScalar0(W1) )
     => ( sdtlseqdt0(W0,W1)
        | sdtlseqdt0(W1,W0) ) ) )).

fof(mPosMon,axiom,(
    ! [W0,W1] :
      ( ( aScalar0(W0)
        & aScalar0(W1) )
     => ( ( sdtlseqdt0(sz0z00,W0)
          & sdtlseqdt0(sz0z00,W1) )
       => ( sdtlseqdt0(sz0z00,sdtpldt0(W0,W1))
          & sdtlseqdt0(sz0z00,sdtasdt0(W0,W1)) ) ) ) )).

fof(mSqPos,axiom,(
    ! [W0] :
      ( aScalar0(W0)
     => sdtlseqdt0(sz0z00,sdtasdt0(W0,W0)) ) )).

fof(mSqrt,axiom,(
    ! [W0,W1] :
      ( ( aScalar0(W0)
        & aScalar0(W1) )
     => ( ( sdtlseqdt0(sz0z00,W0)
          & sdtlseqdt0(sz0z00,W1)
          & sdtasdt0(W0,W0) = sdtasdt0(W1,W1) )
       => W0 = W1 ) ) )).

fof(mVcSort,axiom,(
    ! [W0] :
      ( aVector0(W0)
     => $true ) )).

fof(mDimNat,axiom,(
    ! [W0] :
      ( aVector0(W0)
     => aNaturalNumber0(aDimensionOf0(W0)) ) )).

fof(mElmSc,axiom,(
    ! [W0,W1] :
      ( ( aVector0(W0)
        & aNaturalNumber0(W1) )
     => aScalar0(sdtlbdtrb0(W0,W1)) ) )).

fof(mDefInit,definition,(
    ! [W0] :
      ( aVector0(W0)
     => ( aDimensionOf0(W0) != sz00
       => ! [W1] :
            ( W1 = sziznziztdt0(W0)
          <=> ( aVector0(W1)
              & szszuzczcdt0(aDimensionOf0(W1)) = aDimensionOf0(W0)
              & ! [W2] :
                  ( aNaturalNumber0(W2)
                 => sdtlbdtrb0(W1,W2) = sdtlbdtrb0(W0,W2) ) ) ) ) ) )).

fof(mEqInit,axiom,(
    ! [W0,W1] :
      ( ( aVector0(W0)
        & aVector0(W1) )
     => ( ( aDimensionOf0(W0) = aDimensionOf0(W1)
          & aDimensionOf0(W1) != sz00 )
       => aDimensionOf0(sziznziztdt0(W0)) = aDimensionOf0(sziznziztdt0(W1)) ) ) )).

fof(mScPr,axiom,(
    ! [W0,W1] :
      ( ( aVector0(W0)
        & aVector0(W1) )
     => ( aDimensionOf0(W0) = aDimensionOf0(W1)
       => aScalar0(sdtasasdt0(W0,W1)) ) ) )).

fof(mDefSPZ,axiom,(
    ! [W0,W1] :
      ( ( aVector0(W0)
        & aVector0(W1) )
     => ( ( aDimensionOf0(W0) = aDimensionOf0(W1)
          & aDimensionOf0(W1) = sz00 )
       => sdtasasdt0(W0,W1) = sz0z00 ) ) )).

fof(mDefSPN,axiom,(
    ! [W0,W1] :
      ( ( aVector0(W0)
        & aVector0(W1) )
     => ( ( aDimensionOf0(W0) = aDimensionOf0(W1)
          & aDimensionOf0(W1) != sz00 )
       => sdtasasdt0(W0,W1) = sdtpldt0(sdtasasdt0(sziznziztdt0(W0),sziznziztdt0(W1)),sdtasdt0(sdtlbdtrb0(W0,aDimensionOf0(W0)),sdtlbdtrb0(W1,aDimensionOf0(W1)))) ) ) )).

fof(mScSqPos,axiom,(
    ! [W0] :
      ( aVector0(W0)
     => sdtlseqdt0(sz0z00,sdtasasdt0(W0,W0)) ) )).

fof(m__1678,hypothesis,
    ( aVector0(xs)
    & aVector0(xt) )).

fof(m__1652,hypothesis,(
    ! [W0,W1] :
      ( ( aVector0(W0)
        & aVector0(W1) )
     => ( aDimensionOf0(W0) = aDimensionOf0(W1)
       => ( iLess0(aDimensionOf0(W0),aDimensionOf0(xs))
         => sdtlseqdt0(sdtasdt0(sdtasasdt0(W0,W1),sdtasasdt0(W0,W1)),sdtasdt0(sdtasasdt0(W0,W0),sdtasasdt0(W1,W1))) ) ) ) )).

fof(m__1678_01,hypothesis,(
    aDimensionOf0(xs) = aDimensionOf0(xt) )).

fof(m__1692,hypothesis,(
    aDimensionOf0(xs) != sz00 )).

fof(m__1709,hypothesis,
    ( aVector0(xp)
    & xp = sziznziztdt0(xs) )).

fof(m__1726,hypothesis,
    ( aVector0(xq)
    & xq = sziznziztdt0(xt) )).

fof(m__1746,hypothesis,
    ( aScalar0(xA)
    & xA = sdtlbdtrb0(xs,aDimensionOf0(xs)) )).

fof(m__1766,hypothesis,
    ( aScalar0(xB)
    & xB = sdtlbdtrb0(xt,aDimensionOf0(xt)) )).

fof(m__1783,hypothesis,
    ( aScalar0(xC)
    & xC = sdtasasdt0(xp,xp) )).

fof(m__1800,hypothesis,
    ( aScalar0(xD)
    & xD = sdtasasdt0(xq,xq) )).

fof(m__1820,hypothesis,
    ( aScalar0(xE)
    & xE = sdtasasdt0(xp,xq) )).

fof(m__1837,hypothesis,
    ( aScalar0(xF)
    & xF = sdtasdt0(xA,xA) )).

fof(m__1854,hypothesis,
    ( aScalar0(xG)
    & xG = sdtasdt0(xB,xB) )).

fof(m__1873,hypothesis,
    ( aScalar0(xH)
    & xH = sdtasdt0(xA,xB) )).

fof(m__1892,hypothesis,
    ( aScalar0(xR)
    & xR = sdtasdt0(xC,xG) )).

fof(m__1911,hypothesis,
    ( aScalar0(xP)
    & xP = sdtasdt0(xE,xH) )).

fof(m__1930,hypothesis,
    ( aScalar0(xS)
    & xS = sdtasdt0(xF,xD) )).

fof(m__1949,hypothesis,
    ( aScalar0(xN)
    & xN = sdtasdt0(xR,xS) )).

fof(m__1967,hypothesis,(
    sdtlseqdt0(sdtasdt0(xE,xE),sdtasdt0(xC,xD)) )).

fof(m__2004,hypothesis,(
    sdtlseqdt0(sdtasdt0(xP,xP),xN) )).

fof(m__2104,hypothesis,(
    sdtlseqdt0(sdtpldt0(sdtasdt0(xP,xP),sdtasdt0(xP,xP)),sdtpldt0(sdtasdt0(xR,xR),sdtasdt0(xS,xS))) )).

fof(m__,conjecture,(
    sdtlseqdt0(sdtpldt0(sdtpldt0(sdtpldt0(sdtasdt0(xP,xP),sdtasdt0(xP,xP)),sdtasdt0(xP,xP)),sdtasdt0(xP,xP)),sdtpldt0(sdtpldt0(sdtpldt0(sdtasdt0(xR,xR),sdtasdt0(xS,xS)),xN),xN)) )).

%------------------------------------------------------------------------------
