on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
  push:
  workflow_dispatch:
jobs:
  build_lambdapi:
    strategy:
      fail-fast: false
      matrix:
        ocaml-version: [5.2.0, 5.1.1, 5.0.0, 4.14.1, 4.13.1, 4.12.1, 4.11.2, 4.10.2, 4.09.1, 4.08.1]
    runs-on: ubuntu-latest
    steps:
      - name: checking out lambdapi repo ...
        uses: actions/checkout@v4
      - name: recovering cached opam files ...
        uses: actions/cache@v4
        with:
          path: ~/.opam
          key: ${{ runner.os }}-ocaml-${{ matrix.ocaml-version }}
      - name: setting up opam ...
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
      - name: installing dependencies ...
        run: |
          opam pin add -n -k path zenon_modulo .
          opam install --deps-only zenon_modulo
      - name: compiling zenon_modulo ...
        run: |
          eval `opam env`
          ./configure
          make zenon_modulo.bin
          
